from __future__ import annotations

import calendar
import logging
import os
import re
import threading
from dataclasses import dataclass
from datetime import date, datetime
from statistics import fmean
from typing import Any, Dict, List, Optional, Tuple

from db import fetch_ohlc_series_from_oracle
try:
    from services.ath_service import get_all_time_high_for_symbols, log_stale_snapshot_warning
except Exception:  # pragma: no cover
    from .ath_service import get_all_time_high_for_symbols, log_stale_snapshot_warning  # type: ignore

try:
    from services.technical_score_engine import calculate_master_trend
except Exception:  # pragma: no cover
    from .technical_score_engine import calculate_master_trend  # type: ignore

try:
    from db_pool import pool
except Exception:  # pragma: no cover
    pool = None  # type: ignore


EMA_PERIOD = 50
RSI_PERIOD = 14
ATR_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
VOL_WINDOW = 20

BHRAMHASTRA_MIN_EMA = float(os.getenv("BHRAMHASTRA_MIN_EMA", "50"))
BHRAMHASTRA_MIN_RSI = float(os.getenv("BHRAMHASTRA_MIN_RSI", "50"))
BHRAMHASTRA_MAX_RSI = float(os.getenv("BHRAMHASTRA_MAX_RSI", "55"))
BHRAMHASTRA_MIN_MACD = float(os.getenv("BHRAMHASTRA_MIN_MACD", "0"))
BHRAMHASTRA_MIN_VOLUME = float(os.getenv("BHRAMHASTRA_MIN_VOLUME", "20"))
BHRAMHASTRA_STOP_PCT = float(os.getenv("BHRAMHASTRA_STOP_PCT", "0.05"))
BHRAMHASTRA_STOP_ATR_MULT = float(os.getenv("BHRAMHASTRA_STOP_ATR_MULT", "1.0"))
BHRAMHASTRA_TARGET1_RR = float(os.getenv("BHRAMHASTRA_TARGET1_RR", "2.0"))
BHRAMHASTRA_TARGET2_RR = float(os.getenv("BHRAMHASTRA_TARGET2_RR", "3.0"))
BHRAMHASTRA_CUTOFF_MONTHS = int(os.getenv("BHRAMHASTRA_CUTOFF_MONTHS", "36"))
BHRAMHASTRA_SETUP_TYPE = "EMA50 + RSI50-55 + MACD + Volume"

BHRAMHASTRA_TABLE = (os.getenv("BHRAMHASTRA_TABLE") or "Bhramhastra_BackTesting_Data").strip()
_BHRAMHASTRA_SCHEMA = (os.getenv("BHRAMHASTRA_SCHEMA") or os.getenv("ORACLE_SCHEMA") or "").strip()
if _BHRAMHASTRA_SCHEMA and "." not in BHRAMHASTRA_TABLE:
    BHRAMHASTRA_TABLE = f"{_BHRAMHASTRA_SCHEMA}.{BHRAMHASTRA_TABLE}"

_IDENT_RE = re.compile(r'^[A-Za-z0-9_.$#]+$')
_DDL_LOCK = threading.Lock()
_DDL_READY = False

VALID_TIMEFRAMES = ("daily", "weekly", "monthly", "yearly")
_logger = logging.getLogger(__name__)


def _execute_ddl(conn, ddl: str) -> None:
    with conn.cursor() as cur:
        try:
            cur.execute(ddl)
        except Exception as exc:
            msg = str(exc)
            if 'ORA-00955' in msg or 'ORA-01408' in msg:
                return
            raise


def _ensure_bhramhastra_objects(conn) -> None:
    global _DDL_READY
    if _DDL_READY:
        return
    with _DDL_LOCK:
        if _DDL_READY:
            return
        _execute_ddl(conn, f'''
            CREATE TABLE {BHRAMHASTRA_TABLE} (
              ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
              S_NO             NUMBER,
              SYMBOL           VARCHAR2(30) NOT NULL,
              STOCK_NAME       VARCHAR2(200),
              LTC_DATE         DATE NOT NULL,
              TRADE_DATE       DATE,
              FIRST_TRADE_DATE DATE,
              CALENDAR_DAYS    NUMBER,
              TRADING_DAYS     NUMBER,
              ENTRY_PRICE      NUMBER(18,4),
              EMA50            NUMBER(18,4),
              RSI14            NUMBER(10,4),
              MACD_HIST        NUMBER(18,6),
              VOLUME           NUMBER(20,2),
              ATR14            NUMBER(18,4),
              RISK_AMOUNT      NUMBER(18,4),
              TARGET1          NUMBER(18,4),
              TARGET2          NUMBER(18,4),
              TARGET1_RRR      NUMBER(10,4) DEFAULT 2,
              TARGET2_RRR      NUMBER(10,4) DEFAULT 3,
              STOP_LOSS        NUMBER(18,4),
              BACKTEST_DATE    DATE,
              HIGH_52W         NUMBER(18,4),
              LOW_52W          NUMBER(18,4),
              ATH              NUMBER(18,4),
              HIGH_1Y          NUMBER(18,4),
              HIGH_2Y          NUMBER(18,4),
              SUPPORT_PRICE    NUMBER(18,4),
              RESISTANCE_PRICE NUMBER(18,4),
              EXIT_DATE        DATE,
              EXIT_PRICE       NUMBER(18,4),
              EXIT_REASON      VARCHAR2(30),
              STATUS           VARCHAR2(20) DEFAULT 'OPEN',
              CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT UK_BHRAMHASTRA_BT_SIGNAL UNIQUE (SYMBOL, LTC_DATE)
            )
        ''')
        _execute_ddl(conn, f'CREATE INDEX IDX_BHRAMHASTRA_BT_LTC_DATE ON {BHRAMHASTRA_TABLE} (LTC_DATE)')
        _execute_ddl(conn, f'CREATE INDEX IDX_BHRAMHASTRA_BT_STATUS ON {BHRAMHASTRA_TABLE} (STATUS)')
        conn.commit()
        _DDL_READY = True


def _split_owner_and_table(name: str) -> Tuple[str, str]:
    raw = (name or "").strip()
    if "." in raw:
        owner, table = raw.rsplit(".", 1)
    else:
        owner, table = _BHRAMHASTRA_SCHEMA, raw
    return owner.strip('"').upper(), table.strip('"').upper()


def _id_is_identity(conn) -> bool:
    owner, table = _split_owner_and_table(BHRAMHASTRA_TABLE)
    with conn.cursor() as cur:
        try:
            cur.execute(
                """
                SELECT 1
                FROM USER_TAB_IDENTITY_COLS
                WHERE TABLE_NAME = :table_name
                  AND COLUMN_NAME = 'ID'
                """,
                {"table_name": table},
            )
            if cur.fetchone():
                return True
        except Exception:
            pass
        try:
            bind = {"table_name": table}
            sql = (
                """
                SELECT 1
                FROM ALL_TAB_IDENTITY_COLS
                WHERE TABLE_NAME = :table_name
                  AND COLUMN_NAME = 'ID'
                """
            )
            if owner:
                sql += " AND OWNER = :owner"
                bind["owner"] = owner
            cur.execute(sql, bind)
            return bool(cur.fetchone())
        except Exception:
            return False


def _assign_explicit_ids(conn, rows: List[Dict[str, Any]]) -> None:
    if not rows:
        return
    with conn.cursor() as cur:
        cur.execute(f"LOCK TABLE {BHRAMHASTRA_TABLE} IN EXCLUSIVE MODE")
        cur.execute(f"SELECT NVL(MAX(ID), 0) FROM {BHRAMHASTRA_TABLE}")
        row = cur.fetchone()
        base_id = int(row[0] or 0) if row else 0
    for offset, payload in enumerate(rows, start=1):
        payload["id"] = base_id + offset


@dataclass
class Candle:
    date: datetime
    open: float
    high: float
    low: float
    close: float
    volume: Optional[float]


def _normalize_timeframe(value: Optional[str]) -> str:
    if value is None or not str(value).strip():
        return "daily"
    tf = str(value).strip().lower()
    if tf not in VALID_TIMEFRAMES:
        raise ValueError("Invalid timeframe")
    return tf


def _min_required_candles(timeframe: str) -> int:
    baseline = max(EMA_PERIOD, RSI_PERIOD, ATR_PERIOD, MACD_SLOW)
    if timeframe == "yearly":
        baseline = max(baseline, 6)
    return baseline + 2


def _months_ago(base: date, months: int) -> date:
    year = base.year
    month = base.month - months
    while month <= 0:
        month += 12
        year -= 1
    day = min(base.day, calendar.monthrange(year, month)[1])
    return date(year, month, day)


def _cutoff_date_iso(months: int) -> Optional[str]:
    if months <= 0:
        return None
    cutoff = _months_ago(datetime.utcnow().date(), months)
    return cutoff.strftime("%Y-%m-%d")


def _cutoff_months_for_timeframe(timeframe: str) -> int:
    base = max(1, BHRAMHASTRA_CUTOFF_MONTHS)
    if timeframe == "monthly":
        return max(base, 48)
    if timeframe == "yearly":
        return max(base, 96)
    return base


def _periods_per_year(timeframe: str) -> int:
    return {
        "daily": 252,
        "weekly": 52,
        "monthly": 12,
        "yearly": 1,
    }.get(timeframe, 252)


def _aggregate_candles(candles: List[Candle], timeframe: str) -> List[Candle]:
    if timeframe == "daily":
        return candles

    buckets: Dict[Tuple[int, int], Dict[str, Any]] = {}
    for candle in candles:
        dt = candle.date
        if timeframe == "weekly":
            iso = dt.isocalendar()
            key = (iso[0], iso[1])
        elif timeframe == "monthly":
            key = (dt.year, dt.month)
        elif timeframe == "yearly":
            key = (dt.year, 0)
        else:
            return candles

        bucket = buckets.get(key)
        if bucket is None:
            volume_val = candle.volume if candle.volume is not None else None
            buckets[key] = {
                "date": dt,
                "open": candle.open,
                "high": candle.high,
                "low": candle.low,
                "close": candle.close,
                "volume": volume_val,
            }
            continue

        bucket["high"] = max(bucket["high"], candle.high)
        bucket["low"] = min(bucket["low"], candle.low)
        bucket["close"] = candle.close
        if bucket["open"] is None:
            bucket["open"] = candle.open
        if candle.volume is not None:
            bucket["volume"] = (bucket["volume"] or 0.0) + candle.volume
        bucket["date"] = dt

    aggregated: List[Candle] = []
    for bucket in sorted(buckets.values(), key=lambda b: b["date"]):
        aggregated.append(Candle(
            date=bucket["date"],
            open=bucket["open"],
            high=bucket["high"],
            low=bucket["low"],
            close=bucket["close"],
            volume=bucket["volume"],
        ))
    return aggregated


def _build_candles(entries: List[Dict[str, Any]]) -> List[Candle]:
    candles: List[Candle] = []
    for entry in entries:
        dt = entry.get("date")
        close_val = _safe_float(entry.get("close"))
        if not isinstance(dt, datetime) or close_val is None:
            continue
        open_val = _safe_float(entry.get("open")) or close_val
        high_val = _safe_float(entry.get("high")) or close_val
        low_val = _safe_float(entry.get("low")) or close_val
        volume_val = _safe_float(entry.get("volume"))
        candles.append(Candle(
            date=dt,
            open=open_val,
            high=high_val,
            low=low_val,
            close=close_val,
            volume=volume_val,
        ))
    candles.sort(key=lambda c: c.date)
    return candles


def _safe_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _safe_round(value: Optional[float], digits: int = 2) -> Optional[float]:
    if value is None:
        return None
    try:
        return round(float(value), digits)
    except (TypeError, ValueError):
        return None


def _source_series_stats(raw_series: Dict[str, List[Dict[str, Any]]]) -> Tuple[int, int, str]:
    row_count = 0
    latest = ""
    for entries in raw_series.values():
        if not isinstance(entries, list):
            continue
        row_count += len(entries)
        for entry in entries:
            value = entry.get("date") if isinstance(entry, dict) else None
            token = _fmt_iso(value) if isinstance(value, datetime) else ""
            if token and token > latest:
                latest = token
    return len(raw_series), row_count, latest


def _ema_series(values: List[float], period: int) -> List[Optional[float]]:
    if not values:
        return []
    k = 2 / (period + 1)
    out: List[Optional[float]] = []
    prev: Optional[float] = None
    for value in values:
        prev = value if prev is None else (value - prev) * k + prev
        out.append(prev)
    return out


def _compute_macd(closes: List[float]) -> Tuple[Optional[float], Optional[float], Optional[float]]:
    if len(closes) < MACD_SLOW + 1:
        return None, None, None
    ema_fast = _ema_series(closes, MACD_FAST)
    ema_slow = _ema_series(closes, MACD_SLOW)
    macd_line: List[float] = []
    for fast, slow in zip(ema_fast, ema_slow):
        if fast is None or slow is None:
            macd_line.append(0.0)
        else:
            macd_line.append(float(fast) - float(slow))
    signal_line = _ema_series(macd_line, MACD_SIGNAL)
    if not signal_line:
        return None, None, None
    return macd_line[-1], signal_line[-1], macd_line[-1] - (signal_line[-1] or 0.0)


def _compute_rsi_series(closes: List[float], period: int = RSI_PERIOD) -> List[Optional[float]]:
    if len(closes) < period + 1:
        return [None] * len(closes)
    rsi_values: List[Optional[float]] = [None] * len(closes)
    gains = []
    losses = []
    for i in range(1, period + 1):
        delta = closes[i] - closes[i - 1]
        gains.append(max(delta, 0.0))
        losses.append(max(-delta, 0.0))
    avg_gain = sum(gains) / period
    avg_loss = sum(losses) / period
    rs = (avg_gain / avg_loss) if avg_loss > 0 else None
    rsi_values[period] = 100.0 if rs is None else 100 - (100 / (1 + rs))
    for idx in range(period + 1, len(closes)):
        delta = closes[idx] - closes[idx - 1]
        gain = max(delta, 0.0)
        loss = max(-delta, 0.0)
        avg_gain = ((avg_gain * (period - 1)) + gain) / period
        avg_loss = ((avg_loss * (period - 1)) + loss) / period
        if avg_loss == 0:
            rsi_values[idx] = 100.0
        else:
            rs = avg_gain / avg_loss
            rsi_values[idx] = 100 - (100 / (1 + rs))
    return rsi_values


def _true_ranges(candles: List[Candle]) -> List[float]:
    ranges: List[float] = []
    prev_close: Optional[float] = None
    for candle in candles:
        high = candle.high
        low = candle.low
        close = candle.close
        if prev_close is None:
            tr = high - low
        else:
            tr = max(high - low, abs(high - prev_close), abs(low - prev_close))
        ranges.append(tr)
        prev_close = close
    return ranges


def _wilder_atr(trs: List[float], period: int) -> List[Optional[float]]:
    length = len(trs)
    if length < period:
        return [None] * length
    atrs: List[Optional[float]] = [None] * length
    first_avg = sum(trs[:period]) / period
    atrs[period - 1] = first_avg
    for idx in range(period, length):
        prev_atr = atrs[idx - 1]
        if prev_atr is None:
            prev_atr = first_avg
        atrs[idx] = ((prev_atr * (period - 1)) + trs[idx]) / period
    return atrs


def _compute_adx_last(candles: List[Candle], period: int = 14) -> Optional[float]:
    if len(candles) < period + 1:
        return None

    tr_list: List[float] = []
    plus_dm_list: List[float] = []
    minus_dm_list: List[float] = []

    for idx in range(1, len(candles)):
        current = candles[idx]
        previous = candles[idx - 1]
        up_move = current.high - previous.high
        down_move = previous.low - current.low
        plus_dm = up_move if up_move > down_move and up_move > 0 else 0.0
        minus_dm = down_move if down_move > up_move and down_move > 0 else 0.0
        true_range = max(
            current.high - current.low,
            abs(current.high - previous.close),
            abs(current.low - previous.close),
        )
        tr_list.append(true_range)
        plus_dm_list.append(plus_dm)
        minus_dm_list.append(minus_dm)

    if len(tr_list) < period:
        return None

    tr_sum = sum(tr_list[:period])
    plus_dm_sum = sum(plus_dm_list[:period])
    minus_dm_sum = sum(minus_dm_list[:period])

    def _di(dm_value: float, tr_value: float) -> float:
        return 100.0 * dm_value / tr_value if tr_value else 0.0

    plus_di = _di(plus_dm_sum, tr_sum)
    minus_di = _di(minus_dm_sum, tr_sum)
    denom = plus_di + minus_di
    dx_list: List[float] = [100.0 * abs(plus_di - minus_di) / denom if denom else 0.0]

    for idx in range(period, len(tr_list)):
        tr_sum = tr_sum - (tr_sum / period) + tr_list[idx]
        plus_dm_sum = plus_dm_sum - (plus_dm_sum / period) + plus_dm_list[idx]
        minus_dm_sum = minus_dm_sum - (minus_dm_sum / period) + minus_dm_list[idx]
        plus_di = _di(plus_dm_sum, tr_sum)
        minus_di = _di(minus_dm_sum, tr_sum)
        denom = plus_di + minus_di
        dx_list.append(100.0 * abs(plus_di - minus_di) / denom if denom else 0.0)

    if len(dx_list) < period:
        return None

    adx = sum(dx_list[:period]) / period
    for dx in dx_list[period:]:
        adx = ((adx * (period - 1)) + dx) / period
    return adx


def _apply_trend_display_fields(row: Dict[str, Any]) -> None:
    try:
        trend_result = calculate_master_trend(row)
    except Exception:
        _logger.exception("bhramhastra_trend_display_failed symbol=%s", row.get("symbol"))
        return
    trend = str(trend_result.get("trend") or "").strip()
    if not trend:
        return
    row["trend"] = trend
    row["trendDirection"] = trend
    row["trendSort"] = trend_result.get("trendSort")
    row["trendDirectionSort"] = trend_result.get("trendSort")
    row["trendDecisionReason"] = trend_result.get("trendDecisionReason")
    row["trendSource"] = trend_result.get("trendSource")


def _first_present(row: Dict[str, Any], *keys: str) -> Any:
    for key in keys:
        value = row.get(key)
        if value is None:
            continue
        if isinstance(value, str) and not value.strip():
            continue
        return value
    return None


def _missing_display_value(row: Dict[str, Any], key: str) -> bool:
    value = row.get(key)
    return value is None or (isinstance(value, str) and not value.strip())


def _set_if_missing(row: Dict[str, Any], key: str, value: Any) -> bool:
    if value is None or not _missing_display_value(row, key):
        return False
    row[key] = value
    return True


def _gap_pct(price: Any, ath: Any) -> Optional[float]:
    price_num = _safe_float(price)
    ath_num = _safe_float(ath)
    if price_num is None or ath_num is None or ath_num == 0:
        return None
    return ((price_num - ath_num) / ath_num) * 100.0


def _repair_row_display_fields(row: Dict[str, Any], candles: List[Candle]) -> bool:
    changed = False

    price = _safe_float(_first_present(row, "priceSort", "price", "entryPrice", "close", "PRICE"))
    if price is None and candles:
        price = candles[-1].close
    if price is not None:
        changed = _set_if_missing(row, "price", _safe_round(price, 2)) or changed
        changed = _set_if_missing(row, "priceSort", price) or changed

    ath = _safe_float(_first_present(row, "ath", "ATH"))
    if ath is None and candles:
        ath = _calc_ath(candles)

    gap = _gap_pct(price, ath)
    if gap is not None:
        changed = _set_if_missing(row, "gap", _safe_round(gap, 2)) or changed
        changed = _set_if_missing(row, "gapSort", gap) or changed
        changed = _set_if_missing(row, "GAP", _safe_round(gap, 2)) or changed
        changed = _set_if_missing(row, "GAP_SORT", gap) or changed

    changed = _set_if_missing(row, "setupType", BHRAMHASTRA_SETUP_TYPE) or changed
    changed = _set_if_missing(row, "setup_type", BHRAMHASTRA_SETUP_TYPE) or changed

    if not candles:
        return changed

    closes = [c.close for c in candles]
    ema20_series = _ema_series(closes, 20)
    ema50_series = _ema_series(closes, EMA_PERIOD)
    ema100_series = _ema_series(closes, 100)
    ema200_series = _ema_series(closes, 200)
    ema20 = ema20_series[-1] if ema20_series else None
    ema50 = ema50_series[-1] if ema50_series else None
    ema100 = ema100_series[-1] if ema100_series else None
    ema200 = ema200_series[-1] if ema200_series else None
    adx_now = _compute_adx_last(candles, 14)

    changed = _set_if_missing(row, "ema20", _safe_round(ema20, 2)) or changed
    changed = _set_if_missing(row, "ema20Sort", ema20) or changed
    changed = _set_if_missing(row, "ema50", _safe_round(ema50, 2)) or changed
    changed = _set_if_missing(row, "ema50Sort", ema50) or changed
    changed = _set_if_missing(row, "ema100", _safe_round(ema100, 2)) or changed
    changed = _set_if_missing(row, "ema100Sort", ema100) or changed
    changed = _set_if_missing(row, "ema200", _safe_round(ema200, 2)) or changed
    changed = _set_if_missing(row, "ema200Sort", ema200) or changed
    changed = _set_if_missing(row, "adx14", _safe_round(adx_now, 2)) or changed
    changed = _set_if_missing(row, "adx14Sort", adx_now) or changed

    if _missing_display_value(row, "trendDirection"):
        before = row.get("trendDirection")
        _apply_trend_display_fields(row)
        changed = changed or row.get("trendDirection") != before

    return changed


def repair_bhramhastra_display_fields(payload: Dict[str, Any] | None, timeframe: Optional[str] = None) -> Tuple[Dict[str, Any], int]:
    """Backfill display-only fields on existing rows without changing strategy membership."""
    if not isinstance(payload, dict):
        return {}, 0
    rows = payload.get("rows")
    if not isinstance(rows, list) or not rows:
        return payload, 0

    tf = _normalize_timeframe(timeframe or str(payload.get("timeframe") or "daily"))
    row_items = [row for row in rows if isinstance(row, dict)]
    repaired_row_ids: set[int] = set()
    for row in row_items:
        changed = _set_if_missing(row, "setupType", BHRAMHASTRA_SETUP_TYPE)
        changed = _set_if_missing(row, "setup_type", BHRAMHASTRA_SETUP_TYPE) or changed
        if changed:
            repaired_row_ids.add(id(row))

    needs_repair = [
        row for row in row_items
        if any(_missing_display_value(row, key) for key in ("ema20", "ema100", "ema200", "adx14", "trendDirection", "gap"))
    ]
    if not needs_repair:
        repaired = len(repaired_row_ids)
        if repaired:
            payload["displayFieldsRepairedAt"] = datetime.utcnow().isoformat() + "Z"
            payload["displayFieldsSource"] = "NSE_NIFTY500_DAILY_RAW_DATA_DEV"
        return payload, repaired

    raw_series = fetch_ohlc_series_from_oracle(months=_cutoff_months_for_timeframe(tf))
    series_by_symbol = {str(symbol).strip().upper(): entries for symbol, entries in raw_series.items()}

    for row in needs_repair:
        symbol = str(_first_present(row, "symbol", "stockName", "stock", "SYMBOL") or "").strip().upper()
        entries = series_by_symbol.get(symbol) or []
        candles = _aggregate_candles(_build_candles(entries), tf)
        if _repair_row_display_fields(row, candles):
            repaired_row_ids.add(id(row))

    repaired = len(repaired_row_ids)
    if not repaired:
        return payload, 0

    payload["displayFieldsRepairedAt"] = datetime.utcnow().isoformat() + "Z"
    payload["displayFieldsSource"] = "NSE_NIFTY500_DAILY_RAW_DATA_DEV"
    return payload, repaired


def _avg_volume(candles: List[Candle]) -> Optional[float]:
    volumes = [c.volume for c in candles if c.volume is not None and c.volume > 0]
    if not volumes:
        return None
    window = volumes[-VOL_WINDOW:] if len(volumes) >= VOL_WINDOW else volumes
    return fmean(window) if window else None


def _calc_high_low(candles: List[Candle], window: int) -> Tuple[Optional[float], Optional[float]]:
    if not candles:
        return None, None
    subset = candles[-window:] if len(candles) >= window else candles
    highs = [c.high for c in subset if c.high is not None]
    lows = [c.low for c in subset if c.low is not None]
    return (max(highs) if highs else None, min(lows) if lows else None)


def _calc_ath(candles: List[Candle]) -> Optional[float]:
    highs = [c.high for c in candles if c.high is not None]
    return max(highs) if highs else None


def _support_resistance(candles: List[Candle], window: int = 20) -> Tuple[Optional[float], Optional[float]]:
    if not candles:
        return None, None
    subset = candles[-window:] if len(candles) >= window else candles
    lows = [c.low for c in subset if c.low is not None]
    highs = [c.high for c in subset if c.high is not None]
    support = min(lows) if lows else None
    resistance = max(highs) if highs else None
    return support, resistance


def _fmt_iso(value: Optional[datetime]) -> Optional[str]:
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d")
    return None


def _compute_targets(price: float, atr_value: Optional[float]) -> Tuple[float, float, float, float]:
    atr_risk = (atr_value or 0.0) * BHRAMHASTRA_STOP_ATR_MULT
    risk = max((price * BHRAMHASTRA_STOP_PCT) + atr_risk, price * 0.0025)
    target1 = price + (risk * BHRAMHASTRA_TARGET1_RR)
    target2 = price + (risk * BHRAMHASTRA_TARGET2_RR)
    stop_loss = price - risk
    return target1, target2, stop_loss, risk


def compute_bhramhastra_scan(timeframe: Optional[str] = None) -> Tuple[Dict[str, Any], Dict[str, Dict[str, Any]]]:
    tf = _normalize_timeframe(timeframe)
    cutoff_months = _cutoff_months_for_timeframe(tf)
    cutoff_date_iso = _cutoff_date_iso(cutoff_months)
    try:
        raw_series = fetch_ohlc_series_from_oracle(months=cutoff_months)
    except Exception:
        _logger.exception(
            "bhramhastra_compute_db_error timeframe=%s stage=fetch_ohlc_series cutoff_months=%s",
            tf,
            cutoff_months,
        )
        raise
    source_symbols, source_rows, source_latest_date = _source_series_stats(raw_series)
    _logger.info(
        "bhramhastra_compute_source timeframe=%s cutoff_date=%s latest_trading_date=%s sql_rows_returned=%s source_symbols=%s",
        tf,
        cutoff_date_iso,
        source_latest_date or "-",
        source_rows,
        source_symbols,
    )
    ath_records: Dict[str, Dict[str, Any]] = {}
    try:
        ath_records = get_all_time_high_for_symbols(
            None,
            include_date=True,
            endpoint='/api/bhramhastra',
        )
    except Exception:
        _logger.exception('[ATH] Failed to fetch ATH map for Bhramhastra payload')
        ath_records = {}

    rows: List[Dict[str, Any]] = []
    latest_snapshot: Dict[str, Dict[str, Any]] = {}
    min_required = _min_required_candles(tf)
    periods_per_year = _periods_per_year(tf)
    stale_ath_detected = False

    for symbol, entries in raw_series.items():
        symbol_key = str(symbol).strip().upper()
        candles = _build_candles(entries)
        candles = _aggregate_candles(candles, tf)
        if len(candles) < min_required:
            continue

        latest = candles[-1]
        first_candle = candles[0] if candles else None
        closes = [c.close for c in candles]
        price = latest.close
        latest_snapshot[str(symbol).strip().upper()] = {
            "tradeDate": latest.date,
            "high": latest.high,
            "low": latest.low,
            "close": latest.close,
        }

        ema20_series = _ema_series(closes, 20)
        ema50_series = _ema_series(closes, EMA_PERIOD)
        ema100_series = _ema_series(closes, 100)
        ema200_series = _ema_series(closes, 200)
        ema20 = ema20_series[-1] if ema20_series else None
        ema50 = ema50_series[-1] if ema50_series else None
        ema100 = ema100_series[-1] if ema100_series else None
        ema200 = ema200_series[-1] if ema200_series else None

        rsi_series = _compute_rsi_series(closes, RSI_PERIOD)
        rsi_now = rsi_series[-1] if rsi_series else None

        macd_line, macd_signal, macd_hist = _compute_macd(closes)

        trs = _true_ranges(candles)
        atr_series = _wilder_atr(trs, ATR_PERIOD)
        atr_now = atr_series[-1] if atr_series else None
        adx_now = _compute_adx_last(candles, 14)

        avg_volume = _avg_volume(candles)
        volume_now = latest.volume

        high52, low52 = _calc_high_low(candles, periods_per_year)
        high1y, _ = _calc_high_low(candles, periods_per_year)
        high2y, _ = _calc_high_low(candles, periods_per_year * 2)
        fallback_ath = _calc_ath(candles)
        ath_record = ath_records.get(symbol_key) or {}
        authoritative_ath = _safe_float(ath_record.get('ath'))
        ath = authoritative_ath if authoritative_ath is not None else fallback_ath
        ath_date = ath_record.get('ath_date')
        if authoritative_ath is not None and fallback_ath is not None and abs(float(authoritative_ath) - float(fallback_ath)) > 0.0001:
            stale_ath_detected = True
        support, resistance = _support_resistance(candles)

        ema_ok = ema50 is not None and ema50 > BHRAMHASTRA_MIN_EMA
        rsi_ok = rsi_now is not None and (rsi_now >= BHRAMHASTRA_MIN_RSI and rsi_now <= BHRAMHASTRA_MAX_RSI)
        macd_ok = macd_hist is not None and macd_hist > BHRAMHASTRA_MIN_MACD
        volume_ok = volume_now is not None and volume_now > BHRAMHASTRA_MIN_VOLUME
        conditions_met = ema_ok and rsi_ok and macd_ok and volume_ok
        if not conditions_met:
            continue

        target1, target2, stop_loss, risk_amount = _compute_targets(price, atr_now)
        gap = _gap_pct(price, ath)
        trade_date_iso = _fmt_iso(latest.date)
        first_trade_iso = _fmt_iso(first_candle.date) if first_candle else None
        calendar_days = None
        trading_days = len(candles)
        if first_candle and latest:
            first_dt = first_candle.date.date() if isinstance(first_candle.date, datetime) else first_candle.date
            last_dt = latest.date.date() if isinstance(latest.date, datetime) else latest.date
            calendar_days = (last_dt - first_dt).days

        row_payload = {
            "symbol": str(symbol).strip().upper(),
            "stockName": str(symbol).strip().upper(),
            "tradeDate": trade_date_iso,
            "tradeDateSort": trade_date_iso,
            "firstTradeDate": first_trade_iso,
            "firstTradeDateSort": first_trade_iso,
            "ltcDate": trade_date_iso,
            "ltcDateSort": trade_date_iso,
            "calendarDays": calendar_days,
            "calendarDaysSort": calendar_days,
            "tradingDays": trading_days,
            "tradingDaysSort": trading_days,
            "price": _safe_round(price, 2),
            "priceSort": price,
            "close": _safe_round(price, 2),
            "ema20": _safe_round(ema20, 2),
            "ema20Sort": ema20,
            "emaDays": _safe_round(ema50, 2),
            "emaDaysSort": ema50,
            "ema50": _safe_round(ema50, 2),
            "ema50Sort": ema50,
            "ema100": _safe_round(ema100, 2),
            "ema100Sort": ema100,
            "ema200": _safe_round(ema200, 2),
            "ema200Sort": ema200,
            "rsi": _safe_round(rsi_now, 2),
            "rsiSort": rsi_now,
            "macd": _safe_round(macd_hist, 4),
            "macdHist": _safe_round(macd_hist, 4),
            "macdSort": macd_hist,
            "macdHistSort": macd_hist,
            "volume": _safe_round(volume_now, 2) if volume_now is not None else None,
            "volumeSort": volume_now,
            "atr": _safe_round(atr_now, 2),
            "atr14": _safe_round(atr_now, 2),
            "atrSort": atr_now,
            "atr14Sort": atr_now,
            "adx14": _safe_round(adx_now, 2),
            "adx14Sort": adx_now,
            "backtestDate": trade_date_iso,
            "riskAmount": _safe_round(risk_amount, 2),
            "target1Rrr": BHRAMHASTRA_TARGET1_RR,
            "target2Rrr": BHRAMHASTRA_TARGET2_RR,
            "target1": _safe_round(target1, 2),
            "target2": _safe_round(target2, 2),
            "stopLoss": _safe_round(stop_loss, 2),
            "high52": _safe_round(high52, 2),
            "low52": _safe_round(low52, 2),
            "ath": _safe_round(ath, 2),
            "athDate": ath_date,
            "ath_date": ath_date,
            "high1y": _safe_round(high1y, 2),
            "high2y": _safe_round(high2y, 2),
            "support": _safe_round(support, 2),
            "resistance": _safe_round(resistance, 2),
            "entryPrice": _safe_round(price, 2),
            "avgVolume20": _safe_round(avg_volume, 2),
            "gap": _safe_round(gap, 2),
            "gapSort": gap,
            "GAP": _safe_round(gap, 2),
            "GAP_SORT": gap,
            "setupType": BHRAMHASTRA_SETUP_TYPE,
            "setup_type": BHRAMHASTRA_SETUP_TYPE,
        }
        _apply_trend_display_fields(row_payload)
        rows.append(row_payload)

    rows.sort(key=lambda item: (item.get("symbol") or ""))
    for idx, row in enumerate(rows, start=1):
        row["sNo"] = idx
    first_symbols = [str(row.get("symbol") or "").strip() for row in rows[:3]]
    _logger.info(
        "bhramhastra_compute_done timeframe=%s latest_trading_date=%s sql_rows_returned=%s rows_after_filter=%s first_symbols=%s zero_reason=%s",
        tf,
        source_latest_date or "-",
        source_rows,
        len(rows),
        ",".join([symbol for symbol in first_symbols if symbol]) or "-",
        "strategy_filters_returned_zero_rows" if not rows else "-",
    )

    payload = {
        "rows": rows,
        "count": len(rows),
        "generatedAt": datetime.utcnow().isoformat() + "Z",
        "timeframe": tf,
        "cutoffDateIso": cutoff_date_iso,
        "athSource": "NSE_NIFTY500_DAILY_RAW_DATA_DEV",
    }
    if stale_ath_detected:
        log_stale_snapshot_warning(endpoint='/api/bhramhastra', source='computed-candles')
    return payload, latest_snapshot



def _parse_row_date(value: Any) -> Optional[date]:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    token = text[:10]
    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d", "%d/%m/%Y"):
        try:
            return datetime.strptime(token, fmt).date()
        except Exception:
            continue
    return None


def fetch_bhramhastra_max_ltc_date() -> Optional[str]:
    if pool is None:
        raise RuntimeError("Oracle pool is unavailable for Bhramhastra queries")
    with pool.acquire() as conn:
        _ensure_bhramhastra_objects(conn)
        with conn.cursor() as cur:
            cur.execute(f"SELECT TO_CHAR(MAX(LTC_DATE), 'YYYY-MM-DD') FROM {BHRAMHASTRA_TABLE}")
            row = cur.fetchone()
    return str(row[0]).strip() if row and row[0] else None


def fetch_bhramhastra_source_max_ltc_date() -> Optional[str]:
    if pool is None:
        raise RuntimeError("Oracle pool is unavailable for Bhramhastra source date query")
    schema = (os.getenv("ORACLE_SCHEMA") or "").strip()
    table = (os.getenv("ORACLE_TABLE") or "NSE_NIFTY500_DAILY_RAW_DATA_DEV").strip()
    qualified = f"{schema}.{table}" if schema else table
    if not _IDENT_RE.match(qualified):
        raise ValueError("Invalid Oracle source table name")
    with pool.acquire() as conn:
        with conn.cursor() as cur:
            cur.execute(f"SELECT TO_CHAR(MAX(TRADING_DATE), 'YYYY-MM-DD') FROM {qualified}")
            row = cur.fetchone()
    return str(row[0]).strip() if row and row[0] else None


def _fetch_existing_signal_keys(conn, rows: List[Dict[str, Any]]) -> set[Tuple[str, date]]:
    ltc_dates = sorted({
        parsed
        for parsed in (_parse_row_date(row.get("ltcDate") or row.get("tradeDate")) for row in rows)
        if parsed is not None
    })
    if not ltc_dates:
        return set()
    binds = {f"ltc_date_{idx}": value for idx, value in enumerate(ltc_dates)}
    placeholders = ", ".join(f":ltc_date_{idx}" for idx in range(len(ltc_dates)))
    with conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT SYMBOL, LTC_DATE
            FROM {BHRAMHASTRA_TABLE}
            WHERE LTC_DATE IN ({placeholders})
            """,
            binds,
        )
        existing: set[Tuple[str, date]] = set()
        for symbol, ltc_date in cur.fetchall() or []:
            parsed_date = _parse_row_date(ltc_date)
            normalized_symbol = str(symbol or "").strip().upper()
            if normalized_symbol and parsed_date:
                existing.add((normalized_symbol, parsed_date))
        return existing


def _fetch_symbol_backtest_anchor(conn, symbols: List[str]) -> Dict[str, date]:
    normalized = sorted({str(symbol or "").strip().upper() for symbol in symbols if str(symbol or "").strip()})
    if not normalized:
        return {}
    binds = {f"symbol_{idx}": value for idx, value in enumerate(normalized)}
    placeholders = ", ".join(f":symbol_{idx}" for idx in range(len(normalized)))
    with conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT SYMBOL, MIN(BACKTEST_DATE) AS BACKTEST_DATE
            FROM {BHRAMHASTRA_TABLE}
            WHERE SYMBOL IN ({placeholders})
              AND BACKTEST_DATE IS NOT NULL
            GROUP BY SYMBOL
            """,
            binds,
        )
        anchors: Dict[str, date] = {}
        for symbol, backtest_date in cur.fetchall() or []:
            parsed = _parse_row_date(backtest_date)
            normalized_symbol = str(symbol or "").strip().upper()
            if normalized_symbol and parsed:
                anchors[normalized_symbol] = parsed
        return anchors


def _exit_signal(latest: Dict[str, Any], row: Dict[str, Any]) -> Tuple[Optional[str], Optional[float]]:
    try:
        high = float(latest.get("high") or 0)
        low = float(latest.get("low") or 0)
        target1 = float(row.get("target1") or 0)
        target2 = float(row.get("target2") or 0)
        stop_loss = float(row.get("stopLoss") or 0)
    except (TypeError, ValueError):
        return None, None
    if target2 and high >= target2:
        return "TARGET2", target2
    if target1 and high >= target1:
        return "TARGET1", target1
    if stop_loss and low <= stop_loss:
        return "STOP_LOSS", stop_loss
    return None, None



def upsert_bhramhastra_rows(rows: List[Dict[str, Any]], latest_snapshot: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    if pool is None:
        raise RuntimeError("Oracle pool is unavailable for Bhramhastra upsert")

    inserted = 0
    updated = 0
    payload_skipped = 0
    latest_ltc_date: Optional[date] = None
    open_positions: List[Dict[str, Any]] = []

    with pool.acquire() as conn:
        _ensure_bhramhastra_objects(conn)
        with conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT SYMBOL, LTC_DATE, TARGET1, TARGET2, STOP_LOSS
                FROM {BHRAMHASTRA_TABLE}
                WHERE STATUS = 'OPEN'
                """
            )
            cols = [d[0].lower() for d in (cur.description or [])]
            for row in cur.fetchall() or []:
                open_positions.append(dict(zip(cols, row)))

        updates: List[Dict[str, Any]] = []
        for position in open_positions:
            symbol = str(position.get("symbol") or "").strip().upper()
            latest = latest_snapshot.get(symbol)
            if not latest:
                continue
            reason, exit_price = _exit_signal(latest, {
                "target1": position.get("target1"),
                "target2": position.get("target2"),
                "stopLoss": position.get("stop_loss"),
            })
            if not reason:
                continue
            exit_date = latest.get("tradeDate")
            if isinstance(exit_date, datetime):
                exit_date = exit_date.date()
            updates.append({
                "symbol": symbol,
                "ltc_date": position.get("ltc_date"),
                "exit_date": exit_date,
                "exit_price": exit_price,
                "exit_reason": reason,
            })

        if updates:
            with conn.cursor() as cur:
                cur.executemany(
                    f"""
                    UPDATE {BHRAMHASTRA_TABLE}
                    SET EXIT_DATE = :exit_date,
                        EXIT_PRICE = :exit_price,
                        EXIT_REASON = :exit_reason,
                        STATUS = 'CLOSED',
                        UPDATED_AT = CURRENT_TIMESTAMP
                    WHERE SYMBOL = :symbol
                      AND LTC_DATE = :ltc_date
                      AND STATUS = 'OPEN'
                    """,
                    updates,
                )
                updated = cur.rowcount or len(updates)

        existing_keys = _fetch_existing_signal_keys(conn, rows)
        incoming_symbols = [str(row.get("symbol") or "").strip().upper() for row in rows if str(row.get("symbol") or "").strip()]
        symbol_backtest_anchor = _fetch_symbol_backtest_anchor(conn, incoming_symbols)
        inserts: List[Dict[str, Any]] = []
        seen_keys: set[Tuple[str, date]] = set()
        for row in rows:
            symbol = str(row.get("symbol") or "").strip().upper()
            if not symbol:
                payload_skipped += 1
                continue
            ltc_date = _parse_row_date(row.get("ltcDate") or row.get("tradeDate"))
            trade_date = _parse_row_date(row.get("tradeDate") or row.get("ltcDate"))
            backtest_source = _parse_row_date(
                row.get("backtestDate")
                or row.get("BT_DATE")
                or row.get("bt_date")
                or row.get("backtestingDate")
                or row.get("backtest_date")
                or row.get("backtesting_date")
                or row.get("tradeDate")
                or row.get("ltcDate")
            )
            backtest_date = symbol_backtest_anchor.get(symbol) or backtest_source
            first_trade_date = _parse_row_date(row.get("firstTradeDate"))
            if not ltc_date:
                payload_skipped += 1
                continue
            if ltc_date and (latest_ltc_date is None or ltc_date > latest_ltc_date):
                latest_ltc_date = ltc_date
            key = (symbol, ltc_date)
            if key in seen_keys:
                payload_skipped += 1
                continue
            seen_keys.add(key)
            inserts.append({
                "s_no": row.get("sNo"),
                "symbol": symbol,
                "stock_name": row.get("stockName") or symbol,
                "ltc_date": ltc_date,
                "trade_date": trade_date,
                "first_trade_date": first_trade_date,
                "calendar_days": row.get("calendarDaysSort") or row.get("calendarDays"),
                "trading_days": row.get("tradingDaysSort") or row.get("tradingDays"),
                "entry_price": row.get("entryPrice"),
                "ema50": row.get("emaDaysSort") or row.get("emaDays"),
                "rsi14": row.get("rsiSort") or row.get("rsi"),
                "macd_hist": row.get("macdSort") or row.get("macd"),
                "volume": row.get("volumeSort") or row.get("volume"),
                "atr14": row.get("atrSort") or row.get("atr"),
                "risk_amount": row.get("riskAmount"),
                "target1_rrr": row.get("target1Rrr") or BHRAMHASTRA_TARGET1_RR,
                "target2_rrr": row.get("target2Rrr") or BHRAMHASTRA_TARGET2_RR,
                "high_52w": row.get("high52"),
                "low_52w": row.get("low52"),
                "ath": row.get("ath"),
                "high_1y": row.get("high1y"),
                "high_2y": row.get("high2y"),
                "support_price": row.get("support"),
                "resistance_price": row.get("resistance"),
                "target1": row.get("target1"),
                "target2": row.get("target2"),
                "stop_loss": row.get("stopLoss"),
                "backtest_date": backtest_date,
                "status": "OPEN",
            })

        if inserts:
            new_signal_count = 0
            for row in inserts:
                key = (row["symbol"], row.get("ltc_date"))
                if row.get("ltc_date") and key not in existing_keys:
                    new_signal_count += 1
            use_explicit_id = not _id_is_identity(conn)
            if use_explicit_id:
                _assign_explicit_ids(conn, inserts)
            insert_columns = [
                "S_NO",
                "SYMBOL",
                "STOCK_NAME",
                "LTC_DATE",
                "TRADE_DATE",
                "FIRST_TRADE_DATE",
                "CALENDAR_DAYS",
                "TRADING_DAYS",
                "ENTRY_PRICE",
                "EMA50",
                "RSI14",
                "MACD_HIST",
                "VOLUME",
                "ATR14",
                "RISK_AMOUNT",
                "HIGH_52W",
                "LOW_52W",
                "ATH",
                "HIGH_1Y",
                "HIGH_2Y",
                "SUPPORT_PRICE",
                "RESISTANCE_PRICE",
                "TARGET1",
                "TARGET2",
                "TARGET1_RRR",
                "TARGET2_RRR",
                "STOP_LOSS",
                "BACKTEST_DATE",
                "STATUS",
                "CREATED_AT",
                "UPDATED_AT",
            ]
            insert_values = [
                ":s_no",
                ":symbol",
                ":stock_name",
                ":ltc_date",
                ":trade_date",
                ":first_trade_date",
                ":calendar_days",
                ":trading_days",
                ":entry_price",
                ":ema50",
                ":rsi14",
                ":macd_hist",
                ":volume",
                ":atr14",
                ":risk_amount",
                ":high_52w",
                ":low_52w",
                ":ath",
                ":high_1y",
                ":high_2y",
                ":support_price",
                ":resistance_price",
                ":target1",
                ":target2",
                ":target1_rrr",
                ":target2_rrr",
                ":stop_loss",
                ":backtest_date",
                ":status",
                "CURRENT_TIMESTAMP",
                "CURRENT_TIMESTAMP",
            ]
            if use_explicit_id:
                insert_columns.insert(0, "ID")
                insert_values.insert(0, ":id")
            with conn.cursor() as cur:
                merge_sql = f"""
                    MERGE INTO {BHRAMHASTRA_TABLE} t
                    USING (
                        SELECT :symbol AS symbol, :ltc_date AS ltc_date FROM dual
                    ) src
                    ON (t.SYMBOL = src.symbol AND t.LTC_DATE = src.ltc_date)
                    WHEN MATCHED THEN UPDATE SET
                        S_NO = :s_no,
                        STOCK_NAME = :stock_name,
                        TRADE_DATE = :trade_date,
                        FIRST_TRADE_DATE = :first_trade_date,
                        CALENDAR_DAYS = :calendar_days,
                        TRADING_DAYS = :trading_days,
                        ENTRY_PRICE = :entry_price,
                        EMA50 = :ema50,
                        RSI14 = :rsi14,
                        MACD_HIST = :macd_hist,
                        VOLUME = :volume,
                        ATR14 = :atr14,
                        RISK_AMOUNT = :risk_amount,
                        HIGH_52W = :high_52w,
                        LOW_52W = :low_52w,
                        ATH = :ath,
                        HIGH_1Y = :high_1y,
                        HIGH_2Y = :high_2y,
                        SUPPORT_PRICE = :support_price,
                        RESISTANCE_PRICE = :resistance_price,
                        TARGET1 = :target1,
                        TARGET2 = :target2,
                        TARGET1_RRR = :target1_rrr,
                        TARGET2_RRR = :target2_rrr,
                        STOP_LOSS = :stop_loss,
                        BACKTEST_DATE = NVL(t.BACKTEST_DATE, :backtest_date),
                        STATUS = :status,
                        UPDATED_AT = CURRENT_TIMESTAMP
                    WHEN NOT MATCHED THEN INSERT (
                        {", ".join(insert_columns)}
                    ) VALUES (
                        {", ".join(insert_values)}
                    )
                """
                cur.executemany(merge_sql, inserts)
                inserted = new_signal_count

        conn.commit()

    return {
        "inserted": inserted,
        "updated": updated,
        "skipped": payload_skipped + max(len(inserts) - inserted, 0),
        "latestLtcDate": latest_ltc_date.strftime("%Y-%m-%d") if latest_ltc_date else None,
    }















