-- 02_indexes.sql

-- Symbol search helper
CREATE INDEX IDX_SYMBOLS_NAME ON SYMBOLS (UPPER(NAME));

-- OHLCV indexes (primary key already provides SYMBOL + BAR_DATE)
CREATE INDEX IDX_OHLCV_D_DATE ON OHLCV_D (BAR_DATE);
CREATE INDEX IDX_OHLCV_W_DATE ON OHLCV_W (BAR_DATE);
CREATE INDEX IDX_OHLCV_M_DATE ON OHLCV_M (BAR_DATE);
CREATE INDEX IDX_OHLCV_Y_DATE ON OHLCV_Y (BAR_DATE);

-- Indicators indexes
CREATE INDEX IDX_IND_D_DATE ON INDICATORS_D (BAR_DATE);
CREATE INDEX IDX_IND_W_DATE ON INDICATORS_W (BAR_DATE);
CREATE INDEX IDX_IND_M_DATE ON INDICATORS_M (BAR_DATE);
CREATE INDEX IDX_IND_Y_DATE ON INDICATORS_Y (BAR_DATE);

-- Pivots, SR, patterns, zones
CREATE INDEX IDX_PIVOTS_SYMBOL_TF_DATE ON PIVOTS (SYMBOL, TF, BAR_DATE);
CREATE INDEX IDX_SR_SYMBOL_TF ON SR_LEVELS (SYMBOL, TF);
CREATE INDEX IDX_SR_SYMBOL_TF_LEVEL ON SR_LEVELS (SYMBOL, TF, SR_LEVEL);
CREATE INDEX IDX_PATTERNS_SYMBOL_TF ON PATTERNS (SYMBOL, TF, T1_DATE);
CREATE INDEX IDX_ZONES_SYMBOL_TF ON ZONES (SYMBOL, TF, T1_DATE);
CREATE INDEX IDX_ANNOTATIONS_USER_SYMBOL ON USER_ANNOTATIONS (USER_ID, SYMBOL, TF);


