-- 03_mviews_or_etl.sql
-- Aggregation guidance for OHLCV W/M/Y. Replace bind variables with actual values.

-- Optional partitioning guidance (apply on large datasets):
-- CREATE TABLE OHLCV_D (
--   ...
-- ) PARTITION BY RANGE (BAR_DATE) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (
--   PARTITION P_START VALUES LESS THAN (DATE '2000-01-01')
-- );

-- Weekly aggregation (ISO week start)
MERGE INTO OHLCV_W dst
USING (
  SELECT
    SYMBOL,
    TRUNC(BAR_DATE, 'IW') AS BAR_DATE,
    MIN(LOW_PRICE) AS LOW_PRICE,
    MAX(HIGH_PRICE) AS HIGH_PRICE,
    SUM(VOLUME) AS VOLUME,
    MIN(OPEN_PRICE) KEEP (DENSE_RANK FIRST ORDER BY BAR_DATE) AS OPEN_PRICE,
    MAX(CLOSE_PRICE) KEEP (DENSE_RANK LAST ORDER BY BAR_DATE) AS CLOSE_PRICE
  FROM OHLCV_D
  WHERE BAR_DATE BETWEEN :from_date AND :to_date
  GROUP BY SYMBOL, TRUNC(BAR_DATE, 'IW')
) src
ON (dst.SYMBOL = src.SYMBOL AND dst.BAR_DATE = src.BAR_DATE)
WHEN MATCHED THEN UPDATE SET
  dst.OPEN_PRICE = src.OPEN_PRICE,
  dst.HIGH_PRICE = src.HIGH_PRICE,
  dst.LOW_PRICE = src.LOW_PRICE,
  dst.CLOSE_PRICE = src.CLOSE_PRICE,
  dst.VOLUME = src.VOLUME,
  dst.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  SYMBOL, BAR_DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME
) VALUES (
  src.SYMBOL, src.BAR_DATE, src.OPEN_PRICE, src.HIGH_PRICE, src.LOW_PRICE, src.CLOSE_PRICE, src.VOLUME
);

-- Monthly aggregation
MERGE INTO OHLCV_M dst
USING (
  SELECT
    SYMBOL,
    TRUNC(BAR_DATE, 'MM') AS BAR_DATE,
    MIN(LOW_PRICE) AS LOW_PRICE,
    MAX(HIGH_PRICE) AS HIGH_PRICE,
    SUM(VOLUME) AS VOLUME,
    MIN(OPEN_PRICE) KEEP (DENSE_RANK FIRST ORDER BY BAR_DATE) AS OPEN_PRICE,
    MAX(CLOSE_PRICE) KEEP (DENSE_RANK LAST ORDER BY BAR_DATE) AS CLOSE_PRICE
  FROM OHLCV_D
  WHERE BAR_DATE BETWEEN :from_date AND :to_date
  GROUP BY SYMBOL, TRUNC(BAR_DATE, 'MM')
) src
ON (dst.SYMBOL = src.SYMBOL AND dst.BAR_DATE = src.BAR_DATE)
WHEN MATCHED THEN UPDATE SET
  dst.OPEN_PRICE = src.OPEN_PRICE,
  dst.HIGH_PRICE = src.HIGH_PRICE,
  dst.LOW_PRICE = src.LOW_PRICE,
  dst.CLOSE_PRICE = src.CLOSE_PRICE,
  dst.VOLUME = src.VOLUME,
  dst.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  SYMBOL, BAR_DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME
) VALUES (
  src.SYMBOL, src.BAR_DATE, src.OPEN_PRICE, src.HIGH_PRICE, src.LOW_PRICE, src.CLOSE_PRICE, src.VOLUME
);

-- Yearly aggregation
MERGE INTO OHLCV_Y dst
USING (
  SELECT
    SYMBOL,
    TRUNC(BAR_DATE, 'YYYY') AS BAR_DATE,
    MIN(LOW_PRICE) AS LOW_PRICE,
    MAX(HIGH_PRICE) AS HIGH_PRICE,
    SUM(VOLUME) AS VOLUME,
    MIN(OPEN_PRICE) KEEP (DENSE_RANK FIRST ORDER BY BAR_DATE) AS OPEN_PRICE,
    MAX(CLOSE_PRICE) KEEP (DENSE_RANK LAST ORDER BY BAR_DATE) AS CLOSE_PRICE
  FROM OHLCV_D
  WHERE BAR_DATE BETWEEN :from_date AND :to_date
  GROUP BY SYMBOL, TRUNC(BAR_DATE, 'YYYY')
) src
ON (dst.SYMBOL = src.SYMBOL AND dst.BAR_DATE = src.BAR_DATE)
WHEN MATCHED THEN UPDATE SET
  dst.OPEN_PRICE = src.OPEN_PRICE,
  dst.HIGH_PRICE = src.HIGH_PRICE,
  dst.LOW_PRICE = src.LOW_PRICE,
  dst.CLOSE_PRICE = src.CLOSE_PRICE,
  dst.VOLUME = src.VOLUME,
  dst.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  SYMBOL, BAR_DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME
) VALUES (
  src.SYMBOL, src.BAR_DATE, src.OPEN_PRICE, src.HIGH_PRICE, src.LOW_PRICE, src.CLOSE_PRICE, src.VOLUME
);
