-- 06_price_action_sr_levels_manually.sql
-- Manual TradingView screenshot extraction table.
-- This table is separate from the dynamic SR_LEVELS table used by SR_LEVELS.html.

PROMPT Creating PRICE_ACTION_SR_LEVELS_MANUALLY table...

CREATE TABLE PRICE_ACTION_SR_LEVELS_MANUALLY (
  LEVEL_ID          VARCHAR2(64)   NOT NULL,
  SYMBOL            VARCHAR2(32)   NOT NULL,
  TF                VARCHAR2(4)    NOT NULL,
  LEVEL_TYPE        VARCHAR2(8)    DEFAULT 'SR' NOT NULL,
  CREATED_AT        DATE           DEFAULT SYSDATE NOT NULL,
  UPDATED_AT        DATE           DEFAULT SYSDATE NOT NULL,
  SR_LEVEL          NUMBER(18,6)   NOT NULL,
  CONSTRAINT PK_PRICE_ACTION_SR_LEVELS_MANUALLY PRIMARY KEY (LEVEL_ID)
);

CREATE INDEX IDX_PA_SR_SYMBOL_TF ON PRICE_ACTION_SR_LEVELS_MANUALLY (SYMBOL, TF);
CREATE INDEX IDX_PA_SR_SYMBOL_TF_LEVEL ON PRICE_ACTION_SR_LEVELS_MANUALLY (SYMBOL, TF, SR_LEVEL);

PROMPT PRICE_ACTION_SR_LEVELS_MANUALLY table created.
