import type { StrategyApiScreenerConfig } from './StrategyApiScreenerPage';
import {
  MARKET_CAP_INDEX_ALIASES,
  MARKET_CAP_RANK_ALIASES,
  MARKET_CAP_VALUE_ALIASES,
} from '../../adapters/technicalMarketCap';

const ASURA_PAGE_SIZE = 25;

const strategyMarketCapColumns = [
  { key: 'sNo', label: 'S.NO', align: 'center', sticky: 'sno', sortType: 'number' },
  { key: 'symbol', label: 'SYMBOL', sticky: 'symbol', sortType: 'string', fields: ['stock', 'stockName', 'stock_name', 'STOCK'] },
  { key: 'index', label: 'INDEX', align: 'center', fields: MARKET_CAP_INDEX_ALIASES, renderAs: 'marketCapIndex', sortType: 'string' },
  { key: 'mcap', label: 'MCAP', align: 'center', fields: MARKET_CAP_VALUE_ALIASES, renderAs: 'marketCapValue', sortType: 'number' },
  { key: 'mcap_rank', label: 'MCAP_RANK', align: 'center', dataCol: 'mcapRank', fields: MARKET_CAP_RANK_ALIASES, renderAs: 'marketCapRank', sortType: 'number' },
] as const;

export const asuraConfig: StrategyApiScreenerConfig = {
  activeStrategyPage: '/app/strategy/asura',
  columns: [
    ...strategyMarketCapColumns,
    { key: 'ltcDate', label: 'LTC_DATE', align: 'center', fields: ['ltcDate', 'ltc_date', 'LTC_DATE', 'tradeDate', 'trade_date', 'TRADING_DATE', 'buyingDate', 'BUYING_DATE'], sortType: 'date' },
    { key: 'signal_score', label: 'SignalScore', align: 'right', fields: ['signalScore', 'SIGNALSCORE'] },
    { key: 'move_1d_pct', label: '1D', align: 'right', fields: ['move1dPct'] },
    { key: 'move_1w_pct', label: '1WEEK', align: 'right', fields: ['move1wPct'] },
    { key: 'move_1m_pct', label: '1MONTH', align: 'right', fields: ['move1mPct'] },
    { key: 'volume_ratio', label: 'VolumeRatio20', align: 'right', fields: ['volumeRatio20', 'volumeRatio', 'VOLUME_RATIO20'] },
    { key: 'price', label: 'Price', align: 'right' },
    { key: 'low_52w', label: '52 Week Low', align: 'right', fields: ['low52w', 'LOW52W', 'fiftyTwoWeekLow'] },
    { key: 'high_52w', label: '52 Week High', align: 'right', fields: ['high52w', 'HIGH52W', 'fiftyTwoWeekHigh'] },
    { key: 'gap', label: 'GAP', align: 'right', fields: ['gap', 'GAP', 'gapPct', 'gap_pct'], renderAs: 'gap', sortable: false, sortType: 'number' },
    { key: 'ath', label: 'ATH', align: 'right', fields: ['ath', 'ATH'], renderAs: 'ath', sortType: 'number' },
    { key: 'ema20', label: 'EMA20', align: 'right' },
    { key: 'ema50', label: 'EMA50', align: 'right' },
    { key: 'ema100', label: 'EMA100', align: 'right' },
    { key: 'ema200', label: 'EMA200', align: 'right' },
    { key: 'rsi', label: 'RSI', align: 'right' },
    { key: 'macd_hist', label: 'MACD > 0', align: 'right', fields: ['macdHist'] },
    { key: 'volume', label: 'Volume', align: 'right' },
    { key: 'atr14', label: 'ATR', align: 'right', fields: ['atr', 'ATR'] },
    { key: 'adx', label: 'ADX14', align: 'right', fields: ['adx14', 'ADX14'] },
    { key: 'support_price', label: 'Support', align: 'right', fields: ['support', 'SUPPORT'] },
    { key: 'resistance_price', label: 'Resistance', align: 'right', fields: ['resistance', 'RESISTANCE'] },
    { key: 'trend_direction', label: 'TrendDirection', fields: ['trendDirection', 'TRENDDIRECTION'] },
    { key: 'ema_stack', label: 'EMA_Stack', fields: ['emaStack', 'EMASTACK'] },
    { key: 'setup_type', label: 'SetupType', fields: ['setupType', 'SETUPTYPE'] },
    { key: 'entry_price', label: 'EntryPrice', align: 'right', fields: ['entryPrice', 'ENTRYPRICE'] },
    { key: 'stop_loss', label: 'StopLoss', align: 'right', fields: ['stopLoss', 'STOPLOSS'] },
    { key: 'target1', label: 'Target1', align: 'right' },
    { key: 'target2', label: 'Target2', align: 'right' },
  ],
  defaultSort: 'signal_score',
  description: 'React TSX migration of the Asura bullish uptrend scanner. It reuses /api/asura with the existing page, sort, timeframe, skip_sync, and conditions-only query contract.',
  enableLiveToolbar: true,
  endpoint: '/api/asura',
  extraParams: { conditions_only: 1, skip_sync: 1, include_exited: 0 },
  insertEndpoint: '/api/asura/insert',
  lastBuyingDateEndpoint: '/api/asura/last-buying-date',
  pageSize: ASURA_PAGE_SIZE,
  pollWhileRefreshing: false,
  refreshPollMaxAttempts: 60,
  queryMode: 'timeframe',
  refreshingEmptyMessage: 'Preparing latest Asura rows...',
  serverPagination: true,
  showToolbarTotal: true,
  tableVariant: 'ema',
  title: 'Asura Bullish UPTREND Scanner',
};

export const bhramhaputraConfig: StrategyApiScreenerConfig = {
  activeStrategyPage: '/app/strategy/bhramhaputra',
  columns: [
    ...strategyMarketCapColumns,
    { key: 'price', label: 'Price', align: 'right' },
    { key: 'ath', label: 'ATH', align: 'right', fields: ['ath', 'ATH'], renderAs: 'ath', sortType: 'number' },
    { key: 'gap', label: 'GAP', align: 'right', fields: ['gap', 'GAP', 'gapPct', 'gap_pct'], renderAs: 'gap', sortType: 'number' },
    { key: 'ytdPct', label: 'YTD %', align: 'right', renderAs: 'signedPercent', sortType: 'number' },
    { key: 'buyDate', label: 'Buying Date' },
    { key: 'buyPrice', label: 'Buy Price', align: 'right' },
    { key: 'stopLoss', label: 'Stop Loss', align: 'right' },
    { key: 'target1', label: 'Target1', align: 'right' },
    { key: 'target2', label: 'Target2', align: 'right' },
    { key: 'ema20', label: 'EMA20', align: 'right' },
    { key: 'emaSignal', label: 'EMA > 20' },
    { key: 'rsi14', label: 'RSI14', align: 'right' },
    { key: 'rsiSignal', label: 'RSI > 30' },
    { key: 'macdHist', label: 'MACD Hist', align: 'right' },
    { key: 'macdSignal', label: 'MACD > 0' },
    { key: 'volume', label: 'Volume', align: 'right' },
    { key: 'volumeRatio20', label: 'Vol Ratio', align: 'right' },
    { key: 'trendDirection', label: 'Trend' },
    { key: 'bullishPattern', label: 'Bullish' },
    { key: 'supportDisplay', label: 'Support', align: 'left', dataCol: 'support', fields: ['support', 'support1', 'support_1', 'S1'], renderAs: 'srLevels', sortType: 'number' },
    { key: 'resistanceDisplay', label: 'Resistance', align: 'left', dataCol: 'resistance', fields: ['resistance', 'resistance1', 'resistance_1', 'R1'], renderAs: 'srLevels', sortType: 'number' },
  ],
  defaultSort: 'symbol',
  description: 'React TSX migration of the Bhramhaputra screener. It reuses /api/bhramhaputra and keeps the tf/refresh payload contract unchanged.',
  endpoint: '/api/bhramhaputra',
  insertEndpoint: '/api/bhramhaputra/insert',
  lastBuyingDateEndpoint: '/api/bhramhaputra/last-ltc-date',
  pageSize: 25,
  queryMode: 'tf',
  showToolbarTotal: true,
  tableVariant: 'ema',
  title: 'Bhramhaputra Strategy Screener',
};

export const bhramhastraConfig: StrategyApiScreenerConfig = {
  activeStrategyPage: '/app/strategy/bhramhastra',
  columns: [
    ...strategyMarketCapColumns,
    { key: 'ltcDate', label: 'LTC_DATE' },
    { key: 'price', label: 'Price', align: 'right', fields: ['entryPrice', 'closePrice', 'close'] },
    { key: 'buyDate', label: 'Buying Date', fields: ['ltcDate', 'tradeDate', 'backtestDate'] },
    { key: 'buyPrice', label: 'Buy Price', align: 'right', fields: ['entryPrice'] },
    { key: 'stopLoss', label: 'Stop Loss', align: 'right' },
    { key: 'target1', label: 'Target1', align: 'right' },
    { key: 'target2', label: 'Target2', align: 'right' },
    { key: 'ema20', label: 'EMA20', align: 'right', fields: ['EMA20'] },
    { key: 'ema50', label: 'EMA50', align: 'right', fields: ['emaDays'] },
    { key: 'ema100', label: 'EMA100', align: 'right', fields: ['EMA100'] },
    { key: 'ema200', label: 'EMA200', align: 'right', fields: ['EMA200'] },
    { key: 'rsi14', label: 'RSI14', align: 'right', fields: ['rsi'] },
    { key: 'macdHist', label: 'MACD Hist', align: 'right', fields: ['macd'] },
    { key: 'volume', label: 'Volume', align: 'right' },
    { key: 'atr14', label: 'ATR14', align: 'right', fields: ['atr'] },
    { key: 'adx14', label: 'ADX14', align: 'right', fields: ['ADX14', 'adx', 'ADX'] },
    { key: 'trendDirection', label: 'Trend', fields: ['trend', 'TREND', 'trend_direction', 'TREND_DIRECTION'] },
    { key: 'setupType', label: 'SetupType', fields: ['setup_type', 'SETUP_TYPE', 'SETUPTYPE'] },
    { key: 'support', label: 'Support', align: 'right' },
    { key: 'resistance', label: 'Resistance', align: 'right' },
    { key: 'gap', label: 'GAP', align: 'right', fields: ['gap', 'GAP', 'gapPct', 'gap_pct'], renderAs: 'gap', sortType: 'number' },
    { key: 'ath', label: 'ATH', align: 'right', fields: ['ath', 'ATH'], renderAs: 'ath', sortType: 'number' },
  ],
  defaultSort: 'symbol',
  description: 'React TSX migration of the Bhramhastra strategy scanner. It reuses /api/bhramhastra and keeps refresh/background snapshot behavior backend-owned.',
  endpoint: '/api/bhramhastra',
  insertEndpoint: '/api/bhramhastra/insert',
  lastBuyingDateEndpoint: '/api/bhramhastra/last-ltc-date',
  pageSize: 25,
  pollWhileRefreshing: true,
  refreshPollMaxAttempts: 60,
  queryMode: 'timeframe',
  refreshingEmptyMessage: 'Preparing latest Bhramhastra rows...',
  showToolbarTotal: true,
  tableVariant: 'ema',
  title: 'Bhramhastra Strategy Screener',
};
