-- Approved canonical NSE symbol cleanup. Run validate_obsolete_nse_symbols.sql first.
-- This script is intentionally allow-listed and does not touch unrelated cross-sector membership.
SET SERVEROUTPUT ON;

DECLARE
  v_rows NUMBER := 0;
BEGIN
  SAVEPOINT before_obsolete_symbol_cleanup;

  DELETE FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV
  WHERE REGEXP_LIKE(
    UPPER(TRIM(SYMBOL)),
    '^(NSE:)?(BOSCHHCIL|MIRCELECTR|RESTAURANT|SCHLOSS|SHOPPERS|VISHALMEGA)(-(EQ|BE|SM|ST|BZ))?$'
  );
  DBMS_OUTPUT.PUT_LINE('DEV obsolete rows deleted=' || SQL%ROWCOUNT);

  DELETE FROM STOCK_EOD_HISTORY
  WHERE REGEXP_LIKE(
    UPPER(TRIM(SYMBOL)),
    '^(NSE:)?(BOSCHHCIL|MIRCELECTR|RESTAURANT|SCHLOSS|SHOPPERS|VISHALMEGA)(-(EQ|BE|SM|ST|BZ))?$'
  );
  DBMS_OUTPUT.PUT_LINE('STOCK_EOD_HISTORY obsolete rows deleted=' || SQL%ROWCOUNT);

  INSERT INTO NSE_NIFTY_CONSUMER_ELECTRONICS_STAGING (SYMBOL, SECTOR)
  SELECT 'ONIDA', 'CONSUMER_ELECTRONICS' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_NIFTY_CONSUMER_ELECTRONICS_STAGING WHERE UPPER(TRIM(SYMBOL)) = 'ONIDA');
  DELETE FROM NSE_NIFTY_CONSUMER_ELECTRONICS_STAGING WHERE UPPER(TRIM(SYMBOL)) = 'MIRCELECTR';

  INSERT INTO NSE_NIFTY_CONSUMER_SERVICES_STAGING (SYMBOL, SECTOR)
  SELECT 'SHOPERSTOP', 'CONSUMER_SERVICES' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING WHERE UPPER(TRIM(SYMBOL)) = 'SHOPERSTOP');
  INSERT INTO NSE_NIFTY_CONSUMER_SERVICES_STAGING (SYMBOL, SECTOR)
  SELECT 'VMM', 'CONSUMER_SERVICES' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING WHERE UPPER(TRIM(SYMBOL)) = 'VMM');
  DELETE FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING
  WHERE UPPER(TRIM(SYMBOL)) IN ('RESTAURANT', 'SCHLOSS', 'SHOPPERS', 'VISHALMEGA');

  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'ONIDA'
  WHERE UPPER(TRIM(SYMBOL)) = 'MIRCELECTR' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_ELECTRONICS';
  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'SHOPERSTOP'
  WHERE UPPER(TRIM(SYMBOL)) = 'SHOPPERS' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_SERVICES';
  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'VMM'
  WHERE UPPER(TRIM(SYMBOL)) = 'VISHALMEGA' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_SERVICES';
  DELETE FROM NSE_SYMBOL_SECTOR_MAP
  WHERE UPPER(TRIM(SYMBOL)) IN ('RESTAURANT', 'SCHLOSS');

  COMMIT;
END;
/
