-- Table for Bhramhaputra strategy scan results
-- Stores only symbols that meet EMA>20, Volume>Avg20, Uptrend, and (RSI>30 or MACD>0).

CREATE TABLE BHRAMHAPUTRA_SCAN (
  SYMBOL           VARCHAR2(30) NOT NULL,
  TRADE_DATE       DATE NOT NULL,
  PRICE            NUMBER(12,4),
  EMA20            NUMBER(12,4),
  EMA20_FLAG       CHAR(1),
  RSI14            NUMBER(6,2),
  RSI_FLAG         CHAR(1),
  MACD_HIST        NUMBER(12,6),
  MACD_FLAG        CHAR(1),
  VOLUME           NUMBER(20,2),
  AVG_VOLUME20     NUMBER(20,2),
  VOLUME_RATIO20   NUMBER(12,4),
  VOLUME_FLAG      CHAR(1),
  ATR14            NUMBER(12,4),
  TREND_DIRECTION  VARCHAR2(20),
  BULLISH_PATTERN  CHAR(1),
  SUPPORT_S1       NUMBER(12,4),
  SUPPORT_S2       NUMBER(12,4),
  RESISTANCE_R1    NUMBER(12,4),
  RESISTANCE_R2    NUMBER(12,4),
  HIGH_52W         NUMBER(12,4),
  LOW_52W          NUMBER(12,4),
  HIGH_1Y          NUMBER(12,4),
  HIGH_2Y          NUMBER(12,4),
  ATH              NUMBER(12,4),
  YTD_PCT          NUMBER(8,2),
  CONDITIONS_MET   CHAR(1),
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT       TIMESTAMP,
  CONSTRAINT BHRAMHAPUTRA_SCAN_PK PRIMARY KEY (SYMBOL, TRADE_DATE)
);

CREATE INDEX BHRAMHAPUTRA_SCAN_TRADE_DATE_IDX ON BHRAMHAPUTRA_SCAN (TRADE_DATE);
