-- Oracle 19c strategy-agent objects for CvingTrade25X.
-- Forward DDL only. Runtime code also auto-creates these tables if missing.
-- Validation queries:
--   SELECT COUNT(*) FROM CVING_STRATEGY_PARAMS;
--   SELECT COUNT(*) FROM CVING_STRATEGY_AGENT_RUNS;
--   SELECT COUNT(*) FROM CVING_STRATEGY_AGENT_BACKTESTS;
-- Rollback:
--   DROP TABLE CVING_STRATEGY_AGENT_BACKTESTS;
--   DROP TABLE CVING_STRATEGY_AGENT_RUNS;
--   DROP TABLE CVING_STRATEGY_PARAMS;

CREATE TABLE CVING_STRATEGY_PARAMS (
  STRATEGY_NAME      VARCHAR2(30) NOT NULL,
  PARAM_NAME         VARCHAR2(80) NOT NULL,
  PARAM_VALUE_TEXT   VARCHAR2(4000),
  PARAM_VALUE_NUMBER NUMBER(18,6),
  VALUE_TYPE         VARCHAR2(20) DEFAULT 'text' NOT NULL,
  NOTES              VARCHAR2(400),
  UPDATED_BY         VARCHAR2(64),
  UPDATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP,
  IS_ACTIVE          CHAR(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT PK_CVING_STRATEGY_PARAMS PRIMARY KEY (STRATEGY_NAME, PARAM_NAME)
);

CREATE INDEX IDX_CVING_STRATEGY_PARAMS_UPD ON CVING_STRATEGY_PARAMS (UPDATED_AT);

CREATE TABLE CVING_STRATEGY_AGENT_RUNS (
  RUN_ID                  VARCHAR2(36) PRIMARY KEY,
  STRATEGY_NAME           VARCHAR2(30) NOT NULL,
  RUN_SOURCE              VARCHAR2(20),
  RUN_AT                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  STATUS                  VARCHAR2(20) NOT NULL,
  APPLIED_FLAG            CHAR(1) DEFAULT 'N' NOT NULL,
  BASELINE_SUCCESS_RATE   NUMBER(9,4),
  CANDIDATE_SUCCESS_RATE  NUMBER(9,4),
  BASELINE_FAIL_RATE      NUMBER(9,4),
  CANDIDATE_FAIL_RATE     NUMBER(9,4),
  BASELINE_TOTAL_TRADES   NUMBER,
  CANDIDATE_TOTAL_TRADES  NUMBER,
  BASELINE_AVG_RR         NUMBER(12,6),
  CANDIDATE_AVG_RR        NUMBER(12,6),
  PARAMS_JSON             CLOB,
  NOTES                   CLOB,
  CONSTRAINT CK_CVING_STRATEGY_AGENT_RUNS_JSON CHECK (PARAMS_JSON IS JSON OR PARAMS_JSON IS NULL)
);

CREATE INDEX IDX_CVING_STRATEGY_AGENT_RUNS_STRAT ON CVING_STRATEGY_AGENT_RUNS (STRATEGY_NAME, RUN_AT DESC);

CREATE TABLE CVING_STRATEGY_AGENT_BACKTESTS (
  BACKTEST_ID      VARCHAR2(64) PRIMARY KEY,
  RUN_ID           VARCHAR2(36) NOT NULL,
  STRATEGY_NAME    VARCHAR2(30) NOT NULL,
  SOURCE_NAME      VARCHAR2(30),
  SYMBOL           VARCHAR2(50) NOT NULL,
  DIRECTION        VARCHAR2(10) NOT NULL,
  ENTRY_DATE       DATE NOT NULL,
  EXIT_DATE        DATE,
  ENTRY_PRICE      NUMBER(18,4),
  EXIT_PRICE       NUMBER(18,4),
  STOP_LOSS        NUMBER(18,4),
  TARGET1          NUMBER(18,4),
  TARGET2          NUMBER(18,4),
  TARGET1_DATE     DATE,
  TARGET2_DATE     DATE,
  EXIT_REASON      VARCHAR2(40),
  RESULT_FLAG      VARCHAR2(10),
  SUCCESS_FLAG     NUMBER(1) DEFAULT 0 NOT NULL,
  FAIL_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
  TRADING_DAYS     NUMBER,
  DAYS_TO_T1       NUMBER,
  DAYS_TO_T2       NUMBER,
  RETURN_PCT       NUMBER(12,4),
  RETURN_RR        NUMBER(12,6),
  WHY_TRADE        VARCHAR2(400),
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_CVING_STRATEGY_AGENT_BT_RUN ON CVING_STRATEGY_AGENT_BACKTESTS (RUN_ID, ENTRY_DATE DESC);
CREATE INDEX IDX_CVING_STRATEGY_AGENT_BT_ST ON CVING_STRATEGY_AGENT_BACKTESTS (STRATEGY_NAME, ENTRY_DATE DESC);
