-- Check if table exists
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NSE_NIFTY_PESTICIDES_AGROCHEMICALS_STAGING';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE NSE_NIFTY_PESTICIDES_AGROCHEMICALS_STAGING (
        SYMBOL VARCHAR2(50) NOT NULL,
        COMPANY_NAME VARCHAR2(200),
        ISIN VARCHAR2(20),
        CREATED_DATE DATE DEFAULT SYSDATE,
        CONSTRAINT PK_NSE_NIFTY_PESTICIDES_AGRO_STG PRIMARY KEY (SYMBOL)
      )
    ';
    DBMS_OUTPUT.PUT_LINE('Table NSE_NIFTY_PESTICIDES_AGROCHEMICALS_STAGING created successfully.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Table NSE_NIFTY_PESTICIDES_AGROCHEMICALS_STAGING already exists.');
  END IF;
END;
/
