PROMPT Creating or replacing V_NSE_NIFTY_NEXT50_MIDCAP_OHLCV ...

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_NSE_NIFTY_NEXT50_MIDCAP_OHLCV"
("SYMBOL", "OPEN", "HIGH", "LOW", "PREVIOUS_CLOSE", "VOLUME", "TRADING_DATE") AS
  SELECT
    r."SYMBOL",
    r."OPEN",
    r."HIGH",
    r."LOW",
    r."PREVIOUS_CLOSE",
    r."VOLUME",
    r."TRADING_DATE"
  FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV r
  INNER JOIN NIFTY_NEXT50_MIDCAP n
    ON r.SYMBOL = n.SYMBOL;

PROMPT Validation queries ...
SELECT COUNT(*) AS next50_symbol_count FROM NIFTY_NEXT50_MIDCAP;
SELECT MAX(TRADING_DATE) AS latest_trade_date FROM V_NSE_NIFTY_NEXT50_MIDCAP_OHLCV;
