PROMPT Creating staging tables for Restaurants, Hospitality Hotels & Resorts, Tourism & Travel Sectors

SET DEFINE OFF;

DECLARE
  v_exists NUMBER;
BEGIN
  -- 1. Restaurants
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'NSE_NIFTY_RESTAURANTS_STAGING';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE NSE_NIFTY_RESTAURANTS_STAGING
      (
        SYMBOL VARCHAR2(64 BYTE) NOT NULL,
        COMPANY_NAME VARCHAR2(255 BYTE),
        INDUSTRY VARCHAR2(128 BYTE),
        SECTOR VARCHAR2(128 BYTE),
        ACTIVE_FLAG VARCHAR2(1 BYTE) DEFAULT ''Y'',
        CREATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        UPDATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        CONSTRAINT PK_NIFTY_RESTAURANTS_STG PRIMARY KEY (SYMBOL)
      )
    ';
    DBMS_OUTPUT.PUT_LINE('Created table NSE_NIFTY_RESTAURANTS_STAGING');
  END IF;

  -- 2. Hospitality Hotels & Resorts
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING
      (
        SYMBOL VARCHAR2(64 BYTE) NOT NULL,
        COMPANY_NAME VARCHAR2(255 BYTE),
        INDUSTRY VARCHAR2(128 BYTE),
        SECTOR VARCHAR2(128 BYTE),
        ACTIVE_FLAG VARCHAR2(1 BYTE) DEFAULT ''Y'',
        CREATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        UPDATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        CONSTRAINT PK_NIFTY_HOSPITALITY_STG PRIMARY KEY (SYMBOL)
      )
    ';
    DBMS_OUTPUT.PUT_LINE('Created table NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING');
  END IF;

  -- 3. Tourism & Travel
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'NSE_NIFTY_TOURISM_TRAVEL_STAGING';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE NSE_NIFTY_TOURISM_TRAVEL_STAGING
      (
        SYMBOL VARCHAR2(64 BYTE) NOT NULL,
        COMPANY_NAME VARCHAR2(255 BYTE),
        INDUSTRY VARCHAR2(128 BYTE),
        SECTOR VARCHAR2(128 BYTE),
        ACTIVE_FLAG VARCHAR2(1 BYTE) DEFAULT ''Y'',
        CREATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        UPDATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
        CONSTRAINT PK_NIFTY_TOURISM_TRAVEL_STG PRIMARY KEY (SYMBOL)
      )
    ';
    DBMS_OUTPUT.PUT_LINE('Created table NSE_NIFTY_TOURISM_TRAVEL_STAGING');
  END IF;

END;
/

PROMPT Registering sectors in NSE_SECTOR_MASTER
MERGE INTO NSE_SECTOR_MASTER tgt
USING (
  SELECT 'RESTAURANTS' AS SECTOR_CODE, 'Restaurants' AS SECTOR_NAME, 'NIFTY_RESTAURANTS' AS INDEX_CODE, 60 AS DISPLAY_ORDER FROM DUAL UNION ALL
  SELECT 'HOSPITALITY_HOTELS_RESORTS' AS SECTOR_CODE, 'Hospitality Hotels & Resorts' AS SECTOR_NAME, 'NIFTY_HOSPITALITY_HOTELS_RESORTS' AS INDEX_CODE, 60 AS DISPLAY_ORDER FROM DUAL UNION ALL
  SELECT 'TOURISM_TRAVEL' AS SECTOR_CODE, 'Tourism & Travel' AS SECTOR_NAME, 'NIFTY_TOURISM_TRAVEL' AS INDEX_CODE, 60 AS DISPLAY_ORDER FROM DUAL
) src
ON (tgt.SECTOR_CODE = src.SECTOR_CODE)
WHEN MATCHED THEN UPDATE SET
  tgt.SECTOR_NAME = src.SECTOR_NAME,
  tgt.INDEX_CODE = src.INDEX_CODE,
  tgt.DISPLAY_ORDER = src.DISPLAY_ORDER
WHEN NOT MATCHED THEN INSERT (SECTOR_CODE, SECTOR_NAME, INDEX_CODE, DISPLAY_ORDER)
VALUES (src.SECTOR_CODE, src.SECTOR_NAME, src.INDEX_CODE, src.DISPLAY_ORDER);

COMMIT;
EXIT;
