-- Roll back FYERS holdings import tables.
-- Run this only if you intentionally want to remove the FYERS holdings feature tables.

DROP INDEX FYERS_HOLDINGS_AUDIT_IDX1;
DROP TABLE FYERS_HOLDINGS_AUDIT;

DROP INDEX FYERS_HOLDINGS_CURR_IDX1;
DROP INDEX FYERS_HOLDINGS_CURR_UK1;
DROP TABLE FYERS_HOLDINGS_CURRENT;

DROP TABLE FYERS_HOLDINGS_IMPORTS;
