PROMPT Move NSE FFMC objects into CVING application tablespaces.

ALTER TABLE CVING_NSE_FFMC_HIST MOVE TABLESPACE CVING_DATA UPDATE INDEXES;
ALTER INDEX IDX_CVING_NSE_FFMC_TRDDATE REBUILD TABLESPACE CVING_INDEX;
ALTER INDEX IDX_CVING_NSE_FFMC_SYMDATE REBUILD TABLESPACE CVING_INDEX;

ALTER TABLE CVING_NSE_FFMC_PIPELINE_RUNS MOVE TABLESPACE CVING_DATA;
ALTER INDEX IDX_CVING_NSE_FFMC_RUNS_TRDRUN REBUILD TABLESPACE CVING_INDEX;
ALTER INDEX IDX_CVING_NSE_FFMC_RUNS_START REBUILD TABLESPACE CVING_INDEX;

PROMPT Validation queries:
SELECT table_name, tablespace_name
FROM user_tables
WHERE table_name IN ('CVING_NSE_FFMC_HIST', 'CVING_NSE_FFMC_PIPELINE_RUNS');

SELECT index_name, tablespace_name
FROM user_indexes
WHERE table_name IN ('CVING_NSE_FFMC_HIST', 'CVING_NSE_FFMC_PIPELINE_RUNS')
ORDER BY table_name, index_name;
