-- Move active page-backed application tables from SYSTEM to CVING_APP.
-- This resolves ORA-01653 for Strategy Agent and NSE Market Cap workflows.

ALTER TABLE SYSTEM.CVING_STRATEGY_PARAMS MOVE TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.PK_VING_STRATEGY_PARAMS REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_NG_STRATEGY_PARAMS_UPD REBUILD TABLESPACE CVING_APP;

ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE TABLESPACE CVING_APP;
ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE LOB (PARAMS_JSON) STORE AS (TABLESPACE CVING_APP);
ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE LOB (NOTES) STORE AS (TABLESPACE CVING_APP);
ALTER INDEX SYSTEM.SYS_C0010194 REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_TRATEGY_AGENT_RUNS_STRAT REBUILD TABLESPACE CVING_APP;

ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_BACKTESTS MOVE TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.SYS_C0010203 REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_GY_AGENT_BACKTESTS_RUN REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_GY_AGENT_BACKTESTS_STRAT REBUILD TABLESPACE CVING_APP;

ALTER TABLE SYSTEM.CVING_NSE_MARKET_CAP_HIST MOVE TABLESPACE CVING_APP;
ALTER TABLE SYSTEM.CVING_NSE_MARKET_CAP_HIST MOVE LOB (RESPONSE_PAYLOAD) STORE AS (TABLESPACE CVING_APP);
ALTER INDEX SYSTEM.SYS_C0010214 REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.UQ__NSE_MARKET_CAP_HIST REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_SE_MARKET_CAP_HIST_SYMDATE REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_SE_MARKET_CAP_HIST_TRDSRC REBUILD TABLESPACE CVING_APP;

ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE TABLESPACE CVING_APP;
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (REQUEST_JSON) STORE AS (TABLESPACE CVING_APP);
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (METRICS_JSON) STORE AS (TABLESPACE CVING_APP);
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (LOGS_CLOB) STORE AS (TABLESPACE CVING_APP);
ALTER INDEX SYSTEM.SYS_C0010223 REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_MCAP_PIPELINE_RUNS_START REBUILD TABLESPACE CVING_APP;
ALTER INDEX SYSTEM.IDX_MCAP_PIPELINE_RUNS_TRDRUN REBUILD TABLESPACE CVING_APP;

