SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT Removing approved sector memberships for CIGNITITEC and RELINFRA ...

DELETE FROM NSE_NIFTY_IT_STAGING
WHERE UPPER(TRIM(SYMBOL)) = 'CIGNITITEC';

DELETE FROM NSE_NIFTY_INFRASTRUCTURE_STAGING
WHERE UPPER(TRIM(SYMBOL)) = 'RELINFRA';

DELETE FROM NSE_NIFTY_UTILITIES_STAGING
WHERE UPPER(TRIM(SYMBOL)) = 'RELINFRA';

DELETE FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN ('CIGNITITEC', 'RELINFRA');

COMMIT;

PROMPT Sector memberships removed. Run validate_cignititec_relinfra_sector_removal.sql.
