PROMPT Rollback helper for Media symbol backfill.
PROMPT Run the validation query first and use this only for rows newly inserted by the paired backfill.
SET DEFINE OFF;

PROMPT Pre-rollback validation:
SELECT
  UPPER(TRIM(SYMBOL)) AS SYMBOL,
  SECTOR
FROM NSE_NIFTY_MEDIA_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
  'ZEEL',
  'NETWORK18',
  'SAREGAMA',
  'TIPSMUSIC',
  'NAZARA',
  'AQYLON',
  'SUNTV',
  'PFOCUS',
  'PVRINOX',
  'HATHWAY',
  'NDTV',
  'ZEEMEDIA',
  'DEN',
  'DISHTV',
  'SIGNPOST',
  'BALAJITELE',
  'TVTODAY',
  'ENIL',
  'ONMOBILE',
  'RKSWAMY',
  'GTPL',
  'DBCORP'
)
ORDER BY 1;

PROMPT Commented rollback statements by default for safety:
PROMPT DELETE FROM NSE_SYMBOL_SECTOR_MAP
PROMPT WHERE SECTOR_CODE = 'MEDIA'
PROMPT   AND UPPER(TRIM(SYMBOL)) IN (...)
PROMPT   AND UPPER(TRIM(SYMBOL)) NOT IN (SELECT UPPER(TRIM(SYMBOL)) FROM <pre_run_export>);
PROMPT
PROMPT DELETE FROM NSE_NIFTY_MEDIA_STAGING
PROMPT WHERE UPPER(TRIM(SECTOR)) = 'MEDIA ENTERTAINMENT & PUBLICATION'
PROMPT   AND UPPER(TRIM(SYMBOL)) IN (...)
PROMPT   AND UPPER(TRIM(SYMBOL)) NOT IN (SELECT UPPER(TRIM(SYMBOL)) FROM <pre_run_export>);
