PROMPT Dropping FACT_OHLCV sync procedures.

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_SYNC_FACT_OHLCV_FROM_DEV';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_MERGE_FACT_OHLCV_FROM_DEV';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_SYNC_DIM_SYMBOLS_FROM_DEV';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/
