PROMPT Rolling back source-pack unique sector staging tables and master codes
SET DEFINE OFF;

DECLARE
    l_sector_codes SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
        'HOUSEHOLD_PERSONAL_PRODUCTS',
        'COMMODITIES_TRADING',
        'DEFENCE_AEROSPACE_DEFENSE',
        'DIVERSIFIED',
        'BIOTECHNOLOGY',
        'MEDICAL_EQUIPMENT_SUPPLIES',
        'IT_ENABLED_SERVICES',
        'SOFTWARE_PRODUCTS_SERVICES',
        'MEDIA_ENTERTAINMENT',
        'PRINT_MEDIA_PUBLISHING',
        'METALS_MINING',
        'IRON_STEEL',
        'MINING',
        'NON_FERROUS_METALS',
        'LPG_CNG_PNG_LNG_SUPPLIER',
        'LUBRICANTS',
        'OIL_EQUIPMENT_SERVICES',
        'PETROLEUM_PRODUCTS_REFINERIES',
        'PAPER_PACKAGING',
        'WASTE_WATER_MANAGEMENT',
        'FOOTWEAR',
        'GEMS',
        'JEWELLERY_WATCHES',
        'LEATHER_LEATHER_PRODUCTS',
        'TEXTILES_APPARELS'
    );
    l_table_names SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
        'NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING',
        'NSE_NIFTY_COMMODITIES_TRADING_STAGING',
        'NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING',
        'NSE_NIFTY_DIVERSIFIED_STAGING',
        'NSE_NIFTY_BIOTECHNOLOGY_STAGING',
        'NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING',
        'NSE_NIFTY_IT_ENABLED_SERVICES_STAGING',
        'NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING',
        'NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING',
        'NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING',
        'NSE_NIFTY_METALS_MINING_STAGING',
        'NSE_NIFTY_IRON_STEEL_STAGING',
        'NSE_NIFTY_MINING_STAGING',
        'NSE_NIFTY_NON_FERROUS_METALS_STAGING',
        'NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING',
        'NSE_NIFTY_LUBRICANTS_STAGING',
        'NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING',
        'NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING',
        'NSE_NIFTY_PAPER_PACKAGING_STAGING',
        'NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING',
        'NSE_NIFTY_FOOTWEAR_STAGING',
        'NSE_NIFTY_GEMS_STAGING',
        'NSE_NIFTY_JEWELLERY_WATCHES_STAGING',
        'NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING',
        'NSE_NIFTY_TEXTILES_APPARELS_STAGING'
    );
    v_exists NUMBER := 0;
BEGIN
    FOR i IN 1 .. l_sector_codes.COUNT LOOP
        DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = l_sector_codes(i);
        DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = l_sector_codes(i);

        SELECT COUNT(*)
        INTO v_exists
        FROM user_tables
        WHERE table_name = l_table_names(i);

        IF v_exists > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE ' || l_table_names(i) || ' PURGE';
        END IF;
    END LOOP;

    COMMIT;
END;
/

PROMPT Source-pack unique sector rollback complete.
