-- Restores sector-reference identities only. Historical rows are restored from the
-- pre-change export if validation ever finds deletions (the 2026-07-20 pre-count was zero).
SET SERVEROUTPUT ON;
BEGIN
  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'MIRCELECTR'
  WHERE UPPER(TRIM(SYMBOL)) = 'ONIDA' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_ELECTRONICS';
  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'SHOPPERS'
  WHERE UPPER(TRIM(SYMBOL)) = 'SHOPERSTOP' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_SERVICES';
  UPDATE NSE_SYMBOL_SECTOR_MAP SET SYMBOL = 'VISHALMEGA'
  WHERE UPPER(TRIM(SYMBOL)) = 'VMM' AND UPPER(TRIM(SECTOR_CODE)) = 'CONSUMER_SERVICES';

  INSERT INTO NSE_SYMBOL_SECTOR_MAP (SYMBOL, SECTOR_CODE, IS_ACTIVE)
  SELECT 'RESTAURANT', 'CONSUMER_SERVICES', 'Y' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_SYMBOL_SECTOR_MAP WHERE SYMBOL='RESTAURANT' AND SECTOR_CODE='CONSUMER_SERVICES');
  INSERT INTO NSE_SYMBOL_SECTOR_MAP (SYMBOL, SECTOR_CODE, IS_ACTIVE)
  SELECT 'SCHLOSS', 'CONSUMER_SERVICES', 'Y' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_SYMBOL_SECTOR_MAP WHERE SYMBOL='SCHLOSS' AND SECTOR_CODE='CONSUMER_SERVICES');

  UPDATE NSE_NIFTY_CONSUMER_ELECTRONICS_STAGING SET SYMBOL='MIRCELECTR' WHERE SYMBOL='ONIDA';
  UPDATE NSE_NIFTY_CONSUMER_SERVICES_STAGING SET SYMBOL='SHOPPERS' WHERE SYMBOL='SHOPERSTOP';
  UPDATE NSE_NIFTY_CONSUMER_SERVICES_STAGING SET SYMBOL='VISHALMEGA' WHERE SYMBOL='VMM';
  INSERT INTO NSE_NIFTY_CONSUMER_SERVICES_STAGING (SYMBOL, SECTOR) SELECT 'RESTAURANT', 'CONSUMER_SERVICES' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING WHERE SYMBOL='RESTAURANT');
  INSERT INTO NSE_NIFTY_CONSUMER_SERVICES_STAGING (SYMBOL, SECTOR) SELECT 'SCHLOSS', 'CONSUMER_SERVICES' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING WHERE SYMBOL='SCHLOSS');
  COMMIT;
END;
/
