PROMPT Rolling back Consumer Electronics sector staging table and master code
SET DEFINE OFF;

-- Drop table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_CONSUMER_ELECTRONICS_STAGING';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Delete master data
DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = 'CONSUMER_ELECTRONICS';
DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = 'CONSUMER_ELECTRONICS';
COMMIT;

PROMPT Rollback complete.
