PROMPT Rollback Hospitality Hotels & Resorts Sector Table and References

SET DEFINE OFF;

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING';
  IF v_exists > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING';
    DBMS_OUTPUT.PUT_LINE('Dropped table NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING');
  END IF;
END;
/

DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = 'HOSPITALITY_HOTELS_RESORTS';
DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = 'HOSPITALITY_HOTELS_RESORTS';

COMMIT;
EXIT;
