-- Roll back application table placement from CVING_APP to SYSTEM.
-- Run only if SYSTEM has sufficient free space. This is not recommended on the current database.

ALTER TABLE SYSTEM.CVING_STRATEGY_PARAMS MOVE TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.PK_VING_STRATEGY_PARAMS REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_NG_STRATEGY_PARAMS_UPD REBUILD TABLESPACE SYSTEM;

ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE TABLESPACE SYSTEM;
ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE LOB (PARAMS_JSON) STORE AS (TABLESPACE SYSTEM);
ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_RUNS MOVE LOB (NOTES) STORE AS (TABLESPACE SYSTEM);
ALTER INDEX SYSTEM.SYS_C0010194 REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_TRATEGY_AGENT_RUNS_STRAT REBUILD TABLESPACE SYSTEM;

ALTER TABLE SYSTEM.CVING_STRATEGY_AGENT_BACKTESTS MOVE TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.SYS_C0010203 REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_GY_AGENT_BACKTESTS_RUN REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_GY_AGENT_BACKTESTS_STRAT REBUILD TABLESPACE SYSTEM;

ALTER TABLE SYSTEM.CVING_NSE_MARKET_CAP_HIST MOVE TABLESPACE SYSTEM;
ALTER TABLE SYSTEM.CVING_NSE_MARKET_CAP_HIST MOVE LOB (RESPONSE_PAYLOAD) STORE AS (TABLESPACE SYSTEM);
ALTER INDEX SYSTEM.SYS_C0010214 REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.UQ__NSE_MARKET_CAP_HIST REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_SE_MARKET_CAP_HIST_SYMDATE REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_SE_MARKET_CAP_HIST_TRDSRC REBUILD TABLESPACE SYSTEM;

ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE TABLESPACE SYSTEM;
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (REQUEST_JSON) STORE AS (TABLESPACE SYSTEM);
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (METRICS_JSON) STORE AS (TABLESPACE SYSTEM);
ALTER TABLE SYSTEM.CVING_NSE_MCAP_PIPELINE_RUNS MOVE LOB (LOGS_CLOB) STORE AS (TABLESPACE SYSTEM);
ALTER INDEX SYSTEM.SYS_C0010223 REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_MCAP_PIPELINE_RUNS_START REBUILD TABLESPACE SYSTEM;
ALTER INDEX SYSTEM.IDX_MCAP_PIPELINE_RUNS_TRDRUN REBUILD TABLESPACE SYSTEM;

