PROMPT Rolling back Realty Real Estate sector tables

DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = 'REALTY_REAL_ESTATE';
DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = 'REALTY_REAL_ESTATE';

-- Keep drop commented to prevent destructive execution
-- DROP TABLE NSE_NIFTY_REALTY_REAL_ESTATE_STAGING;

COMMIT;
