SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

MERGE INTO NSE_NIFTY_IT_STAGING tgt
USING (SELECT 'CIGNITITEC' AS SYMBOL, 'IT' AS SECTOR FROM DUAL) src
ON (UPPER(TRIM(tgt.SYMBOL)) = src.SYMBOL)
WHEN NOT MATCHED THEN INSERT (SYMBOL, SECTOR) VALUES (src.SYMBOL, src.SECTOR);

MERGE INTO NSE_NIFTY_INFRASTRUCTURE_STAGING tgt
USING (SELECT 'RELINFRA' AS SYMBOL, 'Infrastructure' AS SECTOR FROM DUAL) src
ON (UPPER(TRIM(tgt.SYMBOL)) = src.SYMBOL)
WHEN NOT MATCHED THEN INSERT (SYMBOL, SECTOR) VALUES (src.SYMBOL, src.SECTOR);

MERGE INTO NSE_NIFTY_UTILITIES_STAGING tgt
USING (SELECT 'RELINFRA' AS SYMBOL, 'UTILITIES' AS SECTOR FROM DUAL) src
ON (UPPER(TRIM(tgt.SYMBOL)) = src.SYMBOL)
WHEN NOT MATCHED THEN INSERT (SYMBOL, SECTOR) VALUES (src.SYMBOL, src.SECTOR);

MERGE INTO NSE_SYMBOL_SECTOR_MAP tgt
USING (
  SELECT 'CIGNITITEC' AS SYMBOL, 'IT' AS SECTOR_CODE FROM DUAL
  UNION ALL
  SELECT 'RELINFRA', 'INFRASTRUCTURE' FROM DUAL
) src
ON (
  UPPER(TRIM(tgt.SYMBOL)) = src.SYMBOL
  AND UPPER(TRIM(tgt.SECTOR_CODE)) = src.SECTOR_CODE
)
WHEN MATCHED THEN UPDATE SET tgt.IS_ACTIVE = 'Y', tgt.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (SYMBOL, SECTOR_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
  VALUES (src.SYMBOL, src.SECTOR_CODE, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;

PROMPT Sector memberships restored. Refresh sector materialized views and caches.
