-- Rollback for FYERS single-stock tracking tables.
-- Run only after confirming no dependent objects require these tables.

DROP INDEX IDX_FYERS_SUCCESS_SYMBOLS_02;
DROP INDEX IDX_FYERS_SUCCESS_SYMBOLS_01;
DROP TABLE FYERS_SUCCESS_SYMBOLS;

DROP INDEX IDX_FYERS_REUSE_SYMBOLS_03;
DROP INDEX IDX_FYERS_REUSE_SYMBOLS_02;
DROP INDEX IDX_FYERS_REUSE_SYMBOLS_01;
DROP TABLE FYERS_REUSE_SYMBOLS;
