PROMPT Rollback Tourism & Travel Sector Table and References

SET DEFINE OFF;

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'NSE_NIFTY_TOURISM_TRAVEL_STAGING';
  IF v_exists > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_TOURISM_TRAVEL_STAGING';
    DBMS_OUTPUT.PUT_LINE('Dropped table NSE_NIFTY_TOURISM_TRAVEL_STAGING');
  END IF;
END;
/

DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = 'TOURISM_TRAVEL';
DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = 'TOURISM_TRAVEL';

COMMIT;
EXIT;
