PROMPT Rolling back Auto Mobile rename and Auto Ancillaries sector staging table changes
SET DEFINE OFF;

MERGE INTO NSE_NIFTY_AUTO_STAGING tgt
USING (
    SELECT 'ACGL' AS symbol, 'Auto' AS sector FROM dual UNION ALL
    SELECT 'ALICON', 'Auto' FROM dual UNION ALL
    SELECT 'APOLLOTYRE', 'Auto' FROM dual UNION ALL
    SELECT 'ARE&M', 'Auto' FROM dual UNION ALL
    SELECT 'ASAHIINDIA', 'Auto' FROM dual UNION ALL
    SELECT 'ASAL', 'Auto' FROM dual UNION ALL
    SELECT 'ASKAUTOLTD', 'Auto' FROM dual UNION ALL
    SELECT 'AUTOAXLES', 'Auto' FROM dual UNION ALL
    SELECT 'BALKRISIND', 'Auto' FROM dual UNION ALL
    SELECT 'BANCOINDIA', 'Auto' FROM dual UNION ALL
    SELECT 'BHARATFORG', 'Auto' FROM dual UNION ALL
    SELECT 'BOSCHLTD', 'Auto' FROM dual UNION ALL
    SELECT 'CEATLTD', 'Auto' FROM dual UNION ALL
    SELECT 'CIEINDIA', 'Auto' FROM dual UNION ALL
    SELECT 'CRAFTSMAN', 'Auto' FROM dual UNION ALL
    SELECT 'ENDURANCE', 'Auto' FROM dual UNION ALL
    SELECT 'EXIDEIND', 'Auto' FROM dual UNION ALL
    SELECT 'FIEMIND', 'Auto' FROM dual UNION ALL
    SELECT 'GABRIEL', 'Auto' FROM dual UNION ALL
    SELECT 'GNA', 'Auto' FROM dual UNION ALL
    SELECT 'HBLENGINE', 'Auto' FROM dual UNION ALL
    SELECT 'JAMNAAUTO', 'Auto' FROM dual UNION ALL
    SELECT 'JBMA', 'Auto' FROM dual UNION ALL
    SELECT 'JKTYRE', 'Auto' FROM dual UNION ALL
    SELECT 'JTEKTINDIA', 'Auto' FROM dual
) src
ON (UPPER(TRIM(tgt.SYMBOL)) = src.symbol)
WHEN MATCHED THEN UPDATE SET
    tgt.SECTOR = src.sector
WHERE NVL(UPPER(TRIM(tgt.SECTOR)), '~') <> UPPER(src.sector)
WHEN NOT MATCHED THEN
    INSERT (SYMBOL, SECTOR)
    VALUES (src.symbol, src.sector);

UPDATE NSE_SYMBOL_SECTOR_MAP
SET SECTOR_CODE = 'AUTO'
WHERE UPPER(TRIM(SYMBOL)) IN (
    'ACGL', 'ALICON', 'APOLLOTYRE', 'ARE&M', 'ASAHIINDIA', 'ASAL', 'ASKAUTOLTD', 'AUTOAXLES',
    'BALKRISIND', 'BANCOINDIA', 'BHARATFORG', 'BOSCHLTD', 'CEATLTD', 'CIEINDIA', 'CRAFTSMAN',
    'ENDURANCE', 'EXIDEIND', 'FIEMIND', 'GABRIEL', 'GNA', 'HBLENGINE', 'JAMNAAUTO', 'JBMA',
    'JKTYRE', 'JTEKTINDIA'
)
  AND UPPER(TRIM(SECTOR_CODE)) = 'AUTO_ANCILLARIES';

DELETE FROM NSE_NIFTY_AUTO_ANCILLARIES_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
    'ACGL', 'ALICON', 'APOLLOTYRE', 'ARE&M', 'ASAHIINDIA', 'ASAL', 'ASKAUTOLTD', 'AUTOAXLES',
    'BALKRISIND', 'BANCOINDIA', 'BHARATFORG', 'BOSCHLTD', 'CEATLTD', 'CIEINDIA', 'CRAFTSMAN',
    'ENDURANCE', 'EXIDEIND', 'FIEMIND', 'GABRIEL', 'GNA', 'HBLENGINE', 'JAMNAAUTO', 'JBMA',
    'JKTYRE', 'JTEKTINDIA'
);

DELETE FROM NSE_SECTOR_MASTER
WHERE SECTOR_CODE = 'AUTO_ANCILLARIES';

UPDATE NSE_SECTOR_MASTER
SET SECTOR_NAME = 'Auto',
    INDEX_CODE = 'NIFTY_AUTO'
WHERE SECTOR_CODE = 'AUTO';

COMMIT;
