PROMPT Rolling back explicit Pharma symbol backfill entries for staging and sector-map tables.
SET DEFINE OFF;

DELETE FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN (
  'SENORES',
  'IOLCP',
  'ORCHPHARMA',
  'SMSPHARMA',
  'BLISSGVS',
  'SOLARA',
  'TATVA',
  'LINCOLN',
  'JAGSNPHARM'
)
AND UPPER(TRIM(SECTOR_CODE)) = 'PHARMA';

DELETE FROM NSE_NIFTY_PHARMA_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
  'SENORES',
  'IOLCP',
  'ORCHPHARMA',
  'SMSPHARMA',
  'BLISSGVS',
  'SOLARA',
  'TATVA',
  'LINCOLN',
  'JAGSNPHARM'
);

COMMIT;

PROMPT Validation after rollback:
SELECT COUNT(*) AS REMAINING_ROWS
FROM NSE_NIFTY_PHARMA_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
  'SENORES',
  'IOLCP',
  'ORCHPHARMA',
  'SMSPHARMA',
  'BLISSGVS',
  'SOLARA',
  'TATVA',
  'LINCOLN',
  'JAGSNPHARM'
);
