PROMPT Rolling back Auto Components & Equipments sector tables

SET DEFINE OFF;

DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING';
    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING CASCADE CONSTRAINTS';
    END IF;
END;
/

DELETE FROM NSE_SECTOR_MASTER WHERE sector_code = 'AUTO_COMPONENTS_EQUIPMENTS';
DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE sector_code = 'AUTO_COMPONENTS_EQUIPMENTS';

COMMIT;

PROMPT Rollback complete.
