PROMPT Dropping sector reference sync procedures and alias-safe views.

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_SYNC_SECTOR_REFERENCE_DATA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_SYNC_NSE_SYMBOL_SECTOR_MAP_FROM_STAGING';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_SYNC_DIM_SYMBOLS_CAP_SEG_FROM_INDICES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_NSE_CANONICAL_SECTOR_STAGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_SYMBOL_CAP_BUCKET';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
