PROMPT Rolling back Alcohol Breweries sector staging table and reference mappings
SET DEFINE OFF;

DELETE FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN (
    'ABDL', 'ALCODIS', 'ASALCBR', 'BCLIND', 'COMFINTE', 'GLOBUSSPR', 'GMBREW', 'IFBAGRO', 'INDIAGLYCO',
    'JAGAJITIND', 'PICCADIL', 'RADICO', 'RKDL', 'SDBL', 'SULA', 'TI', 'UBL', 'UNITDSPR'
)
  AND UPPER(TRIM(SECTOR_CODE)) = 'ALCOHOL_BREWERIES';

DELETE FROM NSE_NIFTY_ALCOHOL_BREWERIES_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
    'ABDL', 'ALCODIS', 'ASALCBR', 'BCLIND', 'COMFINTE', 'GLOBUSSPR', 'GMBREW', 'IFBAGRO', 'INDIAGLYCO',
    'JAGAJITIND', 'PICCADIL', 'RADICO', 'RKDL', 'SDBL', 'SULA', 'TI', 'UBL', 'UNITDSPR'
);

DELETE FROM NSE_SECTOR_MASTER
WHERE SECTOR_CODE = 'ALCOHOL_BREWERIES';

COMMIT;

DECLARE
    l_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM user_indexes
     WHERE index_name = 'UK_NIFTY_ALCOBREW_SYM';

    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UK_NIFTY_ALCOBREW_SYM';
    END IF;

    SELECT COUNT(*)
      INTO l_count
      FROM user_tables
     WHERE table_name = 'NSE_NIFTY_ALCOHOL_BREWERIES_STAGING';

    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_ALCOHOL_BREWERIES_STAGING PURGE';
    END IF;
END;
/

PROMPT Alcohol Breweries rollback completed.
