PROMPT Rolling back Electronics and Services Consumer Durables sector staging table and master code
SET DEFINE OFF;

-- Drop table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NSE_NIFTY_ELECTRONICS_SERVICES_CONSUMER_DURABLES_STAGING';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Delete master data
DELETE FROM NSE_SYMBOL_SECTOR_MAP WHERE SECTOR_CODE = 'ELECTRONICS_SERVICES_CONSUMER_DURABLES';
DELETE FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE = 'ELECTRONICS_SERVICES_CONSUMER_DURABLES';
COMMIT;

PROMPT Rollback complete.
