-- Trend Indicator freshness SQL playbook (Oracle 19c)
-- Replace placeholders before execution.

-- 1) Source-of-truth latest date
SELECT TO_CHAR(MAX(LTC_DATE), 'YYYY-MM-DD') AS LTC_DATE
FROM <SOURCE_TABLE_OR_VIEW>
WHERE LTC_DATE IS NOT NULL;

-- If the source uses TRADING_DATE instead of LTC_DATE:
SELECT TO_CHAR(MAX(TRADING_DATE), 'YYYY-MM-DD') AS LTC_DATE
FROM <SOURCE_TABLE_OR_VIEW>
WHERE TRADING_DATE IS NOT NULL;

-- 2) Index recommendation for low-latency MAX date lookup
CREATE INDEX IDX_<TABLE_NAME>_LTC_DATE ON <TABLE_NAME>(LTC_DATE);

-- If the date column is TRADING_DATE:
CREATE INDEX IDX_<TABLE_NAME>_TRADING_DATE ON <TABLE_NAME>(TRADING_DATE);

-- 3) Materialized view freshness checks
SELECT MVIEW_NAME, STALENESS, LAST_REFRESH_TYPE, LAST_REFRESH_DATE
FROM USER_MVIEWS
WHERE MVIEW_NAME = UPPER('<MV_NAME>');

-- Manual refresh (choose FAST/COMPLETE based on MV design):
BEGIN
  DBMS_MVIEW.REFRESH(UPPER('<MV_NAME>'), METHOD => 'F');
END;
/

-- 4) Optional metadata table for O(1) latest date reads
CREATE TABLE TREND_META (
  ID NUMBER(1) CONSTRAINT PK_TREND_META PRIMARY KEY,
  LATEST_LTC_DATE DATE NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

MERGE INTO TREND_META t
USING (
  SELECT 1 AS ID, MAX(LTC_DATE) AS LATEST_LTC_DATE
  FROM <SOURCE_TABLE_OR_VIEW>
) s
ON (t.ID = s.ID)
WHEN MATCHED THEN
  UPDATE SET t.LATEST_LTC_DATE = s.LATEST_LTC_DATE, t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, LATEST_LTC_DATE, UPDATED_AT)
  VALUES (s.ID, s.LATEST_LTC_DATE, SYSTIMESTAMP);

COMMIT;
