PROMPT Validating Cement, Construction and Infrastructure sector tables
SET DEFINE OFF;

PROMPT [1] Staging tables presence
SELECT table_name FROM user_tables 
WHERE table_name IN (
    'NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING',
    'NSE_NIFTY_CONSTRUCTION_STAGING',
    'NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING',
    'NSE_NIFTY_INFRASTRUCTURE_STAGING'
)
ORDER BY table_name;

PROMPT [2] Master codes in nse_sector_master
SELECT sector_code, sector_name, index_code, display_order FROM nse_sector_master
WHERE sector_code IN ('CEMENT_CEMENT_PRODUCTS', 'CONSTRUCTION', 'CONSTRUCTION_MATERIALS', 'INFRASTRUCTURE')
ORDER BY sector_code;

PROMPT [3] Staging tables row counts
SELECT 'CEMENT_CEMENT_PRODUCTS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING
UNION ALL
SELECT 'CONSTRUCTION_STAGING', COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_STAGING
UNION ALL
SELECT 'CONSTRUCTION_MATERIALS_STAGING', COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING
UNION ALL
SELECT 'INFRASTRUCTURE_STAGING', COUNT(*) FROM NSE_NIFTY_INFRASTRUCTURE_STAGING;

PROMPT [4] Duplicate symbols check within staging tables
SELECT 'CEMENT' AS tbl, symbol, COUNT(*) FROM NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1
UNION ALL
SELECT 'CONSTRUCTION', symbol, COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_STAGING GROUP BY symbol HAVING COUNT(*) > 1
UNION ALL
SELECT 'CONSTRUCTION_MATERIALS', symbol, COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING GROUP BY symbol HAVING COUNT(*) > 1
UNION ALL
SELECT 'INFRASTRUCTURE', symbol, COUNT(*) FROM NSE_NIFTY_INFRASTRUCTURE_STAGING GROUP BY symbol HAVING COUNT(*) > 1;

PROMPT [5] Cross-sector duplicate symbol check (across ALL staging tables)
WITH all_stage_symbols AS (
    SELECT symbol, 'NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING' AS src FROM NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING
    UNION ALL
    SELECT symbol, 'NSE_NIFTY_CONSTRUCTION_STAGING' FROM NSE_NIFTY_CONSTRUCTION_STAGING
    UNION ALL
    SELECT symbol, 'NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING' FROM NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING
    UNION ALL
    SELECT symbol, 'NSE_NIFTY_INFRASTRUCTURE_STAGING' FROM NSE_NIFTY_INFRASTRUCTURE_STAGING
    UNION ALL
    -- Include other staging tables dynamically or select from them
    SELECT map.symbol, 'NSE_SYMBOL_SECTOR_MAP/' || map.sector_code
    FROM nse_symbol_sector_map map
    WHERE map.sector_code NOT IN ('CEMENT_CEMENT_PRODUCTS', 'CONSTRUCTION', 'CONSTRUCTION_MATERIALS', 'INFRASTRUCTURE')
)
SELECT symbol, COUNT(DISTINCT src) AS matches, MIN(src) AS first_src, MAX(src) AS second_src
FROM all_stage_symbols
GROUP BY symbol
HAVING COUNT(DISTINCT src) > 1
ORDER BY symbol;

PROMPT [6] Canonical view registration
SELECT sector_code, count(*) AS symbols_in_canonical
FROM VW_NSE_CANONICAL_SECTOR_STAGE
WHERE sector_code IN ('CEMENT_CEMENT_PRODUCTS', 'CONSTRUCTION', 'CONSTRUCTION_MATERIALS', 'INFRASTRUCTURE')
GROUP BY sector_code;

PROMPT [7] Symbol Sector Map coverage
SELECT sector_code, COUNT(*) AS map_count
FROM nse_symbol_sector_map
WHERE sector_code IN ('CEMENT_CEMENT_PRODUCTS', 'CONSTRUCTION', 'CONSTRUCTION_MATERIALS', 'INFRASTRUCTURE')
GROUP BY sector_code;

PROMPT [8] DEV table to Staging table joins (Sample rows returning OHLCV)
SELECT 'CEMENT' AS sec, COUNT(DISTINCT dev.symbol) AS active_dev_symbols, COUNT(*) AS raw_ohlcv_rows
FROM NSE_NIFTY_CEMENT_CEMENT_PRODUCTS_STAGING stg
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV dev ON dev.symbol = stg.symbol
UNION ALL
SELECT 'CONSTRUCTION', COUNT(DISTINCT dev.symbol), COUNT(*)
FROM NSE_NIFTY_CONSTRUCTION_STAGING stg
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV dev ON dev.symbol = stg.symbol
UNION ALL
SELECT 'CONSTRUCTION_MATERIALS', COUNT(DISTINCT dev.symbol), COUNT(*)
FROM NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING stg
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV dev ON dev.symbol = stg.symbol
UNION ALL
SELECT 'INFRASTRUCTURE', COUNT(DISTINCT dev.symbol), COUNT(*)
FROM NSE_NIFTY_INFRASTRUCTURE_STAGING stg
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV dev ON dev.symbol = stg.symbol;
