PROMPT Validating source-pack unique sector onboarding
SET DEFINE OFF;

PROMPT [1] Table presence
SELECT table_name
FROM user_tables
WHERE table_name IN (
    'NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING',
    'NSE_NIFTY_COMMODITIES_TRADING_STAGING',
    'NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING',
    'NSE_NIFTY_DIVERSIFIED_STAGING',
    'NSE_NIFTY_BIOTECHNOLOGY_STAGING',
    'NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING',
    'NSE_NIFTY_IT_ENABLED_SERVICES_STAGING',
    'NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING',
    'NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING',
    'NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING',
    'NSE_NIFTY_METALS_MINING_STAGING',
    'NSE_NIFTY_IRON_STEEL_STAGING',
    'NSE_NIFTY_MINING_STAGING',
    'NSE_NIFTY_NON_FERROUS_METALS_STAGING',
    'NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING',
    'NSE_NIFTY_LUBRICANTS_STAGING',
    'NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING',
    'NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING',
    'NSE_NIFTY_PAPER_PACKAGING_STAGING',
    'NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING',
    'NSE_NIFTY_FOOTWEAR_STAGING',
    'NSE_NIFTY_GEMS_STAGING',
    'NSE_NIFTY_JEWELLERY_WATCHES_STAGING',
    'NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING',
    'NSE_NIFTY_TEXTILES_APPARELS_STAGING'
)
ORDER BY table_name;

PROMPT [2] Master codes in NSE_SECTOR_MASTER
SELECT sector_code, sector_name, index_code, display_order
FROM nse_sector_master
WHERE sector_code IN (
    'HOUSEHOLD_PERSONAL_PRODUCTS',
    'COMMODITIES_TRADING',
    'DEFENCE_AEROSPACE_DEFENSE',
    'DIVERSIFIED',
    'BIOTECHNOLOGY',
    'MEDICAL_EQUIPMENT_SUPPLIES',
    'IT_ENABLED_SERVICES',
    'SOFTWARE_PRODUCTS_SERVICES',
    'MEDIA_ENTERTAINMENT',
    'PRINT_MEDIA_PUBLISHING',
    'METALS_MINING',
    'IRON_STEEL',
    'MINING',
    'NON_FERROUS_METALS',
    'LPG_CNG_PNG_LNG_SUPPLIER',
    'LUBRICANTS',
    'OIL_EQUIPMENT_SERVICES',
    'PETROLEUM_PRODUCTS_REFINERIES',
    'PAPER_PACKAGING',
    'WASTE_WATER_MANAGEMENT',
    'FOOTWEAR',
    'GEMS',
    'JEWELLERY_WATCHES',
    'LEATHER_LEATHER_PRODUCTS',
    'TEXTILES_APPARELS'
)
ORDER BY sector_code;

PROMPT [3] Staging row counts
SELECT 'NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_COMMODITIES_TRADING_STAGING', COUNT(*) FROM NSE_NIFTY_COMMODITIES_TRADING_STAGING UNION ALL
SELECT 'NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING', COUNT(*) FROM NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING UNION ALL
SELECT 'NSE_NIFTY_DIVERSIFIED_STAGING', COUNT(*) FROM NSE_NIFTY_DIVERSIFIED_STAGING UNION ALL
SELECT 'NSE_NIFTY_BIOTECHNOLOGY_STAGING', COUNT(*) FROM NSE_NIFTY_BIOTECHNOLOGY_STAGING UNION ALL
SELECT 'NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING', COUNT(*) FROM NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING UNION ALL
SELECT 'NSE_NIFTY_IT_ENABLED_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_IT_ENABLED_SERVICES_STAGING UNION ALL
SELECT 'NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING UNION ALL
SELECT 'NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING', COUNT(*) FROM NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING UNION ALL
SELECT 'NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING', COUNT(*) FROM NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING UNION ALL
SELECT 'NSE_NIFTY_METALS_MINING_STAGING', COUNT(*) FROM NSE_NIFTY_METALS_MINING_STAGING UNION ALL
SELECT 'NSE_NIFTY_IRON_STEEL_STAGING', COUNT(*) FROM NSE_NIFTY_IRON_STEEL_STAGING UNION ALL
SELECT 'NSE_NIFTY_MINING_STAGING', COUNT(*) FROM NSE_NIFTY_MINING_STAGING UNION ALL
SELECT 'NSE_NIFTY_NON_FERROUS_METALS_STAGING', COUNT(*) FROM NSE_NIFTY_NON_FERROUS_METALS_STAGING UNION ALL
SELECT 'NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING', COUNT(*) FROM NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING UNION ALL
SELECT 'NSE_NIFTY_LUBRICANTS_STAGING', COUNT(*) FROM NSE_NIFTY_LUBRICANTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING UNION ALL
SELECT 'NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING', COUNT(*) FROM NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING UNION ALL
SELECT 'NSE_NIFTY_PAPER_PACKAGING_STAGING', COUNT(*) FROM NSE_NIFTY_PAPER_PACKAGING_STAGING UNION ALL
SELECT 'NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING', COUNT(*) FROM NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING UNION ALL
SELECT 'NSE_NIFTY_FOOTWEAR_STAGING', COUNT(*) FROM NSE_NIFTY_FOOTWEAR_STAGING UNION ALL
SELECT 'NSE_NIFTY_GEMS_STAGING', COUNT(*) FROM NSE_NIFTY_GEMS_STAGING UNION ALL
SELECT 'NSE_NIFTY_JEWELLERY_WATCHES_STAGING', COUNT(*) FROM NSE_NIFTY_JEWELLERY_WATCHES_STAGING UNION ALL
SELECT 'NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING', COUNT(*) FROM NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_TEXTILES_APPARELS_STAGING', COUNT(*) FROM NSE_NIFTY_TEXTILES_APPARELS_STAGING;

PROMPT [4] Duplicate symbols inside new staging tables
SELECT 'NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING' AS table_name, COUNT(*) AS duplicate_symbols FROM (SELECT symbol FROM NSE_NIFTY_HOUSEHOLD_PERSONAL_PRODUCTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_COMMODITIES_TRADING_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_COMMODITIES_TRADING_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_DEFENCE_AEROSPACE_DEFENSE_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_DIVERSIFIED_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_DIVERSIFIED_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_BIOTECHNOLOGY_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_BIOTECHNOLOGY_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_MEDICAL_EQUIPMENT_SUPPLIES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_IT_ENABLED_SERVICES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_IT_ENABLED_SERVICES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_SOFTWARE_PRODUCTS_SERVICES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_MEDIA_ENTERTAINMENT_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_PRINT_MEDIA_PUBLISHING_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_METALS_MINING_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_METALS_MINING_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_IRON_STEEL_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_IRON_STEEL_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_MINING_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_MINING_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_NON_FERROUS_METALS_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_NON_FERROUS_METALS_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_LPG_CNG_PNG_LNG_SUPPLIER_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_LUBRICANTS_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_LUBRICANTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_OIL_EQUIPMENT_SERVICES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_PETROLEUM_PRODUCTS_REFINERIES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_PAPER_PACKAGING_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_PAPER_PACKAGING_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_WASTE_WATER_MANAGEMENT_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_FOOTWEAR_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_FOOTWEAR_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_GEMS_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_GEMS_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_JEWELLERY_WATCHES_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_JEWELLERY_WATCHES_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_LEATHER_LEATHER_PRODUCTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1) UNION ALL
SELECT 'NSE_NIFTY_TEXTILES_APPARELS_STAGING', COUNT(*) FROM (SELECT symbol FROM NSE_NIFTY_TEXTILES_APPARELS_STAGING GROUP BY symbol HAVING COUNT(*) > 1);

PROMPT [5] Duplicate sector codes and names in NSE_SECTOR_MASTER
SELECT sector_code, COUNT(*) AS duplicate_count
FROM NSE_SECTOR_MASTER
GROUP BY sector_code
HAVING COUNT(*) > 1
ORDER BY sector_code;

SELECT UPPER(TRIM(sector_name)) AS sector_name, COUNT(*) AS duplicate_count
FROM NSE_SECTOR_MASTER
GROUP BY UPPER(TRIM(sector_name))
HAVING COUNT(*) > 1
ORDER BY sector_name;

PROMPT [6] Canonical source view registration check
SELECT DISTINCT sector_code, source_table
FROM VW_NSE_CANONICAL_SECTOR_STAGE
WHERE sector_code IN (
    'HOUSEHOLD_PERSONAL_PRODUCTS',
    'COMMODITIES_TRADING',
    'DEFENCE_AEROSPACE_DEFENSE',
    'DIVERSIFIED',
    'BIOTECHNOLOGY',
    'MEDICAL_EQUIPMENT_SUPPLIES',
    'IT_ENABLED_SERVICES',
    'SOFTWARE_PRODUCTS_SERVICES',
    'MEDIA_ENTERTAINMENT',
    'PRINT_MEDIA_PUBLISHING',
    'METALS_MINING',
    'IRON_STEEL',
    'MINING',
    'NON_FERROUS_METALS',
    'LPG_CNG_PNG_LNG_SUPPLIER',
    'LUBRICANTS',
    'OIL_EQUIPMENT_SERVICES',
    'PETROLEUM_PRODUCTS_REFINERIES',
    'PAPER_PACKAGING',
    'WASTE_WATER_MANAGEMENT',
    'FOOTWEAR',
    'GEMS',
    'JEWELLERY_WATCHES',
    'LEATHER_LEATHER_PRODUCTS',
    'TEXTILES_APPARELS'
)
ORDER BY sector_code, source_table;

PROMPT [7] Symbol-sector map counts
SELECT sector_code, COUNT(*) AS mapped_symbols
FROM NSE_SYMBOL_SECTOR_MAP
WHERE sector_code IN (
    'HOUSEHOLD_PERSONAL_PRODUCTS',
    'COMMODITIES_TRADING',
    'DEFENCE_AEROSPACE_DEFENSE',
    'DIVERSIFIED',
    'BIOTECHNOLOGY',
    'MEDICAL_EQUIPMENT_SUPPLIES',
    'IT_ENABLED_SERVICES',
    'SOFTWARE_PRODUCTS_SERVICES',
    'MEDIA_ENTERTAINMENT',
    'PRINT_MEDIA_PUBLISHING',
    'METALS_MINING',
    'IRON_STEEL',
    'MINING',
    'NON_FERROUS_METALS',
    'LPG_CNG_PNG_LNG_SUPPLIER',
    'LUBRICANTS',
    'OIL_EQUIPMENT_SERVICES',
    'PETROLEUM_PRODUCTS_REFINERIES',
    'PAPER_PACKAGING',
    'WASTE_WATER_MANAGEMENT',
    'FOOTWEAR',
    'GEMS',
    'JEWELLERY_WATCHES',
    'LEATHER_LEATHER_PRODUCTS',
    'TEXTILES_APPARELS'
)
GROUP BY sector_code
ORDER BY sector_code;

PROMPT [8] DEV table to sector map join check
SELECT s.sector_code, COUNT(d.symbol) AS active_price_rows
FROM NSE_SYMBOL_SECTOR_MAP s
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV d ON UPPER(TRIM(d.symbol)) = UPPER(TRIM(s.symbol))
WHERE s.sector_code IN (
    'HOUSEHOLD_PERSONAL_PRODUCTS',
    'COMMODITIES_TRADING',
    'DEFENCE_AEROSPACE_DEFENSE',
    'DIVERSIFIED',
    'BIOTECHNOLOGY',
    'MEDICAL_EQUIPMENT_SUPPLIES',
    'IT_ENABLED_SERVICES',
    'SOFTWARE_PRODUCTS_SERVICES',
    'MEDIA_ENTERTAINMENT',
    'PRINT_MEDIA_PUBLISHING',
    'METALS_MINING',
    'IRON_STEEL',
    'MINING',
    'NON_FERROUS_METALS',
    'LPG_CNG_PNG_LNG_SUPPLIER',
    'LUBRICANTS',
    'OIL_EQUIPMENT_SERVICES',
    'PETROLEUM_PRODUCTS_REFINERIES',
    'PAPER_PACKAGING',
    'WASTE_WATER_MANAGEMENT',
    'FOOTWEAR',
    'GEMS',
    'JEWELLERY_WATCHES',
    'LEATHER_LEATHER_PRODUCTS',
    'TEXTILES_APPARELS'
)
GROUP BY s.sector_code
ORDER BY s.sector_code;
