-- Validation for FYERS automation enterprise job tracking.

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'FYERS_EXTRACTION_RUNS',
    'FYERS_EXTRACTION_SYMBOL_STATUS'
)
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE (
        TABLE_NAME = 'FYERS_EXTRACTION_RUNS'
        AND COLUMN_NAME IN (
            'JOB_ID', 'JOB_TYPE', 'TRADING_DATE', 'STATUS', 'TOTAL_SYMBOLS',
            'INSERTED_COUNT', 'REMAINING_COUNT', 'FAILED_COUNT', 'SKIPPED_COUNT',
            'INSERTED_SKIPPED_COUNT', 'INVALID_COUNT', 'ERROR_COUNT',
            'STARTED_AT', 'UPDATED_AT', 'COMPLETED_AT',
            'REQUESTED_STOP_FLAG', 'ERROR_MESSAGE'
        )
    )
    OR (
        TABLE_NAME = 'FYERS_EXTRACTION_SYMBOL_STATUS'
        AND COLUMN_NAME IN (
            'JOB_ID', 'SYMBOL', 'TRADING_DATE', 'STATUS', 'STATUS_REASON',
            'RETRY_COUNT', 'ERROR_MESSAGE', 'STARTED_AT', 'COMPLETED_AT'
        )
    )
ORDER BY TABLE_NAME, COLUMN_ID;

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE INDEX_NAME IN (
    'IDX_FYERS_EXT_RUNS_01',
    'IDX_FYERS_EXT_SYM_01'
)
ORDER BY INDEX_NAME;

SELECT STATUS, COUNT(*) AS JOB_COUNT
FROM FYERS_EXTRACTION_RUNS
GROUP BY STATUS
ORDER BY STATUS;

SELECT STATUS, COUNT(*) AS SYMBOL_COUNT
FROM FYERS_EXTRACTION_SYMBOL_STATUS
GROUP BY STATUS
ORDER BY STATUS;

SELECT JOB_ID, TRADING_DATE, TOTAL_SYMBOLS, INSERTED_COUNT, REMAINING_COUNT,
       FAILED_COUNT, SKIPPED_COUNT, INSERTED_SKIPPED_COUNT, INVALID_COUNT,
       ERROR_COUNT, REQUESTED_STOP_FLAG, STATUS, UPDATED_AT
FROM FYERS_EXTRACTION_RUNS
ORDER BY NVL(UPDATED_AT, STARTED_AT) DESC
FETCH FIRST 20 ROWS ONLY;
