PROMPT Validating Restaurants, Hospitality Hotels & Resorts, Tourism & Travel Sectors

SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  -- Check Staging Tables
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NSE_NIFTY_RESTAURANTS_STAGING';
  IF v_count = 0 THEN DBMS_OUTPUT.PUT_LINE('FAIL: NSE_NIFTY_RESTAURANTS_STAGING missing.'); ELSE DBMS_OUTPUT.PUT_LINE('PASS: NSE_NIFTY_RESTAURANTS_STAGING exists.'); END IF;

  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING';
  IF v_count = 0 THEN DBMS_OUTPUT.PUT_LINE('FAIL: NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING missing.'); ELSE DBMS_OUTPUT.PUT_LINE('PASS: NSE_NIFTY_HOSPITALITY_HOTELS_RESORTS_STAGING exists.'); END IF;

  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NSE_NIFTY_TOURISM_TRAVEL_STAGING';
  IF v_count = 0 THEN DBMS_OUTPUT.PUT_LINE('FAIL: NSE_NIFTY_TOURISM_TRAVEL_STAGING missing.'); ELSE DBMS_OUTPUT.PUT_LINE('PASS: NSE_NIFTY_TOURISM_TRAVEL_STAGING exists.'); END IF;

  -- Check Master Rows
  SELECT COUNT(*) INTO v_count FROM NSE_SECTOR_MASTER WHERE SECTOR_CODE IN ('RESTAURANTS', 'HOSPITALITY_HOTELS_RESORTS', 'TOURISM_TRAVEL');
  IF v_count < 3 THEN DBMS_OUTPUT.PUT_LINE('FAIL: Some sector master records missing.'); ELSE DBMS_OUTPUT.PUT_LINE('PASS: Sector master records exist.'); END IF;
  
  -- Check Canonical View
  SELECT COUNT(*) INTO v_count FROM VW_NSE_CANONICAL_SECTOR_STAGE WHERE sector_code IN ('RESTAURANTS', 'HOSPITALITY_HOTELS_RESORTS', 'TOURISM_TRAVEL');
  IF v_count < 3 THEN DBMS_OUTPUT.PUT_LINE('FAIL: Staging tables NOT registered in canonical view VW_NSE_CANONICAL_SECTOR_STAGE.'); ELSE DBMS_OUTPUT.PUT_LINE('PASS: Staging tables registered in VW_NSE_CANONICAL_SECTOR_STAGE.'); END IF;

END;
/
EXIT;
