PROMPT Validating Chemicals and Specialty Products sector onboarding
SET DEFINE OFF;

PROMPT [1] Table presence
SELECT table_name
FROM user_tables
WHERE table_name IN (
    'NSE_NIFTY_CHEMICALS_STAGING',
    'NSE_NIFTY_SPECIALTY_CHEMICALS_STAGING',
    'NSE_NIFTY_PETROCHEMICALS_STAGING',
    'NSE_NIFTY_PAINTS_STAGING',
    'NSE_NIFTY_PLASTIC_PRODUCTS_STAGING',
    'NSE_NIFTY_EXPLOSIVES_STAGING',
    'NSE_NIFTY_ABRASIVES_STAGING',
    'NSE_NIFTY_ELECTRODES_REFRACTORIES_STAGING'
)
ORDER BY table_name;

PROMPT [2] Master codes in nse_sector_master
SELECT sector_code, sector_name, index_code, display_order
FROM nse_sector_master
WHERE sector_code IN (
    'CHEMICALS',
    'SPECIALTY_CHEMICALS',
    'PETROCHEMICALS',
    'PAINTS',
    'PLASTIC_PRODUCTS',
    'EXPLOSIVES',
    'ABRASIVES',
    'ELECTRODES_REFRACTORIES'
)
ORDER BY sector_code;

PROMPT [3] Staging row counts
SELECT 'NSE_NIFTY_CHEMICALS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_CHEMICALS_STAGING UNION ALL
SELECT 'NSE_NIFTY_SPECIALTY_CHEMICALS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_SPECIALTY_CHEMICALS_STAGING UNION ALL
SELECT 'NSE_NIFTY_PETROCHEMICALS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_PETROCHEMICALS_STAGING UNION ALL
SELECT 'NSE_NIFTY_PAINTS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_PAINTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_PLASTIC_PRODUCTS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_PLASTIC_PRODUCTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_EXPLOSIVES_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_EXPLOSIVES_STAGING UNION ALL
SELECT 'NSE_NIFTY_ABRASIVES_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_ABRASIVES_STAGING UNION ALL
SELECT 'NSE_NIFTY_ELECTRODES_REFRACTORIES_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_ELECTRODES_REFRACTORIES_STAGING;

PROMPT [4] Duplicate symbols inside new staging tables
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_CHEMICALS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_SPECIALTY_CHEMICALS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_PETROCHEMICALS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_PAINTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_PLASTIC_PRODUCTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_EXPLOSIVES_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_ABRASIVES_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_ELECTRODES_REFRACTORIES_STAGING GROUP BY symbol HAVING COUNT(*) > 1;

PROMPT [5] Canonical source view registration check
SELECT DISTINCT sector_code, source_table
FROM VW_NSE_CANONICAL_SECTOR_STAGE
WHERE sector_code IN (
    'CHEMICALS',
    'SPECIALTY_CHEMICALS',
    'PETROCHEMICALS',
    'PAINTS',
    'PLASTIC_PRODUCTS',
    'EXPLOSIVES',
    'ABRASIVES',
    'ELECTRODES_REFRACTORIES'
)
ORDER BY sector_code;

PROMPT [6] Symbol-sector map counts
SELECT sector_code, COUNT(*) AS mapped_symbols
FROM NSE_SYMBOL_SECTOR_MAP
WHERE sector_code IN (
    'CHEMICALS',
    'SPECIALTY_CHEMICALS',
    'PETROCHEMICALS',
    'PAINTS',
    'PLASTIC_PRODUCTS',
    'EXPLOSIVES',
    'ABRASIVES',
    'ELECTRODES_REFRACTORIES'
)
GROUP BY sector_code
ORDER BY sector_code;

PROMPT [7] DEV table to staging table join check
SELECT s.sector_code, COUNT(d.symbol) AS active_price_rows
FROM NSE_SYMBOL_SECTOR_MAP s
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV d ON UPPER(TRIM(d.symbol)) = UPPER(TRIM(s.symbol))
WHERE s.sector_code IN (
    'CHEMICALS',
    'SPECIALTY_CHEMICALS',
    'PETROCHEMICALS',
    'PAINTS',
    'PLASTIC_PRODUCTS',
    'EXPLOSIVES',
    'ABRASIVES',
    'ELECTRODES_REFRACTORIES'
)
GROUP BY s.sector_code
ORDER BY s.sector_code;
