PROMPT Validate Media symbol backfill coverage in staging and sector-map tables.
SET DEFINE OFF;

SELECT
  UPPER(TRIM(SYMBOL)) AS SYMBOL,
  SECTOR
FROM NSE_NIFTY_MEDIA_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN (
  'ZEEL',
  'NETWORK18',
  'SAREGAMA',
  'TIPSMUSIC',
  'NAZARA',
  'AQYLON',
  'SUNTV',
  'PFOCUS',
  'PVRINOX',
  'HATHWAY',
  'NDTV',
  'ZEEMEDIA',
  'DEN',
  'DISHTV',
  'SIGNPOST',
  'BALAJITELE',
  'TVTODAY',
  'ENIL',
  'ONMOBILE',
  'RKSWAMY',
  'GTPL',
  'DBCORP'
)
ORDER BY 1;

SELECT
  UPPER(TRIM(SYMBOL)) AS SYMBOL,
  SECTOR_CODE
FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN (
  'ZEEL',
  'NETWORK18',
  'SAREGAMA',
  'TIPSMUSIC',
  'NAZARA',
  'AQYLON',
  'SUNTV',
  'PFOCUS',
  'PVRINOX',
  'HATHWAY',
  'NDTV',
  'ZEEMEDIA',
  'DEN',
  'DISHTV',
  'SIGNPOST',
  'BALAJITELE',
  'TVTODAY',
  'ENIL',
  'ONMOBILE',
  'RKSWAMY',
  'GTPL',
  'DBCORP'
)
ORDER BY 1;
