PROMPT Validating Auto Components & Equipments sector tables

SET DEFINE OFF;
SET SERVEROUTPUT ON;

DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING';
    IF l_count = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PASS: Table NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING exists.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FAIL: Table NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING does not exist.');
    END IF;

    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'UK_NIFTY_AUTO_COMP_EQ_SYM';
    IF l_count = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PASS: Index UK_NIFTY_AUTO_COMP_EQ_SYM exists.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FAIL: Index UK_NIFTY_AUTO_COMP_EQ_SYM does not exist.');
    END IF;

    SELECT COUNT(*) INTO l_count FROM NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING;
    DBMS_OUTPUT.PUT_LINE('INFO: NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING has ' || l_count || ' rows.');

    SELECT COUNT(*) INTO l_count FROM NSE_SECTOR_MASTER WHERE sector_code = 'AUTO_COMPONENTS_EQUIPMENTS';
    IF l_count = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PASS: NSE_SECTOR_MASTER has AUTO_COMPONENTS_EQUIPMENTS.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FAIL: NSE_SECTOR_MASTER missing AUTO_COMPONENTS_EQUIPMENTS.');
    END IF;
    
    SELECT COUNT(*) INTO l_count FROM VW_NSE_CANONICAL_SECTOR_STAGE WHERE sector_code = 'AUTO_COMPONENTS_EQUIPMENTS';
    IF l_count > 0 THEN
        DBMS_OUTPUT.PUT_LINE('PASS: VW_NSE_CANONICAL_SECTOR_STAGE returns ' || l_count || ' symbols for AUTO_COMPONENTS_EQUIPMENTS.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FAIL: VW_NSE_CANONICAL_SECTOR_STAGE missing AUTO_COMPONENTS_EQUIPMENTS sync.');
    END IF;
END;
/
