PROMPT Validating Capital Goods, Engineering & Industrials sector onboarding
SET DEFINE OFF;

PROMPT [1] Table presence
SELECT table_name
FROM user_tables
WHERE table_name IN (
    'NSE_NIFTY_ENGINEERING_STAGING',
    'NSE_NIFTY_ELEC_HEAVY_EQUIP_STAGING',
    'NSE_NIFTY_INDUSTRIAL_MANUFACTURING_STAGING',
    'NSE_NIFTY_INDUSTRIAL_PRODUCTS_STAGING',
    'NSE_NIFTY_INDUSTRIAL_GASES_FUELS_STAGING',
    'NSE_NIFTY_CAPITAL_GOODS_STAGING'
)
ORDER BY table_name;

PROMPT [2] Master codes in nse_sector_master
SELECT sector_code, sector_name, index_code, display_order
FROM nse_sector_master
WHERE sector_code IN (
    'ENGINEERING',
    'ELEC_HEAVY_EQUIPMENT',
    'INDUSTRIAL_MANUFACTURING',
    'INDUSTRIAL_PRODUCTS',
    'INDUSTRIAL_GASES_FUELS',
    'CAPITAL_GOODS'
)
ORDER BY sector_code;

PROMPT [3] Staging row counts
SELECT 'NSE_NIFTY_ENGINEERING_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_ENGINEERING_STAGING UNION ALL
SELECT 'NSE_NIFTY_ELEC_HEAVY_EQUIP_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_ELEC_HEAVY_EQUIP_STAGING UNION ALL
SELECT 'NSE_NIFTY_INDUSTRIAL_MANUFACTURING_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_INDUSTRIAL_MANUFACTURING_STAGING UNION ALL
SELECT 'NSE_NIFTY_INDUSTRIAL_PRODUCTS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_INDUSTRIAL_PRODUCTS_STAGING UNION ALL
SELECT 'NSE_NIFTY_INDUSTRIAL_GASES_FUELS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_INDUSTRIAL_GASES_FUELS_STAGING UNION ALL
SELECT 'NSE_NIFTY_CAPITAL_GOODS_STAGING' AS table_name, COUNT(*) AS row_count FROM NSE_NIFTY_CAPITAL_GOODS_STAGING;

PROMPT [4] Duplicate symbols inside new staging tables
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_ENGINEERING_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_ELEC_HEAVY_EQUIP_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_INDUSTRIAL_MANUFACTURING_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_INDUSTRIAL_PRODUCTS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_INDUSTRIAL_GASES_FUELS_STAGING GROUP BY symbol HAVING COUNT(*) > 1 UNION ALL
SELECT symbol, COUNT(*) AS dups FROM NSE_NIFTY_CAPITAL_GOODS_STAGING GROUP BY symbol HAVING COUNT(*) > 1;

PROMPT [5] Canonical source view registration check
SELECT DISTINCT sector_code, source_table
FROM VW_NSE_CANONICAL_SECTOR_STAGE
WHERE sector_code IN (
    'ENGINEERING',
    'ELEC_HEAVY_EQUIPMENT',
    'INDUSTRIAL_MANUFACTURING',
    'INDUSTRIAL_PRODUCTS',
    'INDUSTRIAL_GASES_FUELS',
    'CAPITAL_GOODS'
)
ORDER BY sector_code;

PROMPT [6] Symbol-sector map counts
SELECT sector_code, COUNT(*) AS mapped_symbols
FROM NSE_SYMBOL_SECTOR_MAP
WHERE sector_code IN (
    'ENGINEERING',
    'ELEC_HEAVY_EQUIPMENT',
    'INDUSTRIAL_MANUFACTURING',
    'INDUSTRIAL_PRODUCTS',
    'INDUSTRIAL_GASES_FUELS',
    'CAPITAL_GOODS'
)
GROUP BY sector_code
ORDER BY sector_code;

PROMPT [7] DEV table to staging table join check
SELECT s.sector_code, COUNT(d.symbol) AS active_price_rows
FROM NSE_SYMBOL_SECTOR_MAP s
JOIN NSE_NIFTY500_DAILY_RAW_DATA_DEV d ON UPPER(TRIM(d.symbol)) = UPPER(TRIM(s.symbol))
WHERE s.sector_code IN (
    'ENGINEERING',
    'ELEC_HEAVY_EQUIPMENT',
    'INDUSTRIAL_MANUFACTURING',
    'INDUSTRIAL_PRODUCTS',
    'INDUSTRIAL_GASES_FUELS',
    'CAPITAL_GOODS'
)
GROUP BY s.sector_code
ORDER BY s.sector_code;
