-- Read-only validation for canonical NSE cleanup.
SELECT 'DEV_OBSOLETE' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV
WHERE REGEXP_LIKE(UPPER(TRIM(SYMBOL)), '^(NSE:)?(BOSCHHCIL|MIRCELECTR|RESTAURANT|SCHLOSS|SHOPPERS|VISHALMEGA)(-(EQ|BE|SM|ST|BZ))?$')
UNION ALL
SELECT 'STOCK_EOD_OBSOLETE', COUNT(*) FROM STOCK_EOD_HISTORY
WHERE REGEXP_LIKE(UPPER(TRIM(SYMBOL)), '^(NSE:)?(BOSCHHCIL|MIRCELECTR|RESTAURANT|SCHLOSS|SHOPPERS|VISHALMEGA)(-(EQ|BE|SM|ST|BZ))?$')
UNION ALL
SELECT 'MAP_OBSOLETE', COUNT(*) FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN ('BOSCHHCIL','MIRCELECTR','RESTAURANT','SCHLOSS','SHOPPERS','VISHALMEGA');

SELECT SYMBOL, TRUNC(TRADING_DATE) AS TRADING_DATE, COUNT(*) AS ROW_COUNT
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV
GROUP BY SYMBOL, TRUNC(TRADING_DATE)
HAVING COUNT(*) > 1;

SELECT SYMBOL, TRUNC(TRADE_DATE) AS TRADE_DATE, COUNT(*) AS ROW_COUNT
FROM STOCK_EOD_HISTORY
GROUP BY SYMBOL, TRUNC(TRADE_DATE)
HAVING COUNT(*) > 1;

