PROMPT Validate FACT_OHLCV sync procedures.

SELECT object_name, object_type, status
FROM user_objects
WHERE object_name IN (
  'PR_SYNC_DIM_SYMBOLS_FROM_DEV',
  'PR_MERGE_FACT_OHLCV_FROM_DEV',
  'PR_SYNC_FACT_OHLCV_FROM_DEV'
)
ORDER BY object_type, object_name;

SELECT
  (SELECT MAX(TRADING_DATE) FROM FACT_OHLCV) AS fact_max_trade_date,
  (SELECT MAX(TRADING_DATE) FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV) AS dev_max_trade_date
FROM dual;

SELECT COUNT(*) AS unmapped_dev_symbols
FROM (
  SELECT DISTINCT UPPER(TRIM(d.SYMBOL)) AS symbol
  FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV d
  LEFT JOIN DIM_SYMBOLS s
    ON UPPER(TRIM(s.SYMBOL)) = UPPER(TRIM(d.SYMBOL))
  WHERE d.SYMBOL IS NOT NULL
    AND s.SYMBOL_ID IS NULL
);

SELECT COUNT(*) AS missing_fact_rows
FROM (
  SELECT s.SYMBOL_ID, d.TRADING_DATE
  FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV d
  JOIN DIM_SYMBOLS s
    ON UPPER(TRIM(s.SYMBOL)) = UPPER(TRIM(d.SYMBOL))
  WHERE d.TRADING_DATE IS NOT NULL
  MINUS
  SELECT f.SYMBOL_ID, f.TRADING_DATE
  FROM FACT_OHLCV f
);

SELECT *
FROM (
  SELECT
    d.TRADING_DATE,
    d.SYMBOL,
    d.PREVIOUS_CLOSE AS dev_previous_close,
    f.PREVIOUS_CLOSE AS fact_previous_close,
    d.VOLUME AS dev_volume,
    f.VOLUME AS fact_volume
  FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV d
  JOIN DIM_SYMBOLS s
    ON UPPER(TRIM(s.SYMBOL)) = UPPER(TRIM(d.SYMBOL))
  JOIN FACT_OHLCV f
    ON f.SYMBOL_ID = s.SYMBOL_ID
   AND f.TRADING_DATE = d.TRADING_DATE
  ORDER BY d.TRADING_DATE DESC, d.SYMBOL
)
WHERE ROWNUM <= 20;
