PROMPT Validation queries for missing sector table/symbol sync
SET DEFINE OFF;

PROMPT [1] Check all sector staging tables
SELECT table_name
FROM user_tables
WHERE table_name LIKE 'NSE_NIFTY%STAGING'
ORDER BY table_name;

PROMPT [2] Check symbol count for key sector tables
SELECT 'NSE_NIFTY_AUTO_STAGING' table_name, COUNT(*) symbol_count FROM NSE_NIFTY_AUTO_STAGING
UNION ALL
SELECT 'NSE_NIFTY_CAPITAL_GOODS_STAGING', COUNT(*) FROM NSE_NIFTY_CAPITAL_GOODS_STAGING
UNION ALL
SELECT 'NSE_NIFTY_CONSTRUCTION_STAGING', COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_STAGING
UNION ALL
SELECT 'NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING', COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_MATERIALS_STAGING
UNION ALL
SELECT 'NSE_NIFTY_CONSUMER_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_CONSUMER_SERVICES_STAGING
UNION ALL
SELECT 'NSE_NIFTY_DIVERSIFIED_STAGING', COUNT(*) FROM NSE_NIFTY_DIVERSIFIED_STAGING
UNION ALL
SELECT 'NSE_NIFTY_FOREST_MATERIALS_STAGING', COUNT(*) FROM NSE_NIFTY_FOREST_MATERIALS_STAGING
UNION ALL
SELECT 'NSE_NIFTY_POWER_STAGING', COUNT(*) FROM NSE_NIFTY_POWER_STAGING
UNION ALL
SELECT 'NSE_NIFTY_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_SERVICES_STAGING
UNION ALL
SELECT 'NSE_NIFTY_TELECOMMUNICATION_STAGING', COUNT(*) FROM NSE_NIFTY_TELECOMMUNICATION_STAGING
UNION ALL
SELECT 'NSE_NIFTY_TEXTILES_STAGING', COUNT(*) FROM NSE_NIFTY_TEXTILES_STAGING
UNION ALL
SELECT 'NSE_NIFTY_UTILITIES_STAGING', COUNT(*) FROM NSE_NIFTY_UTILITIES_STAGING;

PROMPT [3] Duplicate symbols check template (replace table name if needed)
PROMPT SELECT symbol, COUNT(*) FROM NSE_NIFTY_POWER_STAGING GROUP BY symbol HAVING COUNT(*) > 1;

PROMPT [4] Missing symbols in target table before/after sync template
PROMPT SELECT COUNT(*) missing_count
PROMPT FROM (
PROMPT   SELECT DISTINCT UPPER(TRIM(s.symbol)) symbol
PROMPT   FROM NSE_TOTAL_MARKET_SECTOR_SOURCE_STG s
PROMPT   WHERE UPPER(TRIM(s.industry)) = 'POWER'
PROMPT ) src
PROMPT WHERE NOT EXISTS (
PROMPT   SELECT 1 FROM NSE_NIFTY_POWER_STAGING t
PROMPT   WHERE UPPER(TRIM(t.symbol)) = src.symbol
PROMPT );
