SET DEFINE OFF;

SELECT 'NSE_NIFTY_IT_STAGING' AS SOURCE_NAME, COUNT(*) AS REMAINING_ROWS
FROM NSE_NIFTY_IT_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN ('CIGNITITEC', 'RELINFRA')
UNION ALL
SELECT 'NSE_NIFTY_INFRASTRUCTURE_STAGING', COUNT(*)
FROM NSE_NIFTY_INFRASTRUCTURE_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN ('CIGNITITEC', 'RELINFRA')
UNION ALL
SELECT 'NSE_NIFTY_UTILITIES_STAGING', COUNT(*)
FROM NSE_NIFTY_UTILITIES_STAGING
WHERE UPPER(TRIM(SYMBOL)) IN ('CIGNITITEC', 'RELINFRA')
UNION ALL
SELECT 'NSE_SYMBOL_SECTOR_MAP', COUNT(*)
FROM NSE_SYMBOL_SECTOR_MAP
WHERE UPPER(TRIM(SYMBOL)) IN ('CIGNITITEC', 'RELINFRA');

PROMPT Expected REMAINING_ROWS = 0 for every source.
