PROMPT Validation queries for Sector Rotation missing-table/missing-symbol sync
SET DEFINE OFF;

PROMPT [1] Check missing tables created
SELECT table_name
FROM user_tables
WHERE table_name IN (
  'NSE_NIFTY_CAPITAL_GOODS_STAGING',
  'NSE_NIFTY_CONSTRUCTION_STAGING',
  'NSE_NIFTY_POWER_STAGING',
  'NSE_NIFTY_SERVICES_STAGING',
  'NSE_NIFTY_TELECOMMUNICATION_STAGING',
  'NSE_NIFTY_UTILITIES_STAGING'
)
ORDER BY table_name;

PROMPT [2] Check symbol count
SELECT 'NSE_NIFTY_CAPITAL_GOODS_STAGING' table_name, COUNT(*) count FROM NSE_NIFTY_CAPITAL_GOODS_STAGING
UNION ALL
SELECT 'NSE_NIFTY_CONSTRUCTION_STAGING', COUNT(*) FROM NSE_NIFTY_CONSTRUCTION_STAGING
UNION ALL
SELECT 'NSE_NIFTY_POWER_STAGING', COUNT(*) FROM NSE_NIFTY_POWER_STAGING
UNION ALL
SELECT 'NSE_NIFTY_SERVICES_STAGING', COUNT(*) FROM NSE_NIFTY_SERVICES_STAGING
UNION ALL
SELECT 'NSE_NIFTY_TELECOMMUNICATION_STAGING', COUNT(*) FROM NSE_NIFTY_TELECOMMUNICATION_STAGING
UNION ALL
SELECT 'NSE_NIFTY_UTILITIES_STAGING', COUNT(*) FROM NSE_NIFTY_UTILITIES_STAGING;

PROMPT [3] Check duplicate symbols (replace table name)
PROMPT SELECT symbol, COUNT(*)
PROMPT FROM NSE_NIFTY_CAPITAL_GOODS_STAGING
PROMPT GROUP BY symbol
PROMPT HAVING COUNT(*) > 1;

