PROMPT Validating Realty Real Estate sector tables

SELECT COUNT(*) AS staging_count FROM NSE_NIFTY_REALTY_REAL_ESTATE_STAGING;
SELECT * FROM NSE_SECTOR_MASTER WHERE sector_code = 'REALTY_REAL_ESTATE';
SELECT COUNT(*) AS mapping_count FROM NSE_SYMBOL_SECTOR_MAP WHERE sector_code = 'REALTY_REAL_ESTATE';

SELECT symbol FROM NSE_NIFTY_REALTY_REAL_ESTATE_STAGING
GROUP BY symbol HAVING COUNT(*) > 1;

SELECT table_name, symbol
FROM (
  SELECT 'NSE_NIFTY_REALTY_REAL_ESTATE_STAGING' AS table_name, symbol FROM NSE_NIFTY_REALTY_REAL_ESTATE_STAGING
  UNION ALL
  SELECT 'OTHER_STAGING_TABLE' AS table_name, symbol FROM dual WHERE 1=0
)
GROUP BY symbol HAVING COUNT(*) > 1;

SELECT * FROM VW_NSE_CANONICAL_SECTOR_STAGE WHERE source_table = 'NSE_NIFTY_REALTY_REAL_ESTATE_STAGING';

SELECT d.symbol, d.close_price
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV d
JOIN NSE_NIFTY_REALTY_REAL_ESTATE_STAGING s ON d.symbol = s.symbol
WHERE ROWNUM <= 5;
