-- Validation queries for Bhramhastra_BackTesting_Data.

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'BHRAMHASTRA_BACKTESTING_DATA';

SELECT INDEX_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME = 'BHRAMHASTRA_BACKTESTING_DATA'
ORDER BY INDEX_NAME;

SELECT COUNT(*) AS total_rows,
       TO_CHAR(MAX(LTC_DATE), 'YYYY-MM-DD') AS max_ltc_date,
       SUM(CASE WHEN STATUS = 'OPEN' THEN 1 ELSE 0 END) AS open_rows,
       SUM(CASE WHEN STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS closed_rows
FROM Bhramhastra_BackTesting_Data;
