import pytest

from routes.sector_rotation import (
    SECTOR_CODE_ALIASES,
    _STRICT_SECTOR_TABLE_MAP,
    _SECTOR_DISPLAY_NAME_OVERRIDES,
    _friendly_sector_name_from_code
)

def test_restaurants_hospitality_travel_sector_mapping():
    assert 'RESTAURANTS' in SECTOR_CODE_ALIASES
    assert 'RESTAURANTS' in _STRICT_SECTOR_TABLE_MAP
    assert 'RESTAURANTS' in _SECTOR_DISPLAY_NAME_OVERRIDES
    assert _STRICT_SECTOR_TABLE_MAP['RESTAURANTS'] == 'NSE_NIFTY_RESTAURANTS_STAGING'

    assert 'HOSPITALITY_HOTELS_RESORTS' in SECTOR_CODE_ALIASES
    assert 'HOSPITALITY_HOTELS_RESORTS' in _STRICT_SECTOR_TABLE_MAP
    assert 'HOSPITALITY_HOTELS_RESORTS' in _SECTOR_DISPLAY_NAME_OVERRIDES

    assert 'TOURISM_TRAVEL' in SECTOR_CODE_ALIASES
    assert 'TOURISM_TRAVEL' in _STRICT_SECTOR_TABLE_MAP
    assert 'TOURISM_TRAVEL' in _SECTOR_DISPLAY_NAME_OVERRIDES
