CREATE OR REPLACE VIEW VW_HISTORICAL_DATA_DEV AS
SELECT
    SYMBOL AS STOCK,
    TRADING_DATE,
    OPEN,
    HIGH,
    LOW,
    PREVIOUS_CLOSE AS CLOSE_PRICE,
    VOLUME,
    WEEK_BUCKET,
    MONTH_BUCKET,
    YEAR_BUCKET
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV;

CREATE OR REPLACE VIEW VW_HISTORICAL_DATA_ORACLE AS
SELECT
    SYMBOL AS STOCK,
    TRADING_DATE,
    OPEN,
    HIGH,
    LOW,
    NVL(LTP, PREVIOUS_CLOSE) AS CLOSE_PRICE,
    PREVIOUS_CLOSE,
    LTP,
    CHANGE_POINTS,
    CHANGE_PERCENTAGE,
    VOLUME,
    HIGH_52WEEK,
    LOW_52WEEK,
    PERCENTAGE_CHANGE_30_DAYS,
    PERCENTAGE_CHANGE_365_DAYS
FROM NSE_NIFTY500_DAILY_RAW_DATA_ORACLE;
