SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT Ensuring CVING_APP post-restore objects...

DECLARE
  v_source_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_source_exists
  FROM user_tables
  WHERE table_name = 'MV_NSE_SECTOR_UI_SNAPSHOT_SRC';

  IF v_source_exists > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW MV_NSE_SECTOR_UI_SNAPSHOT';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE NOT IN (-12003, -942) THEN
          NULL;
        END IF;
    END;

    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE MV_NSE_SECTOR_UI_SNAPSHOT';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          NULL;
        END IF;
    END;

    EXECUTE IMMEDIATE q'[
      CREATE MATERIALIZED VIEW MV_NSE_SECTOR_UI_SNAPSHOT
      TABLESPACE CVING_DATA
      BUILD IMMEDIATE
      REFRESH COMPLETE ON DEMAND
      AS
      SELECT
        SYMBOL,
        SECTOR,
        INDEX_CODE,
        LTC_DATE,
        CLOSE_PRICE,
        RSI55_GT0,
        RSI50_GT0,
        SMA20,
        SMA50,
        SMA100
      FROM MV_NSE_SECTOR_UI_SNAPSHOT_SRC
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_MV_SECTOR_UI_SECTOR_SYMBOL ON MV_NSE_SECTOR_UI_SNAPSHOT (SECTOR, SYMBOL) TABLESPACE CVING_INDEX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      NULL;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_MV_SECTOR_UI_SECTOR_CLOSE ON MV_NSE_SECTOR_UI_SNAPSHOT (SECTOR, CLOSE_PRICE) TABLESPACE CVING_INDEX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      NULL;
    END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
  v_start_with NUMBER := 1;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM user_tables
  WHERE table_name = 'ASURA_BULLISH_TREND_STRATEGY_TESTING';

  IF v_exists > 0 THEN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX(S_NO), 0) + 1 FROM ASURA_BULLISH_TREND_STRATEGY_TESTING'
      INTO v_start_with;
  END IF;

  SELECT COUNT(*) INTO v_exists
  FROM user_sequences
  WHERE sequence_name = 'ASURA_BTS_SEQ';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ASURA_BTS_SEQ START WITH ' || TO_CHAR(v_start_with) || ' INCREMENT BY 1 CACHE 50';
  END IF;
END;
/

PROMPT CVING_APP post-restore objects complete.
