OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\NSE_NIFTY_ENERGY_STAGING_BKP\NSE_NIFTY_ENERGY_STAGING_DATA_TABLE.ldr'
APPEND
INTO TABLE "NSE_NIFTY_ENERGY_STAGING"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SYMBOL" CHAR (50),
"SECTOR" CHAR (100))
