OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\BHRAMHASTRA_BACKTESTING_DATA_BKP\BHRAMHASTRA_BACKTESTING_DATA_DATA_TABLE.ldr'
APPEND
INTO TABLE "BHRAMHASTRA_BACKTESTING_DATA"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"ID" DECIMAL EXTERNAL,
"S_NO" DECIMAL EXTERNAL,
"SYMBOL" CHAR (30),
"STOCK_NAME" CHAR (200),
"LTC_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"TRADE_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"FIRST_TRADE_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"CALENDAR_DAYS" DECIMAL EXTERNAL,
"TRADING_DAYS" DECIMAL EXTERNAL,
"ENTRY_PRICE" DECIMAL EXTERNAL,
"EMA50" DECIMAL EXTERNAL,
"RSI14" DECIMAL EXTERNAL,
"MACD_HIST" DECIMAL EXTERNAL,
"VOLUME" DECIMAL EXTERNAL,
"ATR14" DECIMAL EXTERNAL,
"RISK_AMOUNT" DECIMAL EXTERNAL,
"TARGET1" DECIMAL EXTERNAL,
"TARGET2" DECIMAL EXTERNAL,
"TARGET1_RRR" DECIMAL EXTERNAL,
"TARGET2_RRR" DECIMAL EXTERNAL,
"STOP_LOSS" DECIMAL EXTERNAL,
"BACKTEST_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"HIGH_52W" DECIMAL EXTERNAL,
"LOW_52W" DECIMAL EXTERNAL,
"ATH" DECIMAL EXTERNAL,
"HIGH_1Y" DECIMAL EXTERNAL,
"HIGH_2Y" DECIMAL EXTERNAL,
"SUPPORT_PRICE" DECIMAL EXTERNAL,
"RESISTANCE_PRICE" DECIMAL EXTERNAL,
"EXIT_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"EXIT_PRICE" DECIMAL EXTERNAL,
"EXIT_REASON" CHAR (30),
"STATUS" CHAR (20),
"CREATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"UPDATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF")
