OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\BHRAMHAPUTRA_TRADES_BKP\BHRAMHAPUTRA_TRADES_DATA_TABLE.ldr'
APPEND
INTO TABLE "BHRAMHAPUTRA_TRADES"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SYMBOL" CHAR (32),
"TRADE_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"BUY_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"BUY_PRICE" DECIMAL EXTERNAL,
"SELL_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"SELL_PRICE" DECIMAL EXTERNAL,
"STOP_LOSS" DECIMAL EXTERNAL,
"STOP_LOSS_PCT" DECIMAL EXTERNAL,
"TARGET1" DECIMAL EXTERNAL,
"TARGET1_PCT" DECIMAL EXTERNAL,
"TARGET2" DECIMAL EXTERNAL,
"TARGET2_PCT" DECIMAL EXTERNAL,
"SUPPORT_S1" DECIMAL EXTERNAL,
"SUPPORT_S2" DECIMAL EXTERNAL,
"RESISTANCE_R1" DECIMAL EXTERNAL,
"RESISTANCE_R2" DECIMAL EXTERNAL,
"JOURNAL" CHAR (4000),
"OUTCOME" CHAR (12),
"CREATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"UPDATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF")
