OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\FYRES_STOCK_TRADING_PNL_CALCULATIONS_BKP\FYRES_STOCK_TRADING_PNL_CALCULATIONS_DATA_TABLE.ldr'
APPEND
INTO TABLE "FYRES_STOCK_TRADING_PNL_CALCULATIONS"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"STOPLOSS" DECIMAL EXTERNAL,
"PROFIT" DECIMAL EXTERNAL,
"PERCENTAGE" DECIMAL EXTERNAL,
"TRADING_DAYS" CHAR (55),
"INVESTED" DECIMAL EXTERNAL,
"NET_PROFIT" DECIMAL EXTERNAL,
"GAIN_LOSS" DECIMAL EXTERNAL,
"PERFORMED" CHAR (3),
"SCRIP_NAME" CHAR (255))
