OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\ASURA_SCAN_DAILY_FACT_BKP\ASURA_SCAN_DAILY_FACT_DATA_TABLE.ldr'
APPEND
INTO TABLE "ASURA_SCAN_DAILY_FACT"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"RUN_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"STOCK" CHAR (50),
"BUYING_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"BUYING_PRICE" DECIMAL EXTERNAL,
"CREATED_TS" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF")
