OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\NIFTY500_MASTER_BKP\NIFTY500_MASTER_DATA_TABLE.ldr'
APPEND
INTO TABLE "NIFTY500_MASTER"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"ID" DECIMAL EXTERNAL,
"SYMBOL" CHAR (50),
"PREVIOUS_CLOSE" DECIMAL EXTERNAL,
"VOLUME" DECIMAL EXTERNAL,
"TRADE_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"CREATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"UPDATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF")
