OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\ASURA_TRADE_BOOK_BKP\ASURA_TRADE_BOOK_DATA_TABLE.ldr'
APPEND
INTO TABLE "ASURA_TRADE_BOOK"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SYMBOL" CHAR (32),
"BUYING_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"SELLING_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"ENTRY_PRICE" DECIMAL EXTERNAL,
"STOP_LOSS" DECIMAL EXTERNAL,
"STOP_LOSS_PCT" DECIMAL EXTERNAL,
"TARGET1" DECIMAL EXTERNAL,
"TARGET1_PCT" DECIMAL EXTERNAL,
"TARGET2" DECIMAL EXTERNAL,
"TARGET2_PCT" DECIMAL EXTERNAL,
"BACKTESTING_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"CREATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"UPDATED_AT" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF")
