OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\DIM_INDEX_MEMBERSHIP_BKP\DIM_INDEX_MEMBERSHIP_DATA_TABLE.ldr'
APPEND
INTO TABLE "DIM_INDEX_MEMBERSHIP"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"INDEX_CODE" CHAR (30),
"SYMBOL_ID" DECIMAL EXTERNAL,
"VALID_FROM" DATE "YYYY-MM-DD HH24:MI:SS",
"VALID_TO" DATE "YYYY-MM-DD HH24:MI:SS",
"EFFECTIVE_FROM" DATE "YYYY-MM-DD HH24:MI:SS",
"EFFECTIVE_TO" DATE "YYYY-MM-DD HH24:MI:SS")
