OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\MARKET_SUMMARY_BKP\MARKET_SUMMARY_DATA_TABLE.ldr'
APPEND
INTO TABLE "MARKET_SUMMARY"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SUMMARY_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"INDEX_NAME" CHAR (50),
"OPEN" DECIMAL EXTERNAL,
"HIGH" DECIMAL EXTERNAL,
"LOW" DECIMAL EXTERNAL,
"CLOSE" DECIMAL EXTERNAL,
"VOLUME" DECIMAL EXTERNAL)
