OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\NIFTY150_SYMBOL_MASTER_BKP\NIFTY150_SYMBOL_MASTER_DATA_TABLE.ldr'
APPEND
INTO TABLE "NIFTY150_SYMBOL_MASTER"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SYMBOL" CHAR (50))
