OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\CVING_NSE_MCAP_PIPELINE_RUNS_BKP\CVING_NSE_MCAP_PIPELINE_RUNS_DATA_TABLE.ldr'
APPEND
INTO TABLE "CVING_NSE_MCAP_PIPELINE_RUNS"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"RUN_ID" CHAR (36),
"TRADE_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"RUN_TYPE" CHAR (20),
"STATUS" CHAR (20),
"REQUEST_JSON" CHAR (4000),
"METRICS_JSON" CHAR (4000),
"MESSAGE" CHAR (4000),
"DOWNLOAD_FILE_PATH" CHAR (1000),
"LOGS_CLOB" CHAR (4000),
"STARTED_TS" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"FINISHED_TS" TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF",
"CREATED_BY" CHAR (128))
