OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\FYRES_BKP\FYRES_DATA_TABLE.ldr'
APPEND
INTO TABLE "FYRES"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"ENTRY_DATE" DATE "YYYY-MM-DD HH24:MI:SS",
"TIME" DATE "YYYY-MM-DD HH24:MI:SS",
"SEGMENT" CHAR (20),
"SYMBOL" CHAR (20),
"TYPE" CHAR (20),
"QUANTITY" DECIMAL EXTERNAL,
"TRADE_PRICE" DECIMAL EXTERNAL,
"TRADE_VALUE" DECIMAL EXTERNAL,
"ORDER_ID" DECIMAL EXTERNAL)
