OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\MARKET_MOVERS_BKP\MARKET_MOVERS_DATA_TABLE.ldr'
APPEND
INTO TABLE "MARKET_MOVERS"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"MOVER_ID" DECIMAL EXTERNAL,
"SYMBOL" CHAR (50),
"MOVER_TYPE" CHAR (20),
"CHANGE_PERCENT" DECIMAL EXTERNAL,
"LTP" DECIMAL EXTERNAL,
"VOLUME" DECIMAL EXTERNAL,
"SUMMARY_DATE" DATE "YYYY-MM-DD HH24:MI:SS")
