OPTIONS (ERRORS=50)
LOAD DATA
INFILE 'E:\DB_BACKUP_SAFETY\EXPORT\NSE_NIFTY_500_STAGING_BKP\NSE_NIFTY_500_STAGING_DATA_TABLE.ldr'
APPEND
INTO TABLE "NSE_NIFTY_500_STAGING"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS (
"SYMBOL" CHAR (50),
"OPEN_PRICE" CHAR (20),
"HIGH_PRICE" CHAR (20),
"LOW_PRICE" CHAR (20),
"PREV_CLOSE_PRICE" CHAR (20),
"LTP" CHAR (20),
"CHANGE_RUPEES" CHAR (20),
"CHANGES_PERCENTAGE" CHAR (20),
"VOLUME_SHARES" CHAR (20),
"VALUE_CRORES" CHAR (20),
"HIGH_52WEEK" CHAR (20),
"LOW_52WEEK" CHAR (20),
"CHANGE_30_DAYS" CHAR (20),
"CHANGES_365_DAYS" CHAR (20),
"TRADING_DATE" CHAR (20))
