SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT Applying post-validation fixes for CVING_APP...

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW V_NSE500_EMA_MONTHLY (
  SYMBOL,
  MONTH_START,
  FIRST_TRADING_DATE,
  LAST_TRADING_DATE,
  LOW,
  HIGH,
  OPEN,
  PRICE_FOR_EMA,
  VOLUME
) AS
SELECT
  SYMBOL,
  MONTH_BUCKET AS MONTH_START,
  MIN(TRADING_DATE) AS FIRST_TRADING_DATE,
  MAX(TRADING_DATE) AS LAST_TRADING_DATE,
  MIN(LOW) AS LOW,
  MAX(HIGH) AS HIGH,
  MIN(OPEN) KEEP (DENSE_RANK FIRST ORDER BY TRADING_DATE) AS OPEN,
  MAX(PREVIOUS_CLOSE) KEEP (DENSE_RANK LAST ORDER BY TRADING_DATE) AS PRICE_FOR_EMA,
  SUM(VOLUME) AS VOLUME
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV
GROUP BY SYMBOL, MONTH_BUCKET;
/

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW V_NSE500_EMA_YEARLY (
  SYMBOL,
  YEAR_START,
  FIRST_TRADING_DATE,
  LAST_TRADING_DATE,
  LOW,
  HIGH,
  OPEN,
  PRICE_FOR_EMA,
  VOLUME
) AS
SELECT
  SYMBOL,
  YEAR_BUCKET AS YEAR_START,
  MIN(TRADING_DATE) AS FIRST_TRADING_DATE,
  MAX(TRADING_DATE) AS LAST_TRADING_DATE,
  MIN(LOW) AS LOW,
  MAX(HIGH) AS HIGH,
  MIN(OPEN) KEEP (DENSE_RANK FIRST ORDER BY TRADING_DATE) AS OPEN,
  MAX(PREVIOUS_CLOSE) KEEP (DENSE_RANK LAST ORDER BY TRADING_DATE) AS PRICE_FOR_EMA,
  SUM(VOLUME) AS VOLUME
FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV
GROUP BY SYMBOL, YEAR_BUCKET;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM user_tables
  WHERE table_name = 'TRADE_BOOK_BUY_SELL_FYRES';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE TRADE_BOOK_BUY_SELL_FYRES (
        TRADE_DATE DATE,
        TRADE_TIME TIMESTAMP,
        SEGMENT VARCHAR2(50),
        SYMBOL VARCHAR2(50),
        TRADE_TYPE VARCHAR2(10),
        QUANTITY NUMBER(18, 6),
        TRADE_PRICE NUMBER(18, 6),
        TRADE_VALUE NUMBER(18, 6),
        PROCESS_STATUS CHAR(1),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      ) TABLESPACE CVING_DATA
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_TRADE_BOOK_BUY_SELL_FYRES_SD ON TRADE_BOOK_BUY_SELL_FYRES (SYMBOL, TRADE_DATE) TABLESPACE CVING_INDEX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER PROCEDURE CALCULATE_TRADE_BOOK COMPILE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

PROMPT Post-validation fixes applied.
