BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY150_MIDCAP" 
   (	"SYMBOL" VARCHAR2(50), 
	"LARGE_INDEX" CHAR(1), 
	"MID_INDEX" CHAR(1), 
	"SMALL_INDEX" CHAR(1)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_N150_SYMBOL" ON "NSE_NIFTY150_MIDCAP" ("SYMBOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY150_MIDCAP" ADD CONSTRAINT "PK_NIFTY150_SYMBOL" PRIMARY KEY ("SYMBOL")
  USING INDEX "IDX_N150_SYMBOL"  ENABLE~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
      RAISE;
    END IF;
END;
/
