BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "FYRES_STOCK_TRADING_PNL_CALCULATIONS" (
    "STOPLOSS" NUMBER(10,2),
    "PROFIT" NUMBER(10,2),
    "PERCENTAGE" NUMBER(10,2),
    "TRADING_DAYS" VARCHAR2(55),
    "INVESTED" NUMBER(10,2),
    "NET_PROFIT" NUMBER(10,2),
    "GAIN_LOSS" NUMBER(10,2),
    "PERFORMED" VARCHAR2(3),
    "SCRIP_NAME" VARCHAR2(255)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
