BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "FYRES_STOCK_TRADING_PNL_AFTER_CALCULATIONS" (
    "SCRIP_NAME" VARCHAR2(255),
    "QUANTITY" NUMBER(10,0),
    "PROFIT" NUMBER(10,2),
    "INVESTED" NUMBER(10,2),
    "NET_PROFIT" NUMBER(10,2),
    "GAIN_LOSS" NUMBER(10,2),
    "PERCENTAGE" VARCHAR2(10),
    "TRADING_DAYS" VARCHAR2(32),
    "PERFORMED" VARCHAR2(3)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
