BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_STRATEGY_PARAMS" (
    "STRATEGY_NAME" VARCHAR2(30) NOT NULL,
    "PARAM_NAME" VARCHAR2(80) NOT NULL,
    "PARAM_VALUE_TEXT" VARCHAR2(4000),
    "PARAM_VALUE_NUMBER" NUMBER(18,6),
    "VALUE_TYPE" VARCHAR2(20) NOT NULL,
    "NOTES" VARCHAR2(400),
    "UPDATED_BY" VARCHAR2(64),
    "UPDATED_AT" TIMESTAMP(6),
    "IS_ACTIVE" CHAR(1) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
