BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "MARKET_MOVERS" (
    "MOVER_ID" NUMBER NOT NULL,
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "MOVER_TYPE" VARCHAR2(20),
    "CHANGE_PERCENT" NUMBER,
    "LTP" NUMBER,
    "VOLUME" NUMBER,
    "SUMMARY_DATE" DATE
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
