BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "DIM_INDEX" (
    "INDEX_CODE" VARCHAR2(30) NOT NULL,
    "INDEX_NAME" VARCHAR2(100)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
