BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_SECTOR_MASTER" 
   (	"SECTOR_CODE" VARCHAR2(30), 
	"SECTOR_NAME" VARCHAR2(100), 
	"INDEX_CODE" VARCHAR2(60), 
	"DISPLAY_ORDER" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX "SYS_C0010120" ON "NSE_SECTOR_MASTER" ("SECTOR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SECTOR_MASTER" MODIFY ("SECTOR_NAME" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SECTOR_MASTER" MODIFY ("INDEX_CODE" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SECTOR_MASTER" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SECTOR_MASTER" ADD PRIMARY KEY ("SECTOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA  ENABLE~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
      RAISE;
    END IF;
END;
/
