BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "DIM_INDEX_MEMBERSHIP" (
    "INDEX_CODE" VARCHAR2(30) NOT NULL,
    "SYMBOL_ID" NUMBER NOT NULL,
    "VALID_FROM" DATE NOT NULL,
    "VALID_TO" DATE,
    "EFFECTIVE_FROM" DATE NOT NULL,
    "EFFECTIVE_TO" DATE
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
