BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_NSE_DELIVERY_HIST" (
    "ID" NUMBER NOT NULL,
    "TRADE_DATE" DATE NOT NULL,
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "SOURCE_NAME" VARCHAR2(50) NOT NULL,
    "SERIES" VARCHAR2(10),
    "SECURITY_NAME" VARCHAR2(300),
    "PREV_CLOSE" NUMBER(24,6),
    "CLOSE_PRICE" NUMBER(24,6),
    "TOTAL_TRADED_QTY" NUMBER(24,6),
    "TURNOVER_LACS" NUMBER(24,6),
    "NO_OF_TRADES" NUMBER(24,6),
    "DELIVERY_QTY" NUMBER(24,6),
    "DELIVERY_PCT" NUMBER(12,6),
    "RESPONSE_PAYLOAD" CLOB,
    "FETCH_STATUS" VARCHAR2(30) NOT NULL,
    "ERROR_MESSAGE" VARCHAR2(2000),
    "FETCH_TS" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" VARCHAR2(128) NOT NULL,
    "UPDATED_TS" TIMESTAMP(6) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
