BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_STRATEGY_AGENT_BACKTESTS" (
    "BACKTEST_ID" VARCHAR2(64) NOT NULL,
    "RUN_ID" VARCHAR2(36) NOT NULL,
    "STRATEGY_NAME" VARCHAR2(30) NOT NULL,
    "SOURCE_NAME" VARCHAR2(30),
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "DIRECTION" VARCHAR2(10) NOT NULL,
    "ENTRY_DATE" DATE NOT NULL,
    "EXIT_DATE" DATE,
    "ENTRY_PRICE" NUMBER(18,4),
    "EXIT_PRICE" NUMBER(18,4),
    "STOP_LOSS" NUMBER(18,4),
    "TARGET1" NUMBER(18,4),
    "TARGET2" NUMBER(18,4),
    "TARGET1_DATE" DATE,
    "TARGET2_DATE" DATE,
    "EXIT_REASON" VARCHAR2(40),
    "RESULT_FLAG" VARCHAR2(10),
    "SUCCESS_FLAG" NUMBER(1,0) NOT NULL,
    "FAIL_FLAG" NUMBER(1,0) NOT NULL,
    "TRADING_DAYS" NUMBER,
    "DAYS_TO_T1" NUMBER,
    "DAYS_TO_T2" NUMBER,
    "RETURN_PCT" NUMBER(12,4),
    "RETURN_RR" NUMBER(12,6),
    "WHY_TRADE" VARCHAR2(400),
    "CREATED_AT" TIMESTAMP(6) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
