BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_NSE_FFMC_PIPELINE_RUNS" (
    "RUN_ID" VARCHAR2(36) NOT NULL,
    "TRADE_DATE" DATE NOT NULL,
    "RUN_TYPE" VARCHAR2(20) NOT NULL,
    "STATUS" VARCHAR2(20) NOT NULL,
    "REQUEST_JSON" CLOB,
    "METRICS_JSON" CLOB,
    "MESSAGE" VARCHAR2(4000),
    "DOWNLOAD_FILE_PATH" VARCHAR2(1000),
    "LOGS_CLOB" CLOB,
    "STARTED_TS" TIMESTAMP(6) NOT NULL,
    "FINISHED_TS" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(128) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
