BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY500_DAILY_RAW_DATA_DEV" 
   (	"SYMBOL" VARCHAR2(50), 
	"OPEN" NUMBER, 
	"HIGH" NUMBER, 
	"LOW" NUMBER, 
	"PREVIOUS_CLOSE" NUMBER, 
	"VOLUME" NUMBER, 
	"TRADING_DATE" DATE, 
	"WEEK_BUCKET" DATE GENERATED ALWAYS AS (TRUNC("TRADING_DATE",'fmiw')) VIRTUAL , 
	"MONTH_BUCKET" DATE GENERATED ALWAYS AS (TRUNC("TRADING_DATE",'fmmm')) VIRTUAL , 
	"YEAR_BUCKET" DATE GENERATED ALWAYS AS (TRUNC("TRADING_DATE",'fmyyyy')) VIRTUAL 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_RAW_SYM_DATE" ON "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ("SYMBOL", "TRADING_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_N500_TDATE" ON "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ("TRADING_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_NSE500_SYM_WEEK" ON "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ("SYMBOL", "WEEK_BUCKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_NSE500_SYM_MONTH" ON "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ("SYMBOL", "MONTH_BUCKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IDX_NSE500_SYM_YEAR" ON "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ("SYMBOL", "YEAR_BUCKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_DEV" MODIFY ("SYMBOL" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_DEV" MODIFY ("TRADING_DATE" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_DEV" ADD CONSTRAINT "PK_NSE_NIFTY500_RAW" PRIMARY KEY ("SYMBOL", "TRADING_DATE")
  USING INDEX "IDX_RAW_SYM_DATE"  ENABLE~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
      RAISE;
    END IF;
END;
/
