BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "ASURA_SCAN_DAILY_FACT" (
    "RUN_DATE" DATE NOT NULL,
    "STOCK" VARCHAR2(50) NOT NULL,
    "BUYING_DATE" DATE NOT NULL,
    "BUYING_PRICE" NUMBER(12,2) NOT NULL,
    "CREATED_TS" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
