BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "BULLISH_BHRAMHAPUTRA" (
    "S_NO" NUMBER,
    "STOCK_NAME" VARCHAR2(120) NOT NULL,
    "PRICE" NUMBER(14,4),
    "BUY_PRICE" NUMBER(14,4),
    "BUY_DATE" DATE NOT NULL,
    "STOP_LOSS" NUMBER(14,4),
    "TARGET1" NUMBER(14,4),
    "TARGET2" NUMBER(14,4),
    "EMA_GT_20" CHAR(1),
    "RSI_GT_30" CHAR(1),
    "MACD_GT_0" CHAR(1),
    "VOLUME_GT_20" CHAR(1),
    "ATR14" NUMBER(14,4),
    "BULLISH" CHAR(1),
    "TREND" VARCHAR2(30),
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
