BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "BHRAMHASTRA_BACKTESTING_DATA" (
    "ID" NUMBER NOT NULL,
    "S_NO" NUMBER,
    "SYMBOL" VARCHAR2(30) NOT NULL,
    "STOCK_NAME" VARCHAR2(200),
    "LTC_DATE" DATE NOT NULL,
    "TRADE_DATE" DATE,
    "FIRST_TRADE_DATE" DATE,
    "CALENDAR_DAYS" NUMBER,
    "TRADING_DAYS" NUMBER,
    "ENTRY_PRICE" NUMBER(18,4),
    "EMA50" NUMBER(18,4),
    "RSI14" NUMBER(10,4),
    "MACD_HIST" NUMBER(18,6),
    "VOLUME" NUMBER(20,2),
    "ATR14" NUMBER(18,4),
    "RISK_AMOUNT" NUMBER(18,4),
    "TARGET1" NUMBER(18,4),
    "TARGET2" NUMBER(18,4),
    "TARGET1_RRR" NUMBER(10,4),
    "TARGET2_RRR" NUMBER(10,4),
    "STOP_LOSS" NUMBER(18,4),
    "BACKTEST_DATE" DATE,
    "HIGH_52W" NUMBER(18,4),
    "LOW_52W" NUMBER(18,4),
    "ATH" NUMBER(18,4),
    "HIGH_1Y" NUMBER(18,4),
    "HIGH_2Y" NUMBER(18,4),
    "SUPPORT_PRICE" NUMBER(18,4),
    "RESISTANCE_PRICE" NUMBER(18,4),
    "EXIT_DATE" DATE,
    "EXIT_PRICE" NUMBER(18,4),
    "EXIT_REASON" VARCHAR2(30),
    "STATUS" VARCHAR2(20),
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
