BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "BHRAMHAPUTRA_TRADES" (
    "SYMBOL" VARCHAR2(32) NOT NULL,
    "TRADE_DATE" DATE NOT NULL,
    "BUY_DATE" DATE,
    "BUY_PRICE" NUMBER(12,2),
    "SELL_DATE" DATE,
    "SELL_PRICE" NUMBER(12,2),
    "STOP_LOSS" NUMBER(12,2),
    "STOP_LOSS_PCT" NUMBER(5,2),
    "TARGET1" NUMBER(12,2),
    "TARGET1_PCT" NUMBER(5,2),
    "TARGET2" NUMBER(12,2),
    "TARGET2_PCT" NUMBER(5,2),
    "SUPPORT_S1" NUMBER(12,2),
    "SUPPORT_S2" NUMBER(12,2),
    "RESISTANCE_R1" NUMBER(12,2),
    "RESISTANCE_R2" NUMBER(12,2),
    "JOURNAL" CLOB,
    "OUTCOME" VARCHAR2(12),
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
