BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NIFTY500_MASTER" (
    "ID" NUMBER NOT NULL,
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "PREVIOUS_CLOSE" NUMBER(18,2) NOT NULL,
    "VOLUME" NUMBER NOT NULL,
    "TRADE_DATE" DATE NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
