BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "LOAD_PROGRESS" (
    "SYMBOL" VARCHAR2(32) NOT NULL,
    "LAST_LOADED_DATE" DATE
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
