BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "ASURA_TRADE_BOOK" (
    "SYMBOL" VARCHAR2(32) NOT NULL,
    "BUYING_DATE" DATE,
    "SELLING_DATE" DATE,
    "ENTRY_PRICE" NUMBER(18,6),
    "STOP_LOSS" NUMBER(18,6),
    "STOP_LOSS_PCT" NUMBER(10,4),
    "TARGET1" NUMBER(18,6),
    "TARGET1_PCT" NUMBER(10,4),
    "TARGET2" NUMBER(18,6),
    "TARGET2_PCT" NUMBER(10,4),
    "BACKTESTING_DATE" DATE,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
