BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY_500_EQUITY_SEGMENT" (
    "SYMBOL" VARCHAR2(100),
    "OPEN_PRICE" NUMBER(38,2),
    "HIGH_PRICE" NUMBER(38,2),
    "LOW_PRICE" NUMBER(38,2),
    "PREV_CLOSE_PRICE" NUMBER(38,2),
    "LTP" NUMBER(38,2),
    "CHANGE_RUPEES" NUMBER(38,2),
    "CHANGES_PERCENTAGE" NUMBER(38,2),
    "VOLUME_SHARES" NUMBER(38,0),
    "VALUE_CRORES" NUMBER(38,2),
    "HIGH_52WEEK" NUMBER(38,2),
    "LOW_52WEEK" NUMBER(38,2),
    "CHANGE_30_DAYS" NUMBER(38,2),
    "CHANGES_365_DAYS" NUMBER(38,2),
    "TRADING_DATE" DATE
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
