BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "MARKET_SUMMARY" (
    "SUMMARY_DATE" DATE NOT NULL,
    "INDEX_NAME" VARCHAR2(50),
    "OPEN" NUMBER,
    "HIGH" NUMBER,
    "LOW" NUMBER,
    "CLOSE" NUMBER,
    "VOLUME" NUMBER
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
