BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY_500_STAGING" (
    "SYMBOL" VARCHAR2(50),
    "OPEN_PRICE" VARCHAR2(20),
    "HIGH_PRICE" VARCHAR2(20),
    "LOW_PRICE" VARCHAR2(20),
    "PREV_CLOSE_PRICE" VARCHAR2(20),
    "LTP" VARCHAR2(20),
    "CHANGE_RUPEES" VARCHAR2(20),
    "CHANGES_PERCENTAGE" VARCHAR2(20),
    "VOLUME_SHARES" VARCHAR2(20),
    "VALUE_CRORES" VARCHAR2(20),
    "HIGH_52WEEK" VARCHAR2(20),
    "LOW_52WEEK" VARCHAR2(20),
    "CHANGE_30_DAYS" VARCHAR2(20),
    "CHANGES_365_DAYS" VARCHAR2(20),
    "TRADING_DATE" VARCHAR2(20)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
