BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_SYMBOL_INDICATORS_LATEST" 
   (	"SYMBOL" VARCHAR2(50), 
	"LTC_DATE" DATE, 
	"SMA20" NUMBER(12,4), 
	"SMA50" NUMBER(12,4), 
	"SMA100" NUMBER(12,4), 
	"RSI50" NUMBER(10,4), 
	"RSI55" NUMBER(10,4), 
	"CLOSE_PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX "NSE_SYM_IND_LATEST_PK" ON "NSE_SYMBOL_INDICATORS_LATEST" ("SYMBOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "NSE_SYM_IND_LATEST_IDX1" ON "NSE_SYMBOL_INDICATORS_LATEST" ("LTC_DATE", "SYMBOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SYMBOL_INDICATORS_LATEST" MODIFY ("SYMBOL" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SYMBOL_INDICATORS_LATEST" MODIFY ("LTC_DATE" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_SYMBOL_INDICATORS_LATEST" ADD CONSTRAINT "NSE_SYM_IND_LATEST_PK" PRIMARY KEY ("SYMBOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA  ENABLE~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
      RAISE;
    END IF;
END;
/
