BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" 
   (	"S_NO" NUMBER, 
	"SYMBOL" VARCHAR2(50), 
	"OPEN" NUMBER, 
	"HIGH" NUMBER, 
	"LOW" NUMBER, 
	"PREVIOUS_CLOSE" NUMBER, 
	"LTP" NUMBER, 
	"CHANGE_POINTS" NUMBER, 
	"CHANGE_PERCENTAGE" NUMBER, 
	"VOLUME" NUMBER, 
	"HIGH_52WEEK" NUMBER, 
	"LOW_52WEEK" NUMBER, 
	"PERCENTAGE_CHANGE_30_DAYS" NUMBER, 
	"PERCENTAGE_CHANGE_365_DAYS" NUMBER, 
	"TRADING_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX "IX_RAW_DATE" ON "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" ("TRADING_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX "PK_NSE_NIFTY500" ON "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" ("SYMBOL", "TRADING_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" MODIFY ("SYMBOL" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" MODIFY ("TRADING_DATE" NOT NULL ENABLE)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~ALTER TABLE "NSE_NIFTY500_DAILY_RAW_DATA_ORACLE" ADD CONSTRAINT "PK_NSE_NIFTY500" PRIMARY KEY ("SYMBOL", "TRADING_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE CVING_DATA  ENABLE~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
      RAISE;
    END IF;
END;
/
