BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NIFTY_INDEX_CONSTITUENTS" (
    "INDEX_NAME" VARCHAR2(30) NOT NULL,
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "EFFECTIVE_FROM" DATE NOT NULL,
    "EFFECTIVE_TO" DATE
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
