BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "ETL_WATERMARK" (
    "PROCESS_NAME" VARCHAR2(64) NOT NULL,
    "LAST_TRADING_DATE" DATE,
    "LAST_RUN_TS" TIMESTAMP(6)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
