BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "NSE_NIFTY_MIDSMALL_FINANCIAL_SERVICES_STAGING" (
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "SECTOR" VARCHAR2(100) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
