BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "API_QUOTA_LOG" (
    "RUN_TS" TIMESTAMP(6),
    "SYMBOL" VARCHAR2(32),
    "FROM_DATE" DATE,
    "TO_DATE" DATE,
    "ROWS_FETCHED" NUMBER
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
