BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_STRATEGY_AGENT_RUNS" (
    "RUN_ID" VARCHAR2(36) NOT NULL,
    "STRATEGY_NAME" VARCHAR2(30) NOT NULL,
    "RUN_SOURCE" VARCHAR2(20),
    "RUN_AT" TIMESTAMP(6) NOT NULL,
    "STATUS" VARCHAR2(20) NOT NULL,
    "APPLIED_FLAG" CHAR(1) NOT NULL,
    "BASELINE_SUCCESS_RATE" NUMBER(9,4),
    "CANDIDATE_SUCCESS_RATE" NUMBER(9,4),
    "BASELINE_FAIL_RATE" NUMBER(9,4),
    "CANDIDATE_FAIL_RATE" NUMBER(9,4),
    "BASELINE_TOTAL_TRADES" NUMBER,
    "CANDIDATE_TOTAL_TRADES" NUMBER,
    "BASELINE_AVG_RR" NUMBER(12,6),
    "CANDIDATE_AVG_RR" NUMBER(12,6),
    "PARAMS_JSON" CLOB,
    "NOTES" CLOB
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
