BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "FYRES_TRADING_PNL" (
    "TRANSACTION_TYPE" VARCHAR2(255),
    "COMPANY_CODE" VARCHAR2(255),
    "ISIN" VARCHAR2(255),
    "SCRIP_SYMBOL" VARCHAR2(255),
    "SCRIP_NAME" VARCHAR2(255),
    "BUY_DATE" DATE,
    "BUY_QUANTITY" NUMBER(10,2),
    "BUY_RATE" NUMBER(10,2),
    "SELL_DATE" DATE,
    "SELL_QUANTITY" NUMBER(10,2),
    "SELL_RATE" NUMBER(10,2),
    "PROFIT_LOSS_AMOUNT" NUMBER(10,2),
    "AVAILABLE_QTY" NUMBER(10,2),
    "LAST_TRADED_PRICE" NUMBER(10,2),
    "DP_EXPENSE_DETAILS" NUMBER(10,2),
    "STOCK_EXCHANGE" VARCHAR2(255)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
