BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "CVING_NSE_FFMC_HIST" (
    "ID" NUMBER NOT NULL,
    "TRADE_DATE" DATE NOT NULL,
    "SYMBOL" VARCHAR2(50) NOT NULL,
    "SOURCE_NAME" VARCHAR2(50) NOT NULL,
    "SERIES" VARCHAR2(10),
    "SECURITY_NAME" VARCHAR2(300),
    "RAW_TOTAL_MCAP" NUMBER(24,6),
    "RAW_TOTAL_MCAP_UNIT" VARCHAR2(30),
    "TOTAL_MCAP_CR" NUMBER(24,6),
    "RAW_FFMC" NUMBER(24,6),
    "RAW_FFMC_UNIT" VARCHAR2(30),
    "FFMC_CR" NUMBER(24,6),
    "RESPONSE_PAYLOAD" CLOB,
    "FETCH_STATUS" VARCHAR2(30) NOT NULL,
    "ERROR_MESSAGE" VARCHAR2(2000),
    "FETCH_TS" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" VARCHAR2(128) NOT NULL,
    "UPDATED_TS" TIMESTAMP(6) NOT NULL
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
