BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "FYRES" (
    "ENTRY_DATE" DATE,
    "TIME" DATE,
    "SEGMENT" VARCHAR2(20),
    "SYMBOL" VARCHAR2(20),
    "TYPE" VARCHAR2(20),
    "QUANTITY" NUMBER(10,0),
    "TRADE_PRICE" NUMBER(10,0),
    "TRADE_VALUE" NUMBER(10,0),
    "ORDER_ID" NUMBER(20,0)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
