BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE "ASURA_BULLISH_TREND_STRATEGY_TESTING" (
    "S_NO" NUMBER,
    "STOCK" VARCHAR2(50) NOT NULL,
    "BUYING_PRICE" NUMBER(10,2),
    "BUYING_DATE" DATE NOT NULL,
    "SELLING_PRICE" NUMBER(10,2),
    "SELLING_DATE" DATE,
    "SIGNAL_SCORE" NUMBER(10,2),
    "VOLUME_RATIO20" NUMBER(10,2),
    "EMA20" NUMBER(10,2),
    "EMA50" NUMBER(10,2),
    "EMA100" NUMBER(10,2),
    "EMA200" NUMBER(10,2),
    "RSI14" NUMBER(10,2),
    "MACD_HIST" NUMBER(10,4),
    "VOLUME" NUMBER(18,2),
    "ATR14" NUMBER(10,2),
    "ADX14" NUMBER(10,2),
    "SUPPORT_PRICE" NUMBER(10,2),
    "RESISTANCE_PRICE" NUMBER(10,2),
    "TREND_DIRECTION" VARCHAR2(20),
    "EMA_STACK" VARCHAR2(20),
    "SUPPORT_STRENGTH" NUMBER(10,2),
    "RESISTANCE_STRENGTH" NUMBER(10,2),
    "LEVEL_SCORE" NUMBER(10,2),
    "BREAKOUT_FLAG" VARCHAR2(20),
    "RETEST_READY" NUMBER(1,0),
    "SETUP_TYPE" VARCHAR2(20),
    "STATUS" VARCHAR2(40),
    "BT_DATE" DATE,
    "ENTRY_PRICE" NUMBER(10,2),
    "STOP_LOSS" NUMBER(10,2),
    "TARGET1" NUMBER(10,2),
    "TARGET2" NUMBER(10,2),
    "RR_1" NUMBER(10,2),
    "RR_2" NUMBER(10,2)
)~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/
