--------------------------------------------------------
--  Backup generated - 2026-03-29 15:08:45
--------------------------------------------------------
--  Source owner: SYSTEM
--  Source container: CDB$ROOT
--  Source object type: VIEW
--  Source object name: V_NSE500_EMA_YEARLY

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_NSE500_EMA_YEARLY" ("SYMBOL", "YEAR_START", "FIRST_TRADING_DATE", "LAST_TRADING_DATE", "LOW", "HIGH", "OPEN", "PRICE_FOR_EMA", "VOLUME") AS
  SELECT
    SYMBOL,
    YEAR_BUCKET      AS YEAR_START,
    MIN(TRADING_DATE) AS FIRST_TRADING_DATE,
    MAX(TRADING_DATE) AS LAST_TRADING_DATE,

    MIN(LOW)  AS LOW,
    MAX(HIGH) AS HIGH,
    MIN(OPEN) KEEP (DENSE_RANK FIRST ORDER BY TRADING_DATE) AS OPEN,
    MAX(PREVIOUS_CLOSE) KEEP (DENSE_RANK LAST ORDER BY TRADING_DATE) AS PRICE_FOR_EMA,

    SUM(VOLUME) AS VOLUME
FROM
    NSE_NIFTY500_DAILY_RAW_DATA_DEV
GROUP BY
    SYMBOL,
    YEAR_BUCKET;
