--------------------------------------------------------
--  Backup generated - 2026-03-29 15:03:17
--------------------------------------------------------
--  Source owner: SYSTEM
--  Source container: CDB$ROOT
--  Source object type: VIEW
--  Source object name: NSE_NIFTY500_DAILY_RAW_DATA_VIEW

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "NSE_NIFTY500_DAILY_RAW_DATA_VIEW" ("S_NO", "SYMBOL", "OPEN", "HIGH", "LOW", "PREVIOUS_CLOSE", "LTP", "CHANGE_POINTS", "CHANGE_PERCENTAGE", "VOLUME", "HIGH_52WEEK", "LOW_52WEEK", "PERCENTAGE_CHANGE_30_DAYS", "PERCENTAGE_CHANGE_365_DAYS", "TRADING_DATE") AS
  SELECT "S_NO","SYMBOL","OPEN","HIGH","LOW","PREVIOUS_CLOSE","LTP","CHANGE_POINTS","CHANGE_PERCENTAGE","VOLUME","HIGH_52WEEK","LOW_52WEEK","PERCENTAGE_CHANGE_30_DAYS","PERCENTAGE_CHANGE_365_DAYS","TRADING_DATE" FROM NSE_NIFTY500_DAILY_RAW_DATA_ORACLE;
