--------------------------------------------------------
--  Backup generated - 2026-03-29 15:08:57
--------------------------------------------------------
--  Source owner: SYSTEM
--  Source container: CDB$ROOT
--  Source object type: VIEW
--  Source object name: V_NSE500_WEEKLY_6M

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "V_NSE500_WEEKLY_6M" ("SYMBOL", "WEEK_START", "FIRST_DAY", "LAST_DAY", "LOW", "HIGH", "VOLUME", "PRICE") AS
  SELECT
    SYMBOL,
    WEEK_BUCKET AS WEEK_START,
    MIN(TRADING_DATE) KEEP (DENSE_RANK FIRST ORDER BY TRADING_DATE) AS FIRST_DAY,
    MAX(TRADING_DATE) KEEP (DENSE_RANK LAST ORDER BY TRADING_DATE) AS LAST_DAY,
    MIN(LOW) AS LOW,
    MAX(HIGH) AS HIGH,
    SUM(VOLUME) AS VOLUME,
    MAX(PREVIOUS_CLOSE) KEEP (DENSE_RANK LAST ORDER BY TRADING_DATE) AS PRICE
FROM
    NSE_NIFTY500_DAILY_RAW_DATA_DEV
WHERE
    TRADING_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -6)
GROUP BY
    SYMBOL,
    WEEK_BUCKET;
