SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
SET ECHO OFF
SET TERMOUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
CONNECT CVING_APP/"Rambabu@1260"@//127.0.0.1:1521/cvingpdb.local
@C:\Users\admin\Documents\CvingTrade25X\CvingTrade25X\db\migration\_generated\table_nse_nifty_oil_and_gas_staging_NSE_NIFTY_OIL_AND_GAS_STAGING_DDL.sql
EXIT
