SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
SET ECHO OFF
SET TERMOUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
CONNECT CVING_APP/"Rambabu@1260"@//127.0.0.1:1521/cvingpdb.local
@C:\Users\admin\Documents\CvingTrade25X\CvingTrade25X\db\migration\_generated\procedure_procedure_pr_sync_nse_symbol_sector_map_from_staging_PROCEDURE_PR_SYNC_NSE_SYMBOL_SECTOR_MAP_FROM_STAGING_DDL.sql
EXIT
