PROMPT Rolling back NSE_SECTOR_HIERARCHY_MASTER objects

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_NSE_SECTOR_HIERARCHY_ACTIVE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NSE_SECTOR_HIERARCHY_MASTER CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
