-- Support & Resistance acceleration
-- Run inside the Oracle schema that owns NSE_NIFTY500_DAILY_RAW_DATA_DEV.
CREATE INDEX IDX_NSE500_RAW_SYMBOL_TRADE_DATE
  ON NSE_NIFTY500_DAILY_RAW_DATA_DEV (SYMBOL, TRADING_DATE DESC);

CREATE INDEX IDX_NSE500_RAW_SYMBOL_PREV_CLOSE
  ON NSE_NIFTY500_DAILY_RAW_DATA_DEV (SYMBOL, PREVIOUS_CLOSE);
