PROMPT Sector hierarchy validation checks

SELECT COUNT(*) AS total_active_rows
FROM NSE_SECTOR_HIERARCHY_MASTER
WHERE IS_ACTIVE = 'Y';

SELECT PARENT_SECTOR, COUNT(DISTINCT SYMBOL) AS stock_count
FROM NSE_SECTOR_HIERARCHY_MASTER
WHERE IS_ACTIVE = 'Y'
GROUP BY PARENT_SECTOR
ORDER BY stock_count DESC;

SELECT PARENT_SECTOR, INDUSTRY_SECTOR, COUNT(DISTINCT SYMBOL) AS stock_count
FROM NSE_SECTOR_HIERARCHY_MASTER
WHERE IS_ACTIVE = 'Y'
GROUP BY PARENT_SECTOR, INDUSTRY_SECTOR
ORDER BY PARENT_SECTOR, stock_count DESC;

SELECT
    PARENT_SECTOR,
    INDUSTRY_SECTOR,
    SUB_SECTOR,
    COUNT(DISTINCT SYMBOL) AS stock_count
FROM NSE_SECTOR_HIERARCHY_MASTER
WHERE IS_ACTIVE = 'Y'
GROUP BY PARENT_SECTOR, INDUSTRY_SECTOR, SUB_SECTOR
ORDER BY PARENT_SECTOR, INDUSTRY_SECTOR, stock_count DESC;

SELECT
    PARENT_SECTOR,
    INDUSTRY_SECTOR,
    SUB_SECTOR,
    SYMBOL,
    EXCHANGE,
    COUNT(*) AS duplicate_count
FROM NSE_SECTOR_HIERARCHY_MASTER
GROUP BY
    PARENT_SECTOR,
    INDUSTRY_SECTOR,
    SUB_SECTOR,
    SYMBOL,
    EXCHANGE
HAVING COUNT(*) > 1;

SELECT DISTINCT h.SYMBOL
FROM NSE_SECTOR_HIERARCHY_MASTER h
WHERE h.IS_ACTIVE = 'Y'
  AND NOT EXISTS (
      SELECT 1
      FROM NSE_NIFTY500_DAILY_RAW_DATA_DEV d
      WHERE UPPER(TRIM(d.SYMBOL)) = UPPER(TRIM(h.SYMBOL))
  )
ORDER BY h.SYMBOL;

SELECT
    INDUSTRY_SECTOR,
    SUB_SECTOR,
    COUNT(DISTINCT SYMBOL) AS stock_count
FROM NSE_SECTOR_HIERARCHY_MASTER
WHERE PARENT_SECTOR = 'Healthcare'
  AND IS_ACTIVE = 'Y'
GROUP BY INDUSTRY_SECTOR, SUB_SECTOR
ORDER BY INDUSTRY_SECTOR, SUB_SECTOR;
