import sys
from backend.db import get_oracle_connection

def run_script():
    conn = get_oracle_connection()
    cursor = conn.cursor()
    
    merge_master = """
    MERGE INTO NSE_SECTOR_MASTER tgt
    USING (
        SELECT 'AUTO_COMPONENTS_EQUIPMENTS' AS sector_code, 'Auto Components & Equipments' AS sector_name, 'AUTO_COMPONENTS_EQUIPMENTS' AS index_code, 99 AS display_order FROM dual
    ) src
    ON (tgt.SECTOR_CODE = src.sector_code)
    WHEN NOT MATCHED THEN INSERT (SECTOR_CODE, SECTOR_NAME, INDEX_CODE, DISPLAY_ORDER) VALUES (src.sector_code, src.sector_name, src.index_code, src.display_order)
    WHEN MATCHED THEN UPDATE SET tgt.SECTOR_NAME = src.sector_name, tgt.INDEX_CODE = src.index_code
    """
    
    merge_sql = """
    MERGE INTO NSE_SYMBOL_SECTOR_MAP tgt
    USING (
        SELECT 'ACGL' AS symbol, 'AUTO_COMPONENTS_EQUIPMENTS' AS sector_code FROM dual UNION ALL
        SELECT 'ALICON', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'AMARAJABAT', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'APOLLOTYRE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ARE&M', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ASAHIINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ASAL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ASKAUTOLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'AUTOAXLES', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BALKRISIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BANCOINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BELRISE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BHARATFORG', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BHARATSE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'BOSCHLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'CARRARO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'CEATLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'CIEINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'CRAFTSMAN', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'DIVGIITTS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ENDURANCE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ENKEIWHEL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'EXIDEIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'FIEMIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'FMGOETZE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'FRONTSP', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'GABRIEL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'GNA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'GOODYEAR', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'HAPPYFORGE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'HINDCOMPOS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'HITECHGEAR', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'IGARASHI', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'IMPAL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'INDNIPPON', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'JAMNAAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'JAYBARMARU', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'JBMA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'JKTYRE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'JTEKTINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'KINETICENG', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'KROSS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'LGBBROSLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'LGBROSLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'LUMAXIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'LUMAXTECH', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MANDEEP', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MENONBE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MINDACORP', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MMFL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MOTHERSON', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MRF', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MSUMI', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MUNJALAU', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'MUNJALSHOW', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'NDRAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'NELCAST', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'NRBBEARING', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'OBSCP', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'OMAXAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PAVNAIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PPAP', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PRADPME', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PRECAM', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PRECISION', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PRICOLLTD', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'PRITIKAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RACLGEAR', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RAJRATAN', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RBL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'REMSONSIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RICOAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RKFORGE', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'RML', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ROLEXRINGS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SANDHAR', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SANSERA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SCHAEFFLER', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SEDEMAC', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SEKURITIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SHARDAMOTR', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SHRIPISTON', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SJS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SKFINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SONACOMS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SSWL', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'STERTOOLS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'STUDDS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SUBROS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SUNCLAY', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SUNDRMBRAK', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SUNDRMFAST', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'SUPRAJIT', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TALBROAUTO', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TENNIND', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TIINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TIMKEN', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TOLINS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'TVSSRICHAK', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'UNIPARTS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'UNOMINDA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'VARROC', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'VELJAN', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'WHEELS', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ZFCVINDIA', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual UNION ALL
        SELECT 'ZFSTEERING', 'AUTO_COMPONENTS_EQUIPMENTS' FROM dual
    ) src
    ON (UPPER(TRIM(tgt.SYMBOL)) = src.symbol)
    WHEN MATCHED THEN UPDATE SET
        tgt.SECTOR_CODE = src.sector_code
    WHERE NVL(UPPER(TRIM(tgt.SECTOR_CODE)), '~') <> src.sector_code
    WHEN NOT MATCHED THEN
        INSERT (SYMBOL, SECTOR_CODE)
        VALUES (src.symbol, src.sector_code)
    """
    
    try:
        cursor.execute(merge_master)
        print("Master seeded.")
    except Exception as e:
        print(f"Error master: {e}")

    try:
        cursor.execute(merge_sql)
        print(f"Merged {cursor.rowcount} rows into map.")
    except Exception as e:
        print(f"Error merging map: {e}")

    seed_sql = """
    MERGE INTO NSE_NIFTY_AUTO_COMPONENTS_EQUIPMENTS_STAGING tgt
    USING (
        SELECT symbol FROM NSE_SYMBOL_SECTOR_MAP WHERE sector_code = 'AUTO_COMPONENTS_EQUIPMENTS'
    ) src
    ON (tgt.SYMBOL = src.symbol)
    WHEN NOT MATCHED THEN INSERT (SYMBOL) VALUES (src.symbol)
    """
    try:
        cursor.execute(seed_sql)
        print(f"Seeded staging table.")
    except Exception as e:
        print(f"Error seeding staging table: {e}")

    conn.commit()
    conn.close()
    print("Done")

if __name__ == '__main__':
    run_script()
