-- Validate Corporate Actions candidate view
-- View:
--   V_CORP_ACTION_CANDIDATES

SET PAGESIZE 200
SET LINESIZE 260

COLUMN SYMBOL FORMAT A20
COLUMN POSSIBLE_ACTIONS FORMAT A40
COLUMN DETECTION_BUCKET FORMAT A12

PROMPT === Total Candidates ===
SELECT COUNT(*) AS TOTAL_CANDIDATES
FROM V_CORP_ACTION_CANDIDATES;

PROMPT === Candidates With Drop >= 50 ===
SELECT COUNT(*) AS TOTAL_CANDIDATES_DROP_GE_50
FROM V_CORP_ACTION_CANDIDATES
WHERE DROP_PCT >= 50;

PROMPT === Top 100 Most Recent / Highest Drop Candidates ===
SELECT
  SYMBOL,
  TO_CHAR(PREV_TRADING_DATE, 'YYYY-MM-DD') AS PREV_TRADING_DATE,
  TO_CHAR(TRADING_DATE, 'YYYY-MM-DD') AS TRADING_DATE,
  PREV_PRICE,
  PRICE,
  DROP_PCT,
  ACTUAL_FACTOR,
  POSSIBLE_ACTIONS,
  EXPECTED_DROP_PCT,
  CONFIDENCE_SCORE,
  DETECTION_BUCKET
FROM V_CORP_ACTION_CANDIDATES
ORDER BY TRADING_DATE DESC, DROP_PCT DESC
FETCH FIRST 100 ROWS ONLY;

PROMPT === Symbol-wise Candidate Count ===
SELECT
  SYMBOL,
  COUNT(*) AS CANDIDATE_COUNT
FROM V_CORP_ACTION_CANDIDATES
GROUP BY SYMBOL
ORDER BY CANDIDATE_COUNT DESC, SYMBOL ASC;

PROMPT === Possible Actions Summary ===
SELECT
  POSSIBLE_ACTIONS,
  COUNT(*) AS CANDIDATE_COUNT
FROM V_CORP_ACTION_CANDIDATES
GROUP BY POSSIBLE_ACTIONS
ORDER BY CANDIDATE_COUNT DESC, POSSIBLE_ACTIONS ASC;
