/*
  CvingTrade25X unified technical score/trend storage.
  Additive only: this script does not modify STOCK_EOD_HISTORY or
  NSE_NIFTY500_DAILY_RAW_DATA_DEV.
*/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TECHNICAL_SCORE_CONFIG (
      CONFIG_KEY      VARCHAR2(100) NOT NULL,
      CONFIG_VALUE    VARCHAR2(500) NOT NULL,
      CONFIG_GROUP    VARCHAR2(100),
      DESCRIPTION     VARCHAR2(1000),
      IS_ACTIVE       CHAR(1) DEFAULT 'Y' NOT NULL,
      CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_TECH_SCORE_CONFIG PRIMARY KEY (CONFIG_KEY),
      CONSTRAINT CK_TECH_SCORE_CONFIG_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TECHNICAL_SCORE_LATEST (
      SYMBOL                    VARCHAR2(50) NOT NULL,
      TRADING_DATE              DATE NOT NULL,
      PRICE                     NUMBER(18,4),
      OPEN_PRICE                NUMBER(18,4),
      HIGH_PRICE                NUMBER(18,4),
      LOW_PRICE                 NUMBER(18,4),
      CLOSE_PRICE               NUMBER(18,4),
      VOLUME                    NUMBER(20,2),
      TREND                     VARCHAR2(50),
      TREND_SORT                NUMBER(5),
      TREND_DECISION_REASON     VARCHAR2(500),
      TREND_SOURCE              VARCHAR2(100),
      SCORE                     NUMBER(5,2),
      SCORE_SORT                NUMBER(5,2),
      SCORE_GRADE               VARCHAR2(5),
      SCORE_SOURCE              VARCHAR2(100),
      SCORE_BREAKDOWN_JSON      CLOB,
      EMA20                     NUMBER(18,4),
      EMA50                     NUMBER(18,4),
      EMA100                    NUMBER(18,4),
      EMA200                    NUMBER(18,4),
      EMA20_SLOPE_PCT           NUMBER(12,6),
      EMA50_SLOPE_PCT           NUMBER(12,6),
      RSI14                     NUMBER(12,6),
      MACD_HIST                 NUMBER(18,6),
      MACD_HIST_SLOPE           NUMBER(18,6),
      ADX14                     NUMBER(12,6),
      ADX14_SLOPE               NUMBER(12,6),
      PLUS_DI14                 NUMBER(12,6),
      MINUS_DI14                NUMBER(12,6),
      ATR14                     NUMBER(18,6),
      VOLUME_RATIO_20           NUMBER(18,6),
      DELIVERY_PCT              NUMBER(12,6),
      DELIVERY_REL_20           NUMBER(18,6),
      DELIVERABLE_VALUE         NUMBER(24,6),
      DELIVERABLE_VALUE_REL_20  NUMBER(18,6),
      ATH                       NUMBER(18,4),
      HIGH_52W                  NUMBER(18,4),
      LOW_52W                   NUMBER(18,4),
      SUPPORT_LEVEL             NUMBER(18,4),
      RESISTANCE_LEVEL          NUMBER(18,4),
      DIST_TO_SUPPORT_PCT       NUMBER(12,6),
      DIST_TO_RESISTANCE_PCT    NUMBER(12,6),
      BREAKOUT_FLAG             VARCHAR2(30),
      BREAKDOWN_FLAG            VARCHAR2(30),
      CLOSE_LOCATION_PCT        NUMBER(12,6),
      RISK_FLAGS_JSON           CLOB,
      MISSING_INPUTS_JSON       CLOB,
      CREATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_TECH_SCORE_LATEST PRIMARY KEY (SYMBOL, TRADING_DATE),
      CONSTRAINT CK_TECH_SCORE_LATEST_RANGE CHECK (SCORE IS NULL OR SCORE BETWEEN 0 AND 100),
      CONSTRAINT CK_TECH_SCORE_LATEST_TREND CHECK (
        TREND IS NULL OR TREND IN (
          'Strong Uptrend',
          'Uptrend',
          'Pullback in Uptrend',
          'Sideways',
          'Consolidation',
          'Possible Reversal',
          'Downtrend',
          'Unknown / Insufficient Data'
        )
      ),
      CONSTRAINT CK_TECH_SCORE_LATEST_BREAKDOWN CHECK (SCORE_BREAKDOWN_JSON IS JSON),
      CONSTRAINT CK_TECH_SCORE_LATEST_RISK CHECK (RISK_FLAGS_JSON IS JSON),
      CONSTRAINT CK_TECH_SCORE_LATEST_MISSING CHECK (MISSING_INPUTS_JSON IS JSON)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TECHNICAL_SCORE_HISTORY (
      SYMBOL                    VARCHAR2(50) NOT NULL,
      TRADING_DATE              DATE NOT NULL,
      RUN_ID                    VARCHAR2(100) NOT NULL,
      TREND                     VARCHAR2(50),
      TREND_SORT                NUMBER(5),
      TREND_DECISION_REASON     VARCHAR2(500),
      TREND_SOURCE              VARCHAR2(100),
      SCORE                     NUMBER(5,2),
      SCORE_SORT                NUMBER(5,2),
      SCORE_GRADE               VARCHAR2(5),
      SCORE_SOURCE              VARCHAR2(100),
      SCORE_BREAKDOWN_JSON      CLOB,
      RISK_FLAGS_JSON           CLOB,
      MISSING_INPUTS_JSON       CLOB,
      CREATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_TECH_SCORE_HISTORY PRIMARY KEY (SYMBOL, TRADING_DATE, RUN_ID),
      CONSTRAINT CK_TECH_SCORE_HIST_RANGE CHECK (SCORE IS NULL OR SCORE BETWEEN 0 AND 100),
      CONSTRAINT CK_TECH_SCORE_HIST_BREAKDOWN CHECK (SCORE_BREAKDOWN_JSON IS JSON),
      CONSTRAINT CK_TECH_SCORE_HIST_RISK CHECK (RISK_FLAGS_JSON IS JSON),
      CONSTRAINT CK_TECH_SCORE_HIST_MISSING CHECK (MISSING_INPUTS_JSON IS JSON)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_TECH_SCORE_LATEST_DATE ON TECHNICAL_SCORE_LATEST (TRADING_DATE DESC)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_TECH_SCORE_LATEST_SCORE ON TECHNICAL_SCORE_LATEST (SCORE_SORT DESC, TREND_SORT ASC)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_TECH_SCORE_LATEST_TREND ON TECHNICAL_SCORE_LATEST (TREND, TREND_SORT)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

MERGE INTO TECHNICAL_SCORE_CONFIG tgt
USING (
  SELECT 'near_high_pct' CONFIG_KEY, '5' CONFIG_VALUE, 'TREND' CONFIG_GROUP, 'Near ATH or 52W high threshold percent.' DESCRIPTION FROM dual UNION ALL
  SELECT 'near_low_pct', '5', 'TREND', 'Near 52W low threshold percent.' FROM dual UNION ALL
  SELECT 'near_level_pct', '2', 'STRUCTURE', 'Near support/resistance threshold percent.' FROM dual UNION ALL
  SELECT 'breakout_buffer_pct', '0.25', 'STRUCTURE', 'Resistance breakout buffer percent.' FROM dual UNION ALL
  SELECT 'breakdown_buffer_pct', '0.25', 'STRUCTURE', 'Support breakdown buffer percent.' FROM dual UNION ALL
  SELECT 'ema20_overextension_pct', '8', 'RISK', 'Distance above EMA20 risk threshold.' FROM dual UNION ALL
  SELECT 'atr_overextension_multiple', '2.5', 'RISK', 'ATR multiple above EMA20 risk threshold.' FROM dual UNION ALL
  SELECT 'low_volume_ratio20', '0.7', 'RISK', 'Low liquidity volume ratio threshold.' FROM dual
) src
ON (tgt.CONFIG_KEY = src.CONFIG_KEY)
WHEN MATCHED THEN UPDATE SET
  tgt.CONFIG_VALUE = src.CONFIG_VALUE,
  tgt.CONFIG_GROUP = src.CONFIG_GROUP,
  tgt.DESCRIPTION = src.DESCRIPTION,
  tgt.IS_ACTIVE = 'Y',
  tgt.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_ACTIVE
) VALUES (
  src.CONFIG_KEY, src.CONFIG_VALUE, src.CONFIG_GROUP, src.DESCRIPTION, 'Y'
);

CREATE OR REPLACE VIEW VW_TECHNICAL_SCORE_LATEST AS
SELECT
  SYMBOL,
  TRADING_DATE,
  PRICE,
  CLOSE_PRICE,
  VOLUME,
  TREND,
  TREND_SORT,
  TREND_DECISION_REASON,
  TREND_SOURCE,
  SCORE,
  SCORE_SORT,
  SCORE_GRADE,
  SCORE_SOURCE,
  SCORE_BREAKDOWN_JSON,
  EMA20,
  EMA50,
  EMA100,
  EMA200,
  RSI14,
  MACD_HIST,
  ADX14,
  VOLUME_RATIO_20,
  DELIVERY_REL_20,
  ATH,
  HIGH_52W,
  LOW_52W,
  SUPPORT_LEVEL,
  RESISTANCE_LEVEL,
  RISK_FLAGS_JSON,
  MISSING_INPUTS_JSON,
  CREATED_AT,
  UPDATED_AT
FROM TECHNICAL_SCORE_LATEST;

COMMIT;
