/*
  Rollback for unified technical score objects.
  Run only after confirming TECHNICAL_SCORE_* data is no longer needed.
  This does not touch STOCK_EOD_HISTORY or NSE_NIFTY500_DAILY_RAW_DATA_DEV.
*/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_TECHNICAL_SCORE_LATEST';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-942) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TECHNICAL_SCORE_HISTORY PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-942) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TECHNICAL_SCORE_LATEST PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-942) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TECHNICAL_SCORE_CONFIG PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-942) THEN RAISE; END IF;
END;
/
