/*
  Validation queries for the unified technical score engine.
*/

-- 1. Duplicate guard: should return zero rows.
SELECT SYMBOL, TRADING_DATE, COUNT(*) AS ROW_COUNT
FROM TECHNICAL_SCORE_LATEST
GROUP BY SYMBOL, TRADING_DATE
HAVING COUNT(*) > 1;

-- 2. Latest rows with missing score or trend: should return zero rows after a full run.
SELECT SYMBOL, TRADING_DATE, SCORE, TREND
FROM TECHNICAL_SCORE_LATEST
WHERE SCORE IS NULL OR TREND IS NULL;

-- 3. Downtrend cap: should return zero rows.
SELECT SYMBOL, TRADING_DATE, SCORE, TREND
FROM TECHNICAL_SCORE_LATEST
WHERE TREND = 'Downtrend'
  AND SCORE > 30;

-- 4. Consolidation cap: should return zero rows.
SELECT SYMBOL, TRADING_DATE, SCORE, TREND
FROM TECHNICAL_SCORE_LATEST
WHERE TREND = 'Consolidation'
  AND SCORE > 60;

-- 5. Strong Uptrend confirmation audit: review any rows returned here.
SELECT SYMBOL, TRADING_DATE, SCORE, TREND, TREND_DECISION_REASON, SCORE_BREAKDOWN_JSON
FROM TECHNICAL_SCORE_LATEST
WHERE TREND = 'Strong Uptrend'
  AND (
    NVL(EMA20, 0) <= NVL(EMA50, 999999999)
    OR NVL(EMA50, 0) <= NVL(EMA100, 999999999)
    OR NVL(EMA100, 0) <= NVL(EMA200, 999999999)
    OR (ADX14 IS NOT NULL AND ADX14 < 25)
    OR (VOLUME_RATIO_20 IS NOT NULL AND VOLUME_RATIO_20 < 1.2 AND NVL(DELIVERY_REL_20, 0) < 1.1)
  );

-- 6. Missing-input distribution for troubleshooting.
SELECT MISSING_INPUTS_JSON, COUNT(*) AS ROW_COUNT
FROM TECHNICAL_SCORE_LATEST
GROUP BY MISSING_INPUTS_JSON
ORDER BY ROW_COUNT DESC;

-- 7. Score/trend distribution.
SELECT TREND, SCORE_GRADE, COUNT(*) AS ROW_COUNT, ROUND(AVG(SCORE), 2) AS AVG_SCORE
FROM TECHNICAL_SCORE_LATEST
GROUP BY TREND, SCORE_GRADE
ORDER BY MIN(TREND_SORT), SCORE_GRADE;

-- 8. View smoke test.
SELECT *
FROM VW_TECHNICAL_SCORE_LATEST
WHERE ROWNUM <= 20
ORDER BY TRADING_DATE DESC, SCORE_SORT DESC;
